### ISSUE TITLE
Reindex an index without a Blue/Green Migration

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1532]
@mmarcotte to follow up with more information here...

Small spike to dig into how we could leverage aliases for indexes. This may allow us to re-index to another index, and then point our alias to that newly reindexed index. and have no downtime.

**Comment by mmarcotte** [comment]
Some discovery here with using aliases, which would be easy enough to implement. However, it would necessitate some downtime while the reindexing was occurring because it could not receive writes, ie those live writes would not get reindexed as the job will have already started.

**Comment by mark-meyer** [comment]
It is not difficult to change ef-cms elasticsearch indices to use aliases instead of directly referencing the index. This could be done with a simple change to [elasticsearch-index-settings.js](https://github.com/ustaxcourt/ef-cms/blob/staging/web-api/elasticsearch/elasticsearch-index-settings.js#L45):

```
searchClientCache.indices.create({
            body: {
              aliases: {
                [index]: {}
              },
              mappings: {
                dynamic: false,
                ...mappings[index],
              },
              settings,
            },
            index: `${index}-concrete`,
          });
```
This would create an alias like `efcms-case` pointing to the actual index `efcms-case-concrete`

With that change it is possible to create another index with a different mapping and reindex into it with something like:

```
POST /_reindex
{
    "source": {
        "index": "efcms-case-concrete"
    },
    "dest": {
        "index": "efcms-case-concrete_ii"
    }
}
```

At this point you have two indices and can freely (and atomically) switch between them:

```
POST /_aliases
{
  "actions": [
    {
      "remove": {
        "index": "efcms-case-concrete_ii",
        "alias": "efcms-case"
      }
    },
    {
      "add": {
        "index": "efcms-case-concrete",
        "alias": "efcms-case"
      }
    }
  ]
}
```

This may be useful for some things, but currently does not solve the problem of blue-green migrations in production.The primary problem is that while you are reindexing to the new index, the app could potentially be writing to the old index which could result in data loss.
