### ISSUE TITLE
Test reliability for Downloading Trial Sessions

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1689]
We are going to be having more trial sessions, and the Court users are going to need to download these documents ahead of the Trial Sessions. 

- Let's try to downloading the big ones. 
- Make sure that you're using a Court laptop
- Look for one that's a really large case.
- These requests cannot take longer than 15minutes

**Comment by ttlenard** [comment]
Did some tests today.  Was able to download all cases, and all downloaded to my computer well, but ran into issues when attempting to extract or just open files that I had downloaded.  I attempted to download all cases from the following trials. 

- 12-26-2021 - New Orleans, Louisiana - When I clicked on the zip folder, I got this message:

![image](https://user-images.githubusercontent.com/87717140/135928809-7d3c8d95-433c-4981-93f0-88e767326ce5.png)

- 12-14-21 - Tampa, Florida - When I clicked on the zip folder, it opened the files. I clicked on one of the cases and when I attempted to open this long named file, I got this error:

![image](https://user-images.githubusercontent.com/87717140/135929026-247e86c5-8d59-4c40-b361-e4a335d7d6db.png)


- 10-25-21 - Los Angeles, California - I got the same behavior as Tampa when attempting to open some of the documents.

*Note - I did a screen share with Mike. We attempted to copy over the zip file to a different folder on my computer (my c drive), but we were still getting the error message.  Mike WAS able to open the New Orleans file on his MAC.  He is going to make a code tweak and shorten the file name and then we will see if we have more success.  Since we have the Printable docket record as one of the downloaded files, Mike and I were proposing that each of the individual files includes the Docket entry number, and the Event Code, rather than the entire name of the file, since these file names are HUGE!

**Note: This issue appears to be the same as what was reported in [https://github.com/flexion/ef-cms/issues/8222]

**Comment by ttlenard** [comment]
Mike adjusted the file name and the downloads have been working like a charm!  @JessicaMarine recommended that instead of the event code we just truncate the file name so that it is more familiar to Judges and Trial Clerks. Maybe this could be the new suggested format? Date_Docket entry #_First 10 characters of File name.  Would this end up making sense? Do we need to add more than 10 characters for clarity?

2021_01_19_0001_PETITION
2021_01_19_0002_Request fo
2021_01_06_0003_Applicatio
2021_02_02_0004_Answer
2021_02_03_0005_Notice of

**Comment by ttlenard** [comment]
Mike pushed an update so that only 64 characters remain in the file name.  I was able to open individual files and able to unzip the folder for both the trial sessions that I had issues with before.

- 10-25-21 - Los Angeles, California
- 12-26-2021 - New Orleans, Louisiana

This one passes @mmarcotte. Thank you for updating this so that we can successfully download these cases!

**Comment by mmarcotte** [comment]
Merged fix to reduce filename length to 64 characters.
