### ISSUE TITLE
Modify Lansweeper for issue tracking.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#237]
As the Product Owner of EF-CMS, so that I can maintain a secure and functioning application, I need to track any defects reported so they can be prioritized and fixed.

**Comment by julialeague** [comment]
This should include training on how to use the system.

**Comment by vickimcfadden** [comment]
Related to support plan #238.

**Comment by mmarcotte** [comment]
LanSweeper has a DAWSON tag and basic workflows for the OIS Team to use. Training for them on how to support the product is tracked with #412 .  There is an immense amount of documentation baked into the application. The E-Help position will have access to this; however, the Admissions section will not.  Additionally, it is no longer the place we are directing Court Staff to send their issues, and LanSweeper will only be used if a Court user emails the helpdesk instead of the support email.
