### ISSUE TITLE
Complete final accessibility testing.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#252]
Perform both automated and manual testing with users who are familiar users of assistive devices to ensure the site is not only meeting it’s legal obligations for accessibility but it is fully functional and useful.

Most interested in *public-facing* flows of an external user. May be able to get work flows from Kristen. Exclude accessibility of Court documents. 18F do microrequest to Accessibility Guild. Prioritize P1 (show stopper!), P2, etc. Add to this GitHub and tag with `accessibility` label.

**Comment by JessicaMarine** [comment]
Flexion is willing to assist with this task.  https://github.com/flexion/ef-cms/issues/4495

**Comment by vickimcfadden** [comment]
Put in an 18F micro-staffing request on 11/17 and asked that work be completed by 12/11.

**Comment by vickimcfadden** [comment]
For testing we'll use the stg environment as the testing will be focused on the frontend and won’t interfere with (or be interfered by) activities in other environments.
https://stg.ef-cms.ustaxcourt.gov/

**Comment by vickimcfadden** [comment]
We have an 18F engineer identified that can start this work on ~11/30.

**Comment by vickimcfadden** [comment]
external user workflows: https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?ts=5fb688d1#gid=215623579

**Comment by adunkman** [comment]
Attempting to assign @echappen and failing miserably. 😅

**Comment by echappen** [comment]
Alrighty, just finished up manual Accessibility testing!

### Summary
- I found no "show stoppers" or anything that should prevent going live. The team has done a great job overall with ensuring A11y!
- I found some minor improvements to specific markup, and a few refinements for easier screen reading. I'll itemize these in separate issues. 
- I found some potential improvements for authentication pages, which I'll bundle into a single issue. Since the app is using[ Amazon Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html) for its authentication, there may be limits on what can be changed, but I figured they're still worth noting. 

### Methodology
- Using the guides for [Public](https://docs.google.com/document/d/1j-MDjGuVyqdMuyAbGk12nMqRCKSw-4iKu9Hd5MrLb4Q/edit), [Petitioner](https://docs.google.com/document/d/1dcbhAU_lUbGdkO5Q6WvHYEAxVFJvyWArNT51_QXqg4k/edit), and [Practitioner](https://docs.google.com/document/d/11KELjrDTd0NVxap1VaoWY3y-HXqUXS1Z8yC6NsibH0M/edit#), I went through the key flows for each user type.
- For each page, I ran both a [Chrome Lighthouse](https://developers.google.com/web/tools/lighthouse) Accessibility scan and a [WAVE Evaluation](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) scan
- For manually testing each page, I used [VoiceOver for Mac](https://www.apple.com/voiceover/info/guide/_1121.html) for Chrome, Safari, and Firefox browsers, and occasionally [ChromeVox Classic](https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) for Chrome
- For mobile testing, I went through searching records and creating a case using [VoiceOver](https://www.apple.com/accessibility/iphone/) on an iPhone 6S.

Thank you Tax Court Team for making this work a priority 🤟 💟 🥇

**Comment by waldoj** [comment]
I want to take this chance to give a shout-out to @kkoskelin, who (at least during my time with the project) led the work of centering accessibility at every step of the way. It was rare that I found an accessibility problem when reviewing the PR at the end of each sprint, and when I did Kris always approached it thoughtfully and resolved it well. I'm not surprised to hear that there were no significant problems, but I am happy to hear it!
