### ISSUE TITLE
Document the security incident response plan.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#306]
As the Court, so that we can maintain a secure system, we need to be able to understand and address security incidents when they occur. 

Notes:

- Broken out from #244, results from this issue should be documented in the Site Operating Plan.

Remaining Tasks:
- [ ] It would be great to add a couple light sections on how and who will be trained on this process and how it will be tested. per controls IR-2 and IR-3.
- [ ] clarify the processes between the checklist and the guidelines
- [ ] remove cloud.gov ref

**Comment by mmarcotte** [comment]
@lauraGgit -- I'd appreciate you having a look at the current Security Incident documentation, and letting me know if you think there are any holes? 

* [Security Incident Response Checklist](https://github.com/ustaxcourt/ato/blob/master/Security-Incident-Response-Checklist.md)
* [Security Incident Response Guidelines](https://github.com/ustaxcourt/ato/blob/master/Operating-Plan.md#security-incident-response)
* [Security Incident Issue Template](https://github.com/ustaxcourt/ato/issues/new?assignees=mmarcotte&labels=security+incident&template=security-incident-template.md&title=)

**Comment by lauraGgit** [comment]
@mmarcotte Overall this looks very comprehensive and I think the team would be well set up to move if there were an incident. I just have a couple of comments on how the team with be prepared (and know this exists) and on organization.

It would be great to add a couple light sections on how and who will be trained on this process and how it will be tested. per controls [IR-2](https://nvd.nist.gov/800-53/Rev4/control/IR-2) and [IR-3](https://nvd.nist.gov/800-53/Rev4/control/IR-3). 

In looking at this the naming feels a bit confusing on where to start between the guidelines and the checklist. In the guidelines, it looks like its a discussion more of contingency planning specifically and has a somewhat different definition of incident than the Checklist. Other than an overall disruption, I'm not sure I'd totally understand the relationship between the two - in part possibly because of the cloud.gov mentions (see below). Also, perhaps more of the elements in the checklist could go directly into the Security issue template?


Also: in the [activation](https://github.com/ustaxcourt/ato/blob/master/Operating-Plan.md#activation) of the guidelines section there is a reference to cloud.gov that doesn't seem applicable here.

**Comment by mmarcotte** [comment]
@lauraGgit -- thank you so much for your direction. I've created a PR over in the ATO repo to address.
