### ISSUE TITLE
Edit Site Footer -- Show support email, monitoring notice to users (AC-8 Notice to users).

### ISSUE THREAD

**Issue by lauraGgit** [ustaxcourt/ef-cms#509]
Added to Flexion's backlog: https://github.com/flexion/ef-cms/issues/7142

## Acceptance Criteria
- [ ] system users understand they are being monitored and recorded
- [ ] system users know where to email for support
- [ ] hiding the "deployed on" message on the production environment (leave for other enviros)
- [ ] hide the `test environment` bar at the top of the production environment (leave for other enviros)
- [ ] add story to flexion backlog

## Notes

- We are already using the USWDS banner so that is a start but we should add a bit more about the notice to users

- Would be good to have the following:
  > Displays references, if any, to monitoring, recording, or auditing that are consistent with privacy accommodations for such systems that generally prohibit those activities; and Includes a description of the authorized uses of the system.

**Comment by mmarcotte** [comment]
So, it sounds like we should add a backlog item that details [the requirements of AC-8](https://nvd.nist.gov/800-53/Rev4/control/AC-8). That is a lot of information. Does it need to live on every page? Its own page? I'll consult with @JessicaMarine about where it should best live.

**Comment by adunkman** [comment]
Folks often have this information on a login page, but since there are public sections of the application, it may make sense to add it to a header or footer. Laura’s suggestion was to extend the USWDS banner notice: 

![Screenshot of the USWDS banner](https://user-images.githubusercontent.com/14930/98550685-687f8f00-226a-11eb-991f-61db976e9aa2.png)

We could also find an area of the footer to add information. 

Here’s Cloud.gov’s notice, for reference. They have the notice on their login page: 

| On the page | Read more details |
|-------------|-----------|
| ![image](https://user-images.githubusercontent.com/14930/98550881-a41a5900-226a-11eb-89cf-de33376051b7.png) | ![image](https://user-images.githubusercontent.com/14930/98550974-c3b18180-226a-11eb-8323-0afc848433a6.png)

**Comment by vickimcfadden** [comment]
Vicki to spin up a google doc and share with Court, 18F, and Kristen. Kristen to mock it up so Jessica can present it to Court stakeholders.

**Comment by vickimcfadden** [comment]
Draft text: https://docs.google.com/document/d/1ElURC1PBdSjAgl2PVPePKt6o8ykJWXk6jZPTgugU6xA/edit#

**Comment by vickimcfadden** [comment]
Kristen mocked up a figma file and will share with Jessica to share with the Court for approval.

**Comment by vickimcfadden** [comment]
Jessica received feedback from Judges, Kristen mocked up new files, those are with the Judges for final approval. Jessica will add a story to the Flexion backlog to incorporate this work.
