### ISSUE TITLE
File a Petition 

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6773]
Petitioner:
* Receive warning about POAs, CPAs, etc. not being able to file for a third party

Petitioner and Practitioner:
* Receive warning about timeliness of filing petition and are informed of options for mailing

**Comment by ttlenard** [comment]
11-4-21 - Tier 1 helpdesk reported that they are seeing an uptick in 2 things:

- Duplicate Petitions filed by Petitioner

Usually this happens when Petitioner mails in with a paper petition, and THEN also eFiles or vice versa.  Due to backlog, it is taking Petitions clerks longer to process all of the petitions.  Recent example was that it took around 2 months for paper petition to be processed, and around 1 month to process electronic petition.

Might need to consider updating DAWSON UI to help prevent this from happening?  Additional warnings? Update Website? Update workflow?

- Private Practitioners signing up for a pro se petitioner account in DAWSON and filing a petition for their client.

Private Practitioners do not sign up for accounts like the pro-se petitioners do. They actually get access when they are admitted to the Tax court, or  they are supposed to request access via dawson.support@ustaxcourt.gov.  If Private Practitioners accidentally do this (this is becoming more common), the helpdesk staff do have an automation that Mike created that delete's their "oopsie" account in cognito, and associates their cases with their Practitioner account.

Might need to consider updating DAWSON UI to help prevent this from happening?  Additional warnings? Update Website? Update workflow?
