### ISSUE TITLE
Court User: Ability to modify case caption/docket number on DAWSON generated orders/notices in Lead Case

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6901]
As a court user, so that I can accurately reflect the scope of an order or notice, I need to be able to modify the case caption and docket numbers on the header of a generated order or notice in a Lead Case.

When a document is filed in a case that is part of a consolidated group (CG), it is necessary to have that document reflected on the docket record for some or all of the other cases part of that group. Currently, when creating orders for cases in a CG, users must create them outside of DAWSON and then upload them via PDF, in large part because currently the system currently generates captions for the immediate case only.

We would like the Court to have the ability to modify the case caption when generating orders/notices in consolidated Lead Cases to add ", et al." to the Petitioners portion of the caption and add any other cases in the CG to the Docket No. portion of the caption.

See screenshot of attached order w/ caption for consolidated case example.

## Pre-Conditions
ustaxcourt/ef-cms#6969

## Acceptance Criteria
* When creating or editing a document on the Lead Case in a consolidated group, on the Create/Edit screen for the document, the user can indicate that the document caption should be modified
* The user can select which case numbers from the consolidated group should be added to the caption
  - The default for this should be to add _all_ cases from the consolidated group
* When the caption is modified, the Lead Case petitioner's name in the caption should be appended with ", ET AL.," (see screenshot)
* When the caption is modified, the Lead Case docket number in the caption should be followed by the comma-separated values of all other cases in the group selected by the user (see screenshot)
* The Preview tab should show the modified case caption (if modified)
* User can choose to de-select the option to modify the caption
* This applies to user-generated Court orders and notices; auto-generated orders and notices are not in scope for this story.

## Notes
Example of caption on consolidated case order: ![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/c563d71a-8cef-4e29-af07-897e3207ab59)

## Test Cases
* User generates a document in the Lead case of a consolidated group; chooses to modify the caption contents of the document; all other cases in the CG are marked for inclusion; user writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying all other cases in the CG; saves document; document appears as Draft with modified caption
* User generates a document in the Lead case of a consolidated group; chooses to modify the caption contents of the document; some (not all) of the other cases in the CG are marked for inclusion; user writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying only those cases marked for inclusion; saves document; document appears as Draft with modified caption
* User generates a document in the Lead case of a consolidated group; does not choose to modify the caption; user writes the document; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption
* User generates a document in a member case of a consolidated group; is not presented w/ option to modify caption; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption
* User generates a document in a case that is not part of a consolidated group; is not presented w/ option to modify caption; document preview displays normal caption contents for petitioner and docket number; saves document; document appears as Draft with normal caption

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to the Court's `test` environment for PO Review

**Comment by swongCO** [comment]
![Create Order.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/5401b6be-1009-401a-8c24-a47f8cc42266)
- For lead cases, display icon link beneath Generate tab **[NEW]** with link text "Add docket numbers to the caption"
–––––
![Create Order - add modal.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cd0b82ff-3c90-4b73-8cff-07d55fa204b9)
When add link is clicked, display modal with the following text changes:
1. Title: Add Docket Numbers
2. Body: Select cases that you want to add to the caption<s> of the cover sheet</s>. Petitioner’s name will be automatically appended with “ET AL.” if more than one case is selected.
3. Primary CTA: Add Docket Numbers
4. If only the lead case is selected, do not append petitioner's name with "ET AL."
–––––
![Edit flow.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/47a67511-14ae-4b9e-b3c9-16f77f7c3312)
In the edit flow:
1. Change the [+] icon to the edit icon (same as in Edit Title)
2. Change the link text to "Edit docket numbers in the <s>cover sheet</s> caption"
–––––
![Edit flow - modal.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/804b76bd-3708-483f-a64b-e3f5fbaf45e6)
1. Change the modal title to "Edit Docket Numbers"
2. Primary CTA = Save

**Comment by ttlenard** [comment]
## Test Cases

#### 1.1) User generates an Order/Notice in the Lead case of a consolidated group; chooses to modify the caption contents of the document. 
- Log in as a Docket Clerk, ADC, Petitions Clerk or Chambers User
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select Order or Notice
- Select any Order or Notice option from the dropdown 
- Click Continue

Expected Results
- [x]  **NEW FUNCTIONALITY** - On the Create Order/Notice screen, there will be a link that states, "Add docket numbers to the coversheet"


#### 1.2) User selects all other cases in the CG for inclusion
- Continuing from Test case 1.1
- Click on the link for "Add docket numbers to the coversheet"
- Leave the default selection for "All cases in the Consolidated Group"


Expected Results
- [x] **NEW FUNCTIONALITY** - New Modal appears and has the default selection for "All cases in the Consolidated Group" checked.


#### 1.3) User writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying all other cases in the CG.
- Continuing from Test case 1.2
- Click "Add Docket Numbers"
- Create some draft text
- Click on the Preview tab

Expected Results
- [x] **NEW FUNCTIONALITY** - The case caption in the preview window will now have "ET AL.," appended to the Petitioner name from the Lead case in the CG.
- [x] **NEW FUNCTIONALITY** - The list of all the docket numbers that you selected in Test case 1.2 will be listed


#### 1.4)  User saves document; document appears as Draft with modified caption
- Continuing from Test Case 1.3
- Click save at the bottom of the screen (can be from the preview tab or the Generate tab)
- If the document was an Order, Apply a signature and then click "Save Signature"

Expected Results
- [x] You are routed to the Drafts tab
- [x] **NEW FUNCTIONALITY** - The case caption in the document from the drafts tab will now have "ET AL.," appended to the Petitioner name from the Lead case in the CG.
- [x] **NEW FUNCTIONALITY** - The list of all the docket numbers that you selected in Test case 1.2 will be listed



#### 2.1) User generates an Order or Notice in the Lead case of a consolidated group; chooses to modify the caption contents of the document.
- Log in as a Docket Clerk, ADC, Petitions Clerk or Chambers User
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select Order or Notice
- Select any Order or Notice option from the dropdown 
- Click Continue

Expected Results
- [x] **NEW FUNCTIONALITY** - On the Create Order/Notice screen, there will be a link that states, "Add docket numbers to the coversheet"


#### 2.2) User chooses some (not all) of the other cases in the CG for inclusion; 
- Continuing from Test case 2.1
- Click on the link for "Add docket numbers to the coversheet"
- Uncheck the default selection for "All cases in the Consolidated Group"
- Select a few of the cases (not all)


Expected Results
- [x] **NEW FUNCTIONALITY** - The lead case remains checked (and cannot be de-selected)
- [x] When hovering over the Lead case in the CG in the modal, the hover over help text should indicate that the lead case cannot be unselected)
- [x] Other cases in the CG can be checked/unchecked from the Modal


#### 2.3) User writes the document; document preview displays modified caption contents for petitioner and docket numbers displaying only those cases marked for inclusion.
- Continuing from Test case 2.2
- Click "Add Docket Numbers"
- Create some draft text
- Click on the Preview tab

Expected Results
- [x] **NEW FUNCTIONALITY** - The case caption in the preview window will now have "ET AL.," appended to the Petitioner name from the Lead case in the CG.
- [x] **NEW FUNCTIONALITY** - The list of the docket numbers that you selected in Test case 2.2 will be listed


#### 2.4) User saves document; document appears as Draft with modified caption
- Continuing from Test Case 2.3
- Click save at the bottom of the screen (can be from the preview tab or the Generate tab)
- If the document was an Order, Apply a signature and then click "Save Signature"

Expected Results
- [x] You are routed to the Drafts tab
- [x] **NEW FUNCTIONALITY** - The case caption in the document from the drafts tab will now have "ET AL.," appended to the Petitioner name from the Lead case in the CG.
- [x] **NEW FUNCTIONALITY** - The list of the docket numbers that you selected in Test case 2.2 will be listed



#### 3.1) User generates an Order/Notice in the Lead case of a consolidated group.
- Log in as a Docket Clerk, ADC, Petitions Clerk or Chambers User
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select Order or Notice
- Select any Order or Notice option from the dropdown 

Expected Results
- [x] **NEW FUNCTIONALITY** - On the Create Order/Notice screen, there will be a link that states, "Add docket numbers to the coversheet"


#### 3.2) User does not choose to modify the caption. User writes the document; document preview displays normal caption contents for petitioner and docket number; 
- Continuing from Test case 3.1
- Do NOT click on the link for "Add docket numbers to the coversheet"
- Create some draft text
- Click on the Preview tab

Expected Results
- [x] The case caption in the preview window will **NOT** have the "ET AL.," appended to the Petitioner name from the Lead case in the CG.
- [x] The docket number listed is the lead cases docket number.


#### 3.3) User saves document; document appears as Draft with normal caption
- Continuing from Test Case 3.2
- Click save at the bottom of the screen (can be from the preview tab or the Generate tab)
- If the document was an Order, Apply a signature and then click "Save Signature"

Expected Results
- [x] You are routed to the Drafts tab
- [x] The case caption in the document from the drafts tab will **NOT** have "ET AL.," appended to the Petitioner name from the Lead case in the CG.
- [x] The docket number listed is the lead cases docket number.


#### 4.1) User generates an Order/Notice in a member case of a consolidated group; is not presented w/ option to modify caption; 
- Log in as a Docket Clerk, ADC, Petitions Clerk or Chambers User
- Navigate to a member case in a consolidated group (I used case 17497-17)
- Click Create and select Order or Notice
- Select any Order or Notice option from the dropdown 
- Click Continue

Expected Results
- [x] On the Create Order/Notice screen, there will **NOT** be a link that states, "Add docket numbers to the coversheet"


#### 4.2) User writes document, document preview displays normal caption contents for petitioner and docket number; 
- Continuing from Test case 4.1
- Create some draft text
- Click on the Preview tab

Expected Results
- [x] The case caption in the preview window will **NOT** have the "ET AL.," appended to the Petitioner name from the  case in the CG.
- [x] The docket number listed is the member cases docket number.


#### 4.3) User saves document; document appears as Draft with normal caption
- Continuing from Test Case 4.2
- Click save at the bottom of the screen (can be from the preview tab or the Generate tab)
- If the document was an Order, Apply a signature and then click "Save Signature"

Expected Results
- [x] You are routed to the Drafts tab
- [x] The case caption in the document from the drafts tab will **NOT** have "ET AL.," appended to the Petitioner name from the member case in the CG.
- [x] The docket number listed is the member cases docket number.



#### 5.1) User generates a document in a case that is not part of a consolidated group; is not presented w/ option to modify caption.
- Log in as a Docket Clerk, ADC, Petitions Clerk or Chambers User
- Navigate to a case that is NOT in a consolidated group 
- Click Create and select Order or Notice
- Select any Order or Notice option from the dropdown 
- Click Continue

Expected Results
-  [x] On the Create Order/Notice screen, there will **NOT** be a link that states, "Add docket numbers to the coversheet"


#### 5.2) User writes document; document preview displays normal caption contents for petitioner and docket number.
- Continuing from Test case 5.1
- Create some draft text
- Click on the Preview tab

Expected Results
- [x] The case caption in the preview window will **NOT** have the "ET AL.," appended to the Petitioner name from the  case.
- [x] The docket number listed is the cases docket number.


#### 5.3) User saves document; document appears as Draft with normal caption
- Continuing from Test Case 5.2
- Click save at the bottom of the screen (can be from the preview tab or the Generate tab)
- If the document was an Order, Apply a signature and then click "Save Signature"

Expected Results
- [x] You are routed to the Drafts tab
- [x] The case caption in the document from the drafts tab will **NOT** have "ET AL.," appended to the Petitioner name from the case.
- [x] The docket number listed is the cases docket number.



#### 6.1) User generates an Order/Notice in the Lead case of a consolidated group; chooses to modify the caption contents of the document. 
- Log in as a Docket Clerk, ADC, Petitions Clerk or Chambers User
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select Order or Notice
- Select any Order or Notice option from the dropdown EXCEPT for the following:
     - Order of Dismissal and Decision
     - Order and Decision
     - Decision
- Click Continue

Expected Results
- [x] **NEW FUNCTIONALITY** - On the Create Order/Notice screen, there will be a link that states, "Add docket numbers to the coversheet"


#### 6.2) User selects "Take me Back", instead of selecting "Add Docket Numbers"
- Continuing from Test case 6.1
- Add some text in the document from the generate tab
- Click on the link for "Add docket numbers to the coversheet"
- Leave the default selection for "All cases in the Consolidated Group"
- Click "Take me Back"

Expected Results
- [x] **NEW FUNCTIONALITY** - The user is navigated back to the generate tab.
- [x] When previewing the document from the preview tab, the case caption in the document will **NOT** have "ET AL.," appended to the Petitioner name from the Lead case.
- [x] The docket number listed is the Lead cases docket number.

#### 7) Regression test the workflow to add the docket entry (from story 3569) to ensure all works as designed.
- From the drafts tab, click add docket entry.

Expected Results
- [x] Workflows outlined in 3569 function as designed.

~~#### 8) Regression test by clicking "Edit Title" in the Create Order/Notice screen.~~
~~- Test by selecting a non-decision type order, and then editing the title to a decision type Order.~~
~~- Test by selecting a decision type order first, and then editing the title to a non-decision type order.~~

~~Expected Results~~
~~- [ ] The link to add docket numbers to the cover sheet should not appear if the Order is a decision Order~~
~~- [ ] The link to add docket numbers to the cover sheet SHOULD be present when switched to a non-decision type Order~~

#### 9) Regression test this story with the Feature Flag set to Off

**Comment by codyseibert** [comment]
From a discussion, some additional changes we plan to do include:

Edit Model
  - show this when only lead case is selected
    - "ET AL." will not be appended to the caption.
  - change button to "Save"
  - change title to "Edit Docket Numbers"
  - change main link to "Edit" instead of Add

**Comment by swongCO** [comment]
UX feedback:
![Screen Shot 2022-09-07 at 2.00.50 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cc592fb1-7001-419b-81e4-66d377b0cbd5)
There is extra spacing in front of "Docket..." in the docket number section so when it wraps to a second line, they are not left aligned. 

![Screen Shot 2022-09-07 at 1.59.34 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/18932f1f-30ee-4676-84d5-8f7fd7602867)
When I created a Notice and edited it, the edit modal is not showing any of the cases in the group, only the All checkbox. 

Steps to reproduce:
1. Go to any lead case
2. Create an order or notice
3. Add docket #s (I used the All default)
4. Save the document
5. In Drafts, click Edit
6. Click Edit docket #s
7. Modal does not show the cases

**Comment by liadmccabe** [comment]
@codyseibert UX recommendation: Wrap second sentence so that it continues from the first. (i.e. next sentence should start immediately after the word 'caption' rather than start in the next line).  ![Screen Shot 2022-09-13 at 2.00.23 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/e0464180-8c9a-452c-b971-7230808b627b)

**Comment by ttlenard** [comment]
Note: In test case 8, the link to add docket numbers to the caption WAS present for decision type of orders.  I did some additional testing, and Docket is still not able to docket across cases in a consolidated group for decision types of documents, so @cholly75 indicated that it will be fine.  Court users that are creating Orders should know that they are not supposed to file these types of orders across multiple docket numbers.  

I left the original test case in the Test cases section, but put a strikethrough in it.
