### ISSUE TITLE
Mobile Refinement Needed

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7036]
## Acceptance criteria:
* Any public-facing aspect of the site is thoroughly tested on mobile
* Issues documented
- [ ] Create a case instruction accordions could be full-width on mobile
Currently they're only ~60% width and it makes reading the accordion content awkward.
- [ ] "Deployed At" timestamp often overlays on top of buttons, making the buttons un-tappable.
Continued scrolling solves it, but this could be confusing to general users.
- [ ] When pop-ups are blocked in mobile Safari, tapping links to files does nothing, giving the impression that links are broken. Since file viewing is critical to user flows, a pre-emptive alert to allow pop-ups may help.

See also: https://github.com/ustaxcourt/ef-cms/issues/251

**Comment by klohman** [comment]
Testing list 

- eFile a petition (as petitioner) 
- eFile a petition (as practitioner)
- File a Document (Primary document and Supporting Document) - petitioner
- File a Document (Primary document and Supporting Document) - petitioner
- File a Document (practitioner)
- Request Access to Case (practitioner)
- File First IRS Document (irs pracititoner)
- Request Access to Case (second irsPractitioner on case) - (irs pracititoner)
- Practitioner edits contact information
- Petitioner edits contact information
- Public search for case 
- Public search for orders 
- Public search for opinions 
- Public view Today's Opinions

**Comment by klohman** [comment]
### Design Notes 
- File a doc - Success message/Print receipt styling is off 
![Screenshot_20201014-152719.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/71754801-a4c2-4b29-924c-fad2799e979d)

- File a document - What can I include in this document link is centered and should be left-aligned (design issue)
![Screenshot_20201014-164433.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8f9bc8b5-ebf5-42ad-9ef2-cbe61ebdc287)

- Spacing on Case Information screen is off
    - Requested place of trial spacing (mobile) 
![Screenshot_20201019-093638.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1321d741-3874-4f40-8a6e-0fbda12bb9e4)

- Petitioner name spacing (mobile and desktop)
![Screenshot_20201019-093647.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cdc5eb47-ab57-472b-b4ea-70e192985ed7)

- Need to update tabs on Advanced Search to dropdown menu on mobile (added to ustaxcourt/ef-cms#7145)
![Screenshot_20201014-170537.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bfe804e7-f01a-42d2-bed0-2484ef9c1a45)

- Public Case Detail - needs spacing above Docket Record tab
![Screenshot_20201019-094812.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c628bf47-0358-4a91-8d7f-c34f549ed3f5)
 
- “You will be able to file documents after the Petition is processed” message needs spacing above 
![Screenshot_20201019-093647.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/51efe93d-81f8-442c-8485-325a931fcacf)


- Filename not wrapping properly on PDF upload (iphone) 
![Screen Shot 2020-10-20 at 9.48.16 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/55368f92-9068-4576-997d-fce5b28ebae0)


### Usability Notes 
- Difficult to find the call-to-action on the dashboard due to the amount of instructional text above the button and the size of the button  
- “Deployed [date]” footer blocking the view of actual content
![Screenshot_20201014-145435.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1d982cd0-0dd7-41bf-9e8f-5fad0e944848)

- Inconsistency of how PDFs are treated when clicked among different devices (sometimes downloading PDF file automatically, sometimes opening in new tab (safari, iPhone 7) 

- Dashboard with Open Cases lacks appropriate hierarchy and clear direction 

- Case Detail screen (Docket record) view lacks appropriate hierarchy and clear direction; should be redesigned

- Docket record blank columns need blank state on  Document Detail screen “N/A” (mobile only)

![Screenshot_20201019-093601.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9d2dc5b1-37ce-423b-a8e4-51e1acd5d4e8)

- Opinion search results not optimized for mobile (story in backlog ustaxcourt/ef-cms#7145)
- Today’s Opinions on mobile is not optimized for mobile story in backlog ustaxcourt/ef-cms#7145)
- Phone number field - brings up numeric keyboard - could be a problem if users need to enter text
- File a Document form - missing space between stacked buttons (bug) 
- Searches - need feedback after user clicks search - results may be displayed but there is nothing to indicate user needs to scroll to see them (seen on iPhone simulator)

**Comment by klohman** [comment]
### Bugs
- Docket Record - Filings and Proceedings column is not always left aligned (bug) - Logged 6778
- Mobile is still showing “Need help selecting a document” link on the “What Document Are you Filing? (Bug) = 6780 logged 
- Dashboard is missing Search Card, Filing Fee card, and Contact info card (bug) - ustaxcourt/ef-cms#7378 logged 
- (Mobile) Printable Docket Record - for Public- not displaying PDF - logged ustaxcourt/ef-cms#7385
- (Mobile) Incorrect tab title displaying in dropdown on Case Detail ( page is displaying Petitioner tab but dropdown displays Docket Record) - logged ustaxcourt/ef-cms#7389
- iPhone - BUG: (Mobile) - No response when clicking on document link from order or opinion search ustaxcourt/ef-cms#7406
- (Desktop and mobile) case Information tab does not appear for Petitioner [6845](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/6845)
- (Mobile) External user clicks on Printable Docket Record = no response ustaxcourt/ef-cms#7410

**Comment by klohman** [comment]
@kimschulke Can you add any design and usability issues and functional bugs you encounter on mobile via iPhone here as a comment? For bugs, you can also log them as a separate Zenhub issue and just note the issue number here for tracking.

**Comment by cholly75** [comment]
Handling via individual stories/ongoing dev  work.
