### ISSUE TITLE
Final accessibility review of all public-facing aspects of site

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7072]
## Acceptance Criteria:
* Final accessibility test the unauthenticated public site, file a petition and file a document.
* Document issues

## How to Accessibility-check the public site (or any site/page)

* Identify a workflow that you want to execute, and know how to do it with keyboard and mouse as an average-ability user would do.
* Execute the workflow with “plain” keyboard navigation (in the browser of your choice)
    * Use keystrokes like TAB, SPACEBAR, ENTER, ARROW-KEYS, ESC
    * Keyboard navigation should reveal an outline indicating the active element at all times.
    * You should never be able to focus an element that cannot be interacted with (e.g. an h1)
    * Ensure forms used for searches can be actuated by hitting the “enter” key when search input field is in focus
* Execute the workflow on OS X with Safari + VoiceOver (CMD+F5)
    * Ensure that VO keyboard navigation can reach all focusable elements on the page
    * Ensure that forms, inputs, buttons all have descriptive labels (using aria-label, aria-describedby, aria-labelledby) which can read-about a complete phrase which accurately reflects the intent of the item selected to someone who is sight-impaired.  For example, rather than “date”, an input might say “Opinion Search, narrow your search, start date”.

See also: https://github.com/ustaxcourt/ef-cms/issues/252

**Comment by kkoskelin** [comment]
After reviewing and making some simple changes, there are other things we might want to consider from both a usability and accessibility perspective.
**High Priority, fix before launch**
* Date-picker issue: https://trello.com/c/u08W0P2Y/829-date-picker-year-not-visible -- the year is not always visible in the date-picker, and it's quite dreadful on the public UI at the moment.  Making the start and end dates full-width (one above the other) would solve both problems
![Screen Shot 2020-10-08 at 9 51 21 AM](https://user-images.githubusercontent.com/2445917/95475461-dc690780-094b-11eb-937c-c4ae07870a48.png)

**Other considerations**
* Should search results REMAIN on the page when we go back, rather than disappearing? I feel they should stay unless we activate a new search.
* Should there be a “back to search results” button? (Combine with above question)
* Should the label for (Case) “Search by Name” say instead “Search by Petitioner” (because they use name, date, country and state?)  As a VO user, it might be more descriptive to me explaining the kind of search form I'm using -- that it's not just searching the name.
