### ISSUE TITLE
Revisit Notice of Docket Change

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7078]
* Allow Docket to free-text additional reasons for change
* Judge Buch wants it to be more descriptive (from January 2020 Round-Table)

**Comment by ttlenard** [comment]
@cholly75 We had a ZenDesk ticket come through that was requesting this feature as well. https://ustaxcourt.zendesk.com/agent/tickets/12713

This particular scenario had to do with a case (4806-15) that had an opinion that was coming out, so docket was ensuring that the docket record was clean and accurate.  Docket wanted to update the filings and proceedings column so that the wording of the docket entry text was correct.  The notice of docket change entries are currently NOT editable, so they were unable to make a wording change to the title of the record.

The request was that they would like to be able to edit the text of the docket Notice of Docket change entry in the future.
