### ISSUE TITLE
Search Usability - Revisit

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7155]
As a development team, so that we can provide an optimal user experience for users, we need to revisit the the usability of the Search functionality.

* On 5/20/20 discussed that there are possibly some usability issues with navigating back to search results after performing a search. Currently, the page retains the search criteria, but not the search results. May also want to explore other usability issues and/or perform usability testing. 
* From 12/14/2020 Usability Testing:  Highlight matching search terms in results; user should be able to clearly identify why a result is matching their search terms

**Comment by klohman** [comment]
## Recommendations 
* Add description / definition for Order and Opinion search to give public users context 
* Include capability outside of this global search feature; allow users to filter and search within a docket record 
* Allow users to search for exact matches only; consider that most users expect to use quotations marks for this 
* Include “Bench Opinions” in Opinion Type dropdown 
* Allow users to search without a keyword for Orders and Opinion. Consider that the use case for this may be different than for a keyword search: Example: User wants to find all Orders issued by a specific judge. 
* Include messaging to differentiate exact matches from partial matches 
* Add support for Boolean operators, and include instructional text in UI 
* Add a visual indicator of matching keywords; users mentioned highlighting the matching keywords in the result set 
* Display keyword matches in document contents to inform user of where the keyword matches were found; consider displaying excerpts from the contents like the legacy system 
* Allow fuzzy search; consider making this optional and user initiated; research how this should behave with Boolean operators

**Comment by klohman** [comment]
## Summary of Usability Findings (December 2020)

**What are users searching for?**
Searching for a specific case 
If they have the docket number, they’ll use that 
If they don’t have the docket number, they’ll lookup by taxpayer name 
For businesses or partnerships, would search by address, case name, or party associated with the case 
“If i don’t have that info, I’m going to use West Law or LexisNexis” 

**Searching for Research Purposes**
General public may search for Orders and Opinions here because they lack access to paid databases like WestLaw, etc. 
(Clerks, practitioners) generally will not use USTC document search for their research 
(Clerks, practitioners) may use USTC document search to find a specific order (for example, one they worked on) 

**Search for case by petitioner**
Users use different formats to search for a case by petitioner name and expect the results to match 
First Name Last Name
Last Name, First Name 

**Using Quotes**
Users expect putting quotations around their search terms to search that exact terminology and narrow the result set 
Users use quotes in their terms only after searching without and receiving an unexpectedly large result set 


**Order Search**
Most searches are for keyword only and then judge 
Use case to search for a specific order on a specific case
Recommendation: include capability outside of this global search feature; allow users to filter and search within a docket record 


**Opinions**
Users expect Opinion type dropdown to include “Bench Opinions” 
User expected Opinion types to be sorted by precedential effect with TC Opinion first
User interest was expressed in searching without a keyword; for example, search for all Summary Opinions for Judge Buch 


**Navigating search results** 
In large result sets, user uses the “Find” feature in the browser to try to locate relevant search results 
User don’t like they have to “start over” to view search results when they navigate away from the search screen; prefer that results remain displayed 


**Messaging - Search Results**
Users expect messaging/instructions to help them refine their search when a large number of results come back
Current messaging for high number of search results is contradictory and misleading when only presenting partial matches; “Says there’s a high number of matches, but none are an exact match”
Users expect messaging informing them if they have exact matches or partial matches and a way to identify each

**Search speed**
Docket number search is fast; users like that the case comes back quickly 
Petitioner name search was a little “pokey” 


**Identifying keyword matches**
Users had a hard time identifying where their keywords existed in the search results;
Users not clear why some of the results are relevant; for opinion search, there is no way to visually prove the results are accurate (Opinion Type is the only information displayed and does not contain the keyword) 
Users expect to be able to easily identify the matches visually; would like to see keywords highlighted  
Being able to see where a keyword matches in context would be helpful; users would like excerpts from document content matches 

**Advanced search - Booleans**
Users want to be able to enter multiple keywords and connectors to build out their search: wants to enter “keyword + keyword + keyword) 
All users expected more “advanced search” functionality 
Wants Boolean search capabilities; all of the participants in our sample understood how to use Booleans without instruction 
Want to be able to exclude some keywords 

**Advanced search - Petitioner**
Users want more options to narrow petitioner name search by location; state is good but  city or county would be helpful 

**Partial matches**
User complained that it feels like they are getting either no results or too many 
Displaying only partial matches with no messaging confuses users; they expect to find what they were looking for in the results but are seeing only partial matches
Users were able to understand why they were seeing specific matches after looking more closely, but it was not immediately apparent that these were only partial matches 

**Unexpected search behavior**
Not clear to most users how matches are sorted 
User does not expect a google-like search for case search; expects a string search instead of free text

**Fuzzy search**
Would like to see similar names in results; finds it helpful to be able to search for shortened versions
