### ISSUE TITLE
Ban an IP address

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#728]
Acceptance Criteria:

As a sysadmin, so that I can keep bad actors from impacting the performance of the site, I need to quickly ban IP addresses from making requests to the API Gateway. 

Notes:

- Should be a bit of Terraform or aws CLI to be able to ban (or unban) an IP address with one command. 
- Possibly make it easy automate banning an IP in case as we add more triggers to catch suspicious or malicious activity.
- Need to be able to quickly identify an IP address in Kibana,
- IP Address is easily visible in Kibana logs by `request.headers.x-forwarded-for`

References:
https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-resource-policy-access/

**Comment by adunkman** [comment]
My first thought is to implement an example rule that can be manually tweaked in the console without a deploy, since this rule will likely be need to be used in an urgent situation (an IP address wreaking havoc). 

Looks like we can use a few sets of IPs for these examples, as they are unused and reserved for use in documentation:

> The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2), and 203.0.113.0/24 (TEST-NET-3) are provided for use in documentation.

**Comment by adunkman** [comment]
A few questions for you when you have a moment @mmarcotte —

- For "Need to be able to quickly identify an IP address in Kibana" — **is that satisfied by the current implementation, examining `request.headers.x-forwarded-for` or would another way be better?**
- On "Possibly make it easy automate banning an IP in case as we add more triggers to catch suspicious or malicious activity." — we will have automatic banning based on traffic from #735, and could add additional WAF rules to ban specific behaviors. AWS has an [extensive list of managed rulesets](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html).
  - **If we want to use any of these, please let me know.** Otherwise, I’ll let this comment serve as documentation for how to do it in the future, and will consider this item completed.

And an implementation question —

- I’m looking at a command which will be able to be executed without a deploy, and ignoring changes to this resource from Terraform. This would mean that we wouldn’t have a list of banned IP addresses in source control.
  - I think that’s desirable, but it might not be. **Is that acceptable?**
  - The application standard here would be to write a shell script. I’m imagining something which takes an environment and an IP address — along the lines of `./ban-ip-address.sh dev 192.0.2.5`. **Does that jive with you?**

**Comment by adunkman** [comment]
- See if updated AWS provider fixes the terraform issue documented in #840.
- Merging #711 unblocks making a PR for this.
