### ISSUE TITLE
BUG: Case Messages not displaying (or displaying after a delay) after deleting a draft document -- Work w/ #6432

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7297]
We have a spike for tuning Elastic Search (#6432). Deal with them together. 

**Describe the Bug**
After deleting a draft document attached to a message, no messages are displaying in the Case Messages > In Progress. This includes the message that had the draft document attached as well as any other messages. After a few moments, when I click back to the Case Messages, the messages display again. 

Note: This is a reoccurring bug. I believe Matt worked on this before but I could not locate a Trello card. It may have been fixed as part of a story. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to case 
2. Create a message with a draft document attached 
3. Go to Drafts 
4. Delete the draft document that is attached to the message 
5. Go to Case Messages In Progress tab

**Expected Behavior**
All case messages that are not completed should display in the Case Messages In Progress tab until they are completed. 5 seconds is acceptable timeframe. 

**Actual Behavior**
All messages disappeared. If you wait a few minutes and navigate away and then back, they will display again after a few minutes. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac os 
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
unknown 

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering)

**Comment by kkoskelin** [comment]
Steps to recreate:

[in tab 1]
Log in as docket clerk.
Search for 104-19 and arrive at /case-detail/104-19
In “Create” menu, choose “Order or Notice”.
In Modal, select “Order” in drop-down and give your order a name like “Order Onion Rings”.
Click “Continue”

You are now launched into [tab 2] which has a url of ‘/case-detail/104-19/create-order?documentTitle=Order%20Onion%20Rings&documentType=Order&eventCode=O’
[continuing in tab 2]
Type “Onion rings are delicious” into text area and click “Save”
- You will arrive at a route like /case-detail/104-19/edit-order/d44f8c9b-0232-4d89-abec-da75c4e4722d/sign
Click “Skip Signature”
- You will arrive at a route like /case-detail/104-19/draft-documents?docketEntryId=d44f8c9b-0232-4d89-abec-da75c4e4722d
Click “Create” menu and select “Message”.
“Create Message” modal will open. Select ADC, Test ADC as section and recipient. Enter a subject and message.  Select your draft document “Order Onion Rings”.  Click “Send” button.
- Note: your route remains UNCHANGED.

[go back to tab 1]
Click the “Drafts” tab and you will find your document is not there.
Reload the page.
Click “Drafts” again and you will see it there.
- Your route is /case-detail/104-19
Select your draft document if it is not already shown.  Click the “Delete” button above the iframe.
In the modal, click “Yes, Delete”
Your draft should no longer be found in the Drafts view (which should still be your current view)
- Your route remains unchanged.
Click “Case Messages” tab.
The “In Progress” messages are empty.
Reload the page and again go to “Case Messages”.  They are populated.

What’s going on???
It depends on the execution context of the deletion of the draft.  
Suppose your route says ‘/case-detail/104-19’ AND you are on the Drafts tab of the case detail.
Then you click “Delete” on a draft, and clicking “Yes, Delete” fires the `archiveDraftDocumentSequence` whose last action is `navigateToCaseDetailAction` which does this:
await router.route(`/case-detail/${docketNumber}`);

Normally, hitting this route will reload the entire case detail, its messages, etc (see `gotoCaseDetailSequence` which is called when that route is triggered)
HOWEVER… you are ALREADY AT THIS ROUTE.  The window’s location history has not changed. No route is triggered.  The `archiveDraftDocumentSequence` updates the state.caseDetail within `setCaseAction` but the messages are never refreshed; they reside on `state.caseDetail.messages`.  Messages are currently stored nested within case detail, though they are fetched separately, and if you fetch the case detail and case messages out of order OR fetch only the detail without messages, those messages will be empty.

Note that if you redo these steps, but where it says [go back to tab 1] you instead carry out the steps in tab 2 (where your route is actually /case-detail/104-19/draft-documents — by the time you hit the deletion sequence and a request to navigateToCaseDetailAction, this is a request to change the location history (from /case-detail/104-19/draft-documents to /case-detail/104-19) then the entire `gotoCaseDetailSequence` is executed and messages will be refreshed, along with the case detail.

How could this be fixed???
- Don’t open new tabs (the result being two instances of the app with different state)
- Add a call to `getMessagesForCaseAction` as second-to-last step in `archiveDraftDocumentSequence` to ensure it is called even if no new route is triggered
    - Note that if the new route is triggered, we will have requested case detail and messages each TWICE, the second times occurring upon `navigateToCaseDetailAction` which is wasteful
- Store messages somewhere in state which is not nested & dependent upon `state.caseDetail` which gets overwritten by other get/set actions
- Fetch both messages during the retrieval of case details so that whenever we receive an updated case detail, it already contains a `messages` attribute and the complete set of data is then stored in `state.caseDetail` (and `state.caseDetail.messages`)
- Re-engineer our router to
    -  be able to “force” routes to fire even if we’re “already there” (bad idea?)
    - Be able to specify desired primaryTab differently that doesn’t affect route (query string??)

**Comment by kkoskelin** [comment]
ustaxcourt/ef-cms-flexion#6606

**Comment by klohman** [comment]
@kkoskelin 

Still seeing this happening following these steps: 

* Click Create and PDF Upload 
* Upload PDF and save
* Create Message with uploaded PDF attached 
* Send Message 
* Delete uploaded PDF from Drafts 
* Click Case Messages
