### ISSUE TITLE
BUG: Some CSV fields not accounted for in `bulkImportPractitionerUsers.js`

### ISSUE THREAD

**Issue by mrinsin** [ustaxcourt/ef-cms#7393]
**Describe the Bug**
A csv with practitioner data contains columns for `IRS_EMPLOYEE` and `DOJ_EMPLOYEE`. The script to bulk import practitioners uses these columns in the logic to set the practitioners employer. Currently, those fields are not being read, which causes the employer fields to be populated incorrectly.
There are also fields in the `csvColumns` array of the script that are not consumed, those values can be removed.
Finally, `IMPORTING_PRACTITIONER_USERS.md` is not up to date and should be updated.

**Business Impact/Reason for Severity**
Will result in wrong employers associated with imported practitioners

**In which environment did you see this bug?**
Noticed by Mark while prepping for migration

**Who were you logged in as?**
N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Mark was reviewing the documentation to set up data for migration

**To Reproduce**
1.Attempt to bulk import practitioner data that looks like the example in `IMPORTING_PRACTITIONER_USERS.md`

**Expected Behavior**
Practitioners should be successfully imported with correctly populated fields

**Acceptance Criteria**

**Actual Behavior**
The employer field of bulk imported practitioners is incorrectly populates

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Employer field has not been accounted for in the csvColumns array of the script

PR - https://github.com/flexion/ef-cms/pull/6870/files

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mmarcotte** [comment]
One issue we found is that the API would not let you create a practitioner that had a status that was != 'Active'

Error was
> Practitioner users must have either private or IRS practitioner role'

Fix might be:
Adding `ROLES.inactivePractitioner,` to the list of acceptable roles in `shared/src/persistence/dynamo/users/createPractitionerUser.js`

The script also attempted to use the wrong API URL due to the changes from blue/green. So I added:
`const apiUrl = services[`gateway_api_${process.env.DEPLOYING_COLOR}`];`

The API also complained about:
* Address1 being required (so I think we had to fallback to Address2)
* Zip code not being set (so we fell back to 00000
* originalBarState being undefined, so we did a fallback to 'N/A'

Finally noticed that the admissionsDate wasn't getting passed correctly, and so changed it to key off of `    record.admissionsDate` instead of `record.unformattedAdmissionsDate,`

Let me know if I can help!
