### ISSUE TITLE
Performance Tuning: Search Results (casePublicSearch, caseAdvancedSearch, advancedDocumentSearch & getPractitionersByName)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7401]
As the Court, in order to make sure elasticsearch is not improperly limiting what returns for casePublicSearch,  caseAdvancedSearch,  advancedDocumentSearch, or getPractitionersByName, we need to reconsider how search results are being returned.
 
## Acceptance Criteria:
* For casePublicSearch,  caseAdvancedSearch,  advancedDocumentSearch & getPractitionersByName that return more than 200 results, only return the first 200 and instruct user to add additional search criteria to narrow search. [See note below]
* Make sure changes is applied for both public search and internal advanced search.

## Note: 
* Current system: 
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/7c9481cc-91cd-48f0-8b6d-e2338f3c5029)

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by kkoskelin** [comment]
From @klohman 
![image](https://user-images.githubusercontent.com/2445917/97474451-1d848400-191a-11eb-9870-8d6907161617.png)

**Comment by JessicaMarine** [comment]
@klohman @kkoskelin Design looks fine to me!

**Comment by kkoskelin** [comment]
**One note:** individuals using these searches may see confusing results.  At the present time, searching for the word "order" on the public order search results only showing 199 (and not 200):
![Screen Shot 2020-10-29 at 1 04 00 PM](https://user-images.githubusercontent.com/2445917/97613910-458de900-19e7-11eb-83f6-b57117b1ce83.png)

In order to produce the "maximum search results" warning, the client depends upon the number of records returned to be exactly equal to the MAX_SEARCH_RESULTS value (currently 200) which is also used by ElasticSearch.

However, the interactor for public order searches (and probably other search-related interactors) performs a search and filters afterward for sealed cases.  This means that the search *actually* returned its maximum of 200 cases, and then removed one that was sealed before returning only 199 cases as a response.  The result: it appears as though there were *only* 199 matches, and that was it -- when in truth there was probably a whole lot more.

Example code from `shared/src/business/useCases/public/orderPublicSearchInteractor.js`:
```
const results = await applicationContext
    .getPersistenceGateway()
    .advancedDocumentSearch({
      applicationContext,
      documentEventCodes: ORDER_EVENT_CODES,
      judgeType: 'signedJudgeName',
      ...rawSearch,
    });

  const filteredResults = results.filter(item => !item.isSealed);
```

**Comment by klohman** [comment]
@JessicaMarine 

Passes UX review and ready for QA with 2 comments: 
 - 1) The way search results are filtered (see Kris's comment above) 
- 2) We do not have a bulk load of practitioners on Flexion prod so I could not test the max search results in this environment.
