### ISSUE TITLE
BUG: Save button not working on Edit Correspondence (from message detail)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7478]
**Describe the Bug**
On the Edit Correspondence screen, the save button is not working. I believe this is because the user does not have permissions to edit correspondence documents but can still access this screen via the Message Detail. Only docket clerk, petitions clerk and clerk of the court roles should be able to view the "Edit" link for correspondence documents. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
judge buch

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to message (with correspondence file attached) 
2. Click edit link on correspondence file 
3. update description 
4. click save

**Expected Behavior**
User without edit permissions should not be able to access this screen. 

**Actual Behavior**
Users can access the edit screen for correspondence documents from the Message Detail screen and it is not working properly.

**Screenshots**
https://drive.google.com/file/d/1qjLKYFy9MVXVW9vDYXRgvoR7DWZepdR2/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Helper was not checking for edit correspondence permissions before displaying button
PR - ustaxcourt/ef-cms-flexion#7195

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mariahkannenberg** [comment]
Original Correspondence Story: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/4658

**Comment by mariahkannenberg** [comment]
CONTENT FROM ORIGINAL BUG


**Describe the Bug**
On the Edit Correspondence screen, the save button is not working. I believe this is because the user does not have permissions to edit correspondence documents but can still access this screen via the Message Detail. Only docket clerk, petitions clerk and clerk of the court roles should be able to view the "Edit" link for correspondence documents. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
judge buch

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to message (with correspondence file attached) 
2. Click edit link on correspondence file 
3. update description 
4. click save

**Expected Behavior**
User without edit permissions should not be able to access this screen. 

**Actual Behavior**
Users can access the edit screen for correspondence documents from the Message Detail screen and it is not working properly.

**Screenshots**
If applicable, add screenshots to help explain your problem.
https://drive.google.com/file/d/1qjLKYFy9MVXVW9vDYXRgvoR7DWZepdR2/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Cause of Bug, If Known**


**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).
