### ISSUE TITLE
(NEEDED in 53.1) BUG: Allow ready for trial cases to be migrated without a trial city -- Needs to be tested in Court's environments

### ISSUE THREAD

**Issue by ericsorenson** [ustaxcourt/ef-cms#7494]
**Describe the Bug**

When a ready for trial case is migrated without a trial city, a JavaScript error is thrown.

**Business Impact/Reason for Severity**

All legacy cases must be migrated.

**In which environment did you see this bug?**

All environments.

**Who were you logged in as?**

Migration

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Migrating cases.

**To Reproduce**

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
The issue was due to the migration script calling `createCaseTrialSortMappingRecords` when a case was in a ready for trial status, however that method depends on the `preferredTrialCity` being set. Some migrated cases will not have that, so we're now checking for that field before running `createCaseTrialSortMappingRecords`, and instead dropping a note in the console so a manual audit / intervention can be done after the case is migrated.

Testing has not turned up any unexpected bugs when migrating a case in this way, and I was still able to manually set the case for trial without issues - however a situation where `createCaseTrialSortMappingRecords` is run will throw an error until the `preferredTrialCity` is set. The case will also not appear in eligible for trial lists without those sort mappings.

This fix has been added to Sprint 53 PR to get it to the Court's env sooner.
