### ISSUE TITLE
Concurrent Searches: Case Search

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#7577]
As a user, so that I can have a great experience searching cases when many users are searching, I want the system to be optimized.

Pre-conditions:
* Documents are imported into Flexion's prod env.

Acceptance criteria:
 - When concurrent searches of 1000 users are performed on the full data set:
   - searches don't time out (identify queries)
   - all functionality that utilized ES aren't broken (identify them all)
- If search go beyond the performance threshold, user receives a message specific to the scenario and directing them to next steps.

Note:
* Is this still needed? 4/21/21 MK
* How do we mimic #of searches when testing? Gatling can be used; users can also search
* There are 3.7 M documents - how many are orders and opinions?
* Import the Court's order and opinions into Flexion's env.
* Order of operations - prioritize all stories, identify the queries, test them in the Court's env to confirm what's not working to confirm we're optimizing correctly.
* (it appears the endpoint returns improper CORS headers when data exceeds a certain volume, causing the frontend to consider the request unauthorized).

Tasks:

 - [ ] Identify what's not working in Court's env (Mike)
 - [ ] Identify possible search combinations
 - [ ] Enlist help of AWS for support (Mike)
 - [ ] Import Court orders and opinions into Flexion's prod env.
 - [ ] Make a PR w/#7343 to see if it fixes the logout issue. (Story ustaxcourt/ef-cms#6491)

**Comment by mariahkannenberg** [comment]
Elasticsearch is behaving inefficiently for advanced document search, we need to improve the queries and the mapping to reduce CPU and storage demand on the Elasticsearch cluster, and there seems to be a relation between the volume of data returned and users being logged out of the system when running searches (due to improper CORS headers being returned, strangely — @mmarcotte can help reproduce).

**Comment by mariahkannenberg** [comment]
Possible tasks:
- Analyze and optimize queries 
  - Identify all of the searches performed on the `efcms-user-case` index
  - come up with a list of ES queries for each search
  - get current analysis of “analyze and explain queries” for test queries, look at the [profile API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-profile.html)
  - look for misuse of queries, “pk matching case|” and propose matching by entityName keyword (or keyword constant)
- Analyze and optimize mappings 
  - Use the elasticsearch [term analyzer endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-analyze.html) to discover how fields are tokenized
  - Any field which is looked up by exact value (uuid, anything from a select box in the UI) should be a `keyword` field rather than text.
  - Look for opportunities to avoid indexing fields — data can be stored in elasticsearch but not indexed if it will not be searched on.
  - Look for opportunities to use [numeric](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html) fields.
- Understand the impact of nested fields on performance — due to mimicking dynamodb formats, we have many deeply nested fields.
- Ensure all tests still pass as well as expected functionality
- Compare updated report of “analyze and explain queries” for test queries

Notes: 
- Changes to field mappings requires elasticsearch to be reindexed.

**Comment by cholly75** [comment]
@mariahkannenberg Is this better suited as a DevEx task as it's refactoring search queries?

**Comment by cholly75** [comment]
NFA - will address as needed, current throttling controls are in place for high search concurrency.
