### ISSUE TITLE
Opinion Search: Locate document by exact keyword/phase

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7581]
As a internal court user so that I find the opinion I'm looking for, I need searches for exact matches to return expected results.

## Pre-Conditions
- Turn on opinion search in MIG

## Acceptance Criteria
- Court User is able to indicate if they want an exact match
- Court User is able to search for an exact match on a single keyword
- Court User is able to search for an exact match on a phrase
- When exact match is indicated by user, the result set includes only matches that include the exact keyword/phrase
- Court User (internal or external) should see an indication that my search request is “processing” after starting a search
- We define exact matches as exact words in the exact order
- Ensure that search is not case sensitive
- If there are no matches, inform the user
- Review test cases as a team and ensure our test scenarios are good and finalize

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by cholly75** [comment]
## Test cases 

expected results 
results include all keywords in exact order 
results do not include documents with keywords not in exact order 
exact match found in document title and contents
exact match found in document title but not document contents 
exact match found in document contents but not document title 
exact matches with lowercase/uppercase characters (should not be case sensitive) 

Data 
Opinion 1 
“welcome to flavortown” in document contents + title 

Opinion 2
“welcome to flavortown” in document contents 

Opinion 3 
“welcome to flavortown” in document title  

Opinion 4 
“welcome to something” and “flavortown” in document title  

Opinion 5 
“welcome from flavortown” in document contents + title 

Opinion 6 
“welcome to flavor-town” in document contents + title

Opinion 7
“welcome to flavortown.” in document contents 

1. Search for “welcome to flavortown” 
expected results 
- []  Opinion 1 returns in results 
- []  Opinion 2 returns in results 
- []  Opinion 3 returns in results 
- []  Opinion 7 returns in results 
- []  Opinion 4, 5, 6 do not return in results

2. Search for “welcome from flavortown” 
expected results 
- []  Opinion 5 returns in results 
- [] Opinion 1, 2, 3, 4, 6 do not return in results 

3. Search for “welcome to flavor-town” 
expected results
- []  Opinion 6 returns in results 
- [] Opinion 1, 2, 3, 4, 5 do not return in results 

4. Search for “Welcome to Flavortown” 
expected results
- []  Opinion 1 returns in results 
- []  Opinion 2 returns in results 
- []  Opinion 3 returns in results 
- []  Opinion 7 returns in results 
- []  Opinion 4, 5, 6 do not return in results

5. Search for “welcomes to flavortown”
No opinions return in results 


**Realistic data examples for larger testing** 
- some of these may end up moving to the special characters story
* confidential informant
* TC memo 2020-1
* t.c. memo. 2020-1
* 156 T.C. No. 11
* 156 TC No. 11.
* innocent spouse 
* innocent spouses
* estate of jackson
* Estate of Michael Jackson 
* motion to dismiss 
* parties’ joint motion for continuance
* parties’ joint motion for 

(edited by kkoskelin replacing "Order" with "Opinion" in above scenarios)

**Comment by kkoskelin** [comment]
I created all seven opinion documents as PDFs just like the attached.
[opinion-1.pdf](https://github.com/flexion/ef-cms/files/7094690/opinion-1.pdf)

Then I uploaded them with the specified titles in the above scenarios and added them as TC Opinions.
![Screen Shot 2021-09-01 at 5 06 26 PM](https://user-images.githubusercontent.com/2445917/131753125-20af94bb-827b-4ba2-9327-f88bbe44ffd9.png)

I performed each of the suggested searches and got the results you see in these screenshots (below).
NOTE: I made local changes (not committed to repository) in the table to reveal the complete document title (instead of just document type e.g. "T.C. Opinion") so we could see which ones were being returned in the searches.
![Screen Shot 2021-09-01 at 5 17 54 PM](https://user-images.githubusercontent.com/2445917/131753159-0f713579-9d39-4f7a-950c-464a3739d315.png)
![Screen Shot 2021-09-01 at 5 18 24 PM](https://user-images.githubusercontent.com/2445917/131753161-a9a74f9c-f3cb-4b58-87ab-794d726db87d.png)
![Screen Shot 2021-09-01 at 5 18 39 PM](https://user-images.githubusercontent.com/2445917/131753162-b0db159a-e7e7-4031-bcc0-7fe27ce440a9.png)
![Screen Shot 2021-09-01 at 5 19 01 PM](https://user-images.githubusercontent.com/2445917/131753163-87e374c7-7589-443a-b18b-c8daf57cb13c.png)
![Screen Shot 2021-09-01 at 5 19 23 PM](https://user-images.githubusercontent.com/2445917/131753166-5825a19d-633c-4d5d-9e81-21c9e0b04625.png)

**Comment by kkoskelin** [comment]
https://github.com/flexion/ef-cms/pull/8897

**Comment by mariahkannenberg** [comment]
Blocked - Currently can't make it to MIG. @mmarcotte

**Comment by mariahkannenberg** [comment]
Getting code to MIG today.
