### ISSUE TITLE
BUG: Mobile - Practitioner without cases updates address - NaN% in progress bar

### ISSUE THREAD

**Issue by rachaelparris** [ustaxcourt/ef-cms#7733]
**Describe the Bug**
On mobile - Private practitioner without any cases updates address and is taken back to dashboard. NaN% displays in progress bar, and it does not disappear.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
migration

**Who were you logged in as?**
private practitioner with no cases (local: try `privatePractitioner3@example.com`)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
quarterly testing

**To Reproduce**
1. Login as a private practitioner with no cases
2. Go to My Account
3. Update address
4. Progress bar displays

**Expected Behavior**
Progress bar should not display if practitioner has no cases

**Actual Behavior**
Progress bar displays with NaN%

**Screenshots**
![IMG_1301](https://user-images.githubusercontent.com/43251054/109716809-20a6af80-7b5a-11eb-8588-e360d4e02362.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
Analysis:  This seems to be happening when not all of the websocket messages created by the server are received & processed by the client.  I see a websocket connection that just stalls and says "pending" in chrome. Also seen this in Firefox.  It is intermittent and unclear how to always get it to happen.

![Screen Shot 2021-05-11 at 4 45 11 PM](https://user-images.githubusercontent.com/2445917/117889031-827d4700-b278-11eb-95fb-c872962ac53c.png)

**Comment by kkoskelin** [comment]
I've only been able to replicate this error perhaps once in every 20-25 attempts.  It does not really appear to have anything to do with mobile mode, fwiw.  Some debug work is now on branch `7913-progress-nan`.
I'm stuck.  Leaving this for a time when others with socket experience can pitch in.

**Comment by matthopson** [comment]
Some findings on this:

1) The generateChangeOfAddress is sending out a progress message at the start before going through cases. This is fine, except we don't verify that there are actually cases for the given privatePractitioner user. Which means we initially show the progress UI when we don't need to. Since we fetch all docket numbers associated with the privatePractioner, we can just conditionally send that progress message if the array is greater than 0. This is further exacerbated by a race condition (mentioned below).

2) Every time we open a socket, we check if there is one in existence and close it. Since this happens when the user is routed to the dashboard after the `user_contact_initial_update_complete` event is fired, there is a potential race condition where the socket could be closed and reopened when the subsequent `user_contact_full_update_complete` which shows the final Alert Success banner. Any events emitted by the server during this short window can cause the UI to be in an incomplete state. This condition is more likely to be present when updating the firm name on a privatePractitioner with no cases because everything happens quickly and those subsequent messages are more likely to be fired immediately after the UI starts the process of routing the app, creating a socket connection - but not before closing the old one - and there lies the problem. The socket is closed momentarily while those messages come through and the UI is borked.

**Comment by kkoskelin** [comment]
While we are hoping that the occurrence of this bug is far more rare, we are not yet convinced that it is gone for good.

The real solution here is likely to be a more robust messaging solution in which messages get queued, and remain in the queue unless confirmed received by a socket recipient.

https://github.com/ustaxcourt/ef-cms/pull/1211

**Comment by JessicaMarine** [comment]
When we deployed the bug fix for ustaxcourt/ef-cms#7733 to the IRS test environment, it is now preventing all IRS attorneys from logging in. We definitely need to figure out what's happening and how to correct it before we can take that to `prod`.  Perhaps @mmarcotte can explain the websocket issue the IRS has.

**Comment by mariahkannenberg** [comment]
Blocked - waiting to hear back from IRS. 

Mike heard back from IRS. The solution he put in place allowed the IRS to log in. No further work is needed on this bug. @kkoskelin I'm unblocking and moving back to "Merged to Staging"

___background for documentation purposes______
Flexion can create a solution(s) that would help detect and prevent potential bugs caused by Websockets from impacting IRS users. Since we don’t have access to IRS environments, we would request your help with troubleshooting or understanding the root cause, so that we can create the appropriate solution. Insead of doing this work as part of ustaxcourt/ef-cms#7733, we’d create a spike to investigate and understand the root cause, and then create a story to implement the solution. Since Mike has put a solution in place which allows the IRS to log in, I think we can move ustaxcourt/ef-cms#7733 through to “Merged to Staging.” Please confirm if that’s not the case.
 
As requested, here is an inventory of the areas in the application where we use websockets.
Websocket connections require the web client to create a websocket, but also for the server to create its own connection -- like having two parties is necessary to make a telephone call. You can identify the places in our code where messages are sent via websockets to the client by looking for calls to sendNotificationToUser.

The current list of calls are isolated to the following processes:

- updatePractitionerUserInteractor [ADD_EDIT_PRACTITIONER_USER,EMAIL_MANAGEMENT] = admin, admissionsclerk, irsPractitioner, petitioner, privatePractitioner,
- batchDownloadTrialSessionInteractor [BATCH_DOWNLOAD_TRIAL_SESSION] = judge, chambers
- setNoticesForCalendaredTrialSessionInteractor [TRIAL_SESSIONS] = all internal users 
- updateUserContactInformationInteractor [UPDATE_CONTACT_INFO or a user edits their own contact information] = irsPractitioner, petitioner, privatePractitioner,
- verifyUserpendingEmailInteractor [EMAIL_MANAGEMENT] = admissionsclerk, irsPractitioner, petitioner, privatePractitioner
