### ISSUE TITLE
Logged out: Order and Opinion Search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7736]
As a user, so that I may search for orders and opinions in DAWSON, I do not want to get logged out when I perform my search.

## Acceptance Criteria
* User does not get logged out when searching for orders or opinions
* User sees a more descriptive error when requests being made to any endpoints using the efcms-docket-entry index are impacted by service latency or unavailability without being logged out.

## Notes
(it appears the endpoint returns improper CORS headers when data exceeds a certain volume, causing the frontend to consider the request unauthorized).
Issue where worked on previously - https://github.com/flexion/ef-cms/issues/6685

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by kkoskelin** [comment]
A report for both public and internal that shows the chain of calls from the persistence methods back to the originating actions:
https://docs.google.com/spreadsheets/d/1mgpHlGcMqpdcwrTKE0bGbZ6ZMqX-gHV4-kheCNU4S6U/edit?usp=sharing
Notes at the bottom of each sheet that explains which user action executes them.

**Comment by mariahkannenberg** [comment]
7374 - Needs more information- need more specific AC, so we can have a targeted solution. We want to specifically address the ways users are getting logged out.

**Comment by matthopson** [comment]
Just adding some notes after chatting with @mmarcotte a little about this.

Unsure if the best thing to do is shelve this until we can see it actually happening when enabling search for internal users.

It's likely that, since other 500 errors are being caught and handled without logging the user out, the issue is hitting a fall-through case in the `ErrorFactory` - which broadly assumes the user is logged out.We may be able to try and detect if the user is actually logged in and handle those differently - and THEN handle the unauthed case if that fails.

**Comment by kkoskelin** [comment]
@matthopson I think you can probably wrap calls to the search client within a try/catch and then throw an error specific to ES (and distinct from auth issues).
If an error is caught in an action, you can inspect the error's code, message, etc and decide whether to passively handle what might be a simple error with some messaging OR re-throw it and let the cerebral engine decide.

**Comment by mariahkannenberg** [comment]
Hold on this one - may be handled in other upcoming stories, or may not be a search problem at all.  Search needs to be turned on first to verify/see the failure.

**Comment by mariahkannenberg** [comment]
We want to see it fail. Server logs.
If we can't break it on our own, wait until it breaks for a user.

**Comment by JessicaMarine** [comment]
@matthopson This was happening previously when Mike would perform Gatling load testing against an environment while I was simultaneously performing manual searches.  Because we think this issue was resolved by other work done (e.g., not returning entire contents), if we can't reproduce this issue by concurrent load and manual testing, I agree we can wait and see if it fails in the future.

**Comment by matthopson** [comment]
@JessicaMarine I was able to run load tests against order search to the point of it failing while making simultaneous requests manually, and would get back a timeout error with a 504 response code every time. This issue should be addressed with ustaxcourt/ef-cms#7579, where a 504 response code displays a message to the user, rather than redirecting to the login page.

**Comment by mariahkannenberg** [comment]
Load testing had desired results. Revisit if it comes up in the wild!
