### ISSUE TITLE
BUG: Morrison's 3/22 session is randomly showing up on other judge's filtered list of trial sessions

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7768]
**Describe the Bug**
Judge Carluzzo reported that Judge Morrison's 3/22/21 Chicago Trial session is showing on his list of trial sessions when the open trial sessions were filtered for Carluzzo.  I was able to replicate in prod initially (see screenshot below), but cannot replicate for Carluzzo now.  However, Morrison's 3/22 session is randomly showing up on other judge's filtered list of trial sessions.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod; not reproduced on Court's mig

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to Trial Session tab
2. Filter the sessions by various judges
3. Note how Judge Morrison's 3/22 session is randomly showing up on other judge's filtered list of trial sessions

**Expected Behavior**
* Only the filtered judge's sessions should display.

**Actual Behavior**
Judge Morrison's 3/22 session is randomly showing up on other judge's filtered list of trial sessions

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/3f1739f8-08a7-43aa-b669-4723c8e720a6)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/ab01ee63-e5bd-4a50-a4ea-2292339a2b1f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by matthopson** [comment]
## The Problem
The root of this issue is, when updating a note on a hearing, the persistence method is adding a `gsi1pk: trial-session-catalog` - and should not be. This is allowing the hearing to be duplicated in the trial session list. In cases where a given duplicate session (it's not _actually_ a duplicate - it's a separate distinct case hearing record that is coming back because of that gs1ipk) falls on the same trial week as another session for a given filtered judge, that record hangs around - which is also odd, but I believe it's due to how the item is being indexed in the React template. I suspect React isn't being told, based on its key, to REMOVE that element from the UI so it hangs around.

## Steps to Reproduce
*Note, this only works if the later steps that create this condition haven't been met for the given trial sessions - it would also work to just create two trial sessions in the same week with two different judges.

- Find two trial sessions that fall on the same week with two different judges (Judge A and Judge B).
- Go to a case and add trial session from Judge A
- View trial sessions, filter by Judge A and note that there are no unintended duplicates
- Filter by Judge B and note that no records from Judge A show
- Taking it a step further, you could look in dynamo at the mapping record generated by adding the case to the hearing and note there is NO gsi1pk for this record.
- Go back to the case and update the note on the hearing and save
- Go to trial sessions and repeat steps from above, and note there will be a duplicate when filtering by Judge A
- Filter by Judge B and note that the session from Judge A is now present.
- Looking at that same mapping record in dynamo will now show a gsi1pk with `trial-session-catalog` (and manually deleting this property will revert the condition back to before updating the note on the trial session - no duplicates, and no mis-filtered items).

## The Fix
The fix here is to update the persistence method to prevent it from adding that `gsi1pk` and create a migration that updates any case hearing record (`pk: case|${docketNumber`, `sk: hearing|${trialSessionId}`) with a gsi1pk of `trial-session-catalog` to no longer have that gsi1pk.

**Comment by JessicaMarine** [comment]
@matthopson  I don't see Judge Morrison's 3/22 session randomly anymore, but I am noticing something else -- in the Judge dropdown for "Closed" and "All" it now lists all the active and legacy judges instead of just the active judges.  It's not a huge deal, but the legacy judges don't really need to be in those dropdowns.
