### ISSUE TITLE
SPIKE: Judge the quality of the OCR'd data in the system

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7922]
As an engineering team, so that we may understand the quality of the OCR'd data, we need to reviewed contents of production PDFs.

## Acceptance Criteria
* We have an better understanding of quality of the OCR'd data

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by rachaelparris** [comment]
Total count of _all_ orders and opinions currently in Dawson mig: 1,566,007

**Comment by ericsorenson** [comment]
When trying to build a query to find out how many documents were OCRed into a single term, we were able to find other issues with OCRed content. While the some documents were not entirely combined into one word, entire phrases were combined. OCRed postal stamps also added invalid text to the index. We discovered many variations of invalid content. The team would need to manually look at each of the 1.6 million documents individually.

Next Steps: Share progress with the team at standup!

**Comment by codyseibert** [comment]
Things we learned:

From taking 2,500 random order / opinion docket entries and looking at their document contents, it seems like most of words on the documents were ok other than some incorrect characters and missing characters.  There was only 1 or 2 we could find through visually inspecting the documents that had really messed up contents.

Some of the currently documents uploaded in the system are being combined into a single word

Some of the words in the documents have incorrect letters or missing letters, such as 
- `Eled` instead of `filed`
- `deñeiency` instead of `deficiency`

searching directly for `deñeiency` using order search will return 100+ documents.

Taking the same PDF documents with the incorrect words (deñeiency) and putting them through other OCR software (tesseract.js and AWS Textract) which produced the correct output (more accurate output).  These incorrect words were created by tooling outside of dawson.

Questions we have:
- when the court receives paper documents, what machines / software is currently used to generate and upload the pdfs.  Do these PDFs already have some form of OCR or extracted metadata attached to the PDF.  We'd like to inspect the entire pdf document before they are even uploaded into DAWSON and check the metadata.

**Comment by mariahkannenberg** [comment]
@mmarcotte Can you provide a sample of a document a court user has scanned and uploaded to their computer, but not DAWSON?
