### ISSUE TITLE
BUG: Failover does not occur when one region's DDB table becomes unavailable

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7942]
**Describe the Bug**

When one region's DDB table becomes unavailable (for example, it gets deleted), the system does not properly fail over to the other region's DDB table.

**Business Impact/Reason for Severity**

In the event of a failure, folks should still be able to access the system if a DDB table in another region is available.

**In which environment did you see this bug?**

Any

**Who were you logged in as?**

N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Delete a DynamoDB table in the West region
2. Have a user in that region attempt to login

**Expected Behavior**

The system should continue to function on the one data table that is available.

**Actual Behavior**

The application stops functioning for folks who access from the region that is unavailable

**Screenshots**

**Desktop (please complete the following information):**

N/A 

**Smartphone (please complete the following information):**

N/A 

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by codyseibert** [comment]
Some comments about potential solutions for getting a failover working.

- we could failover at the route53 level using custom health checks against cloudwatch alarms to figure out when dynamodb errors are occuring for (table does not exists) or something.  So when we delete the west table, the route53 record would consider west unhealthy and switch all users to east
- we could put an api gateway in front of the dynamodb services and refactor our backend code to hit that api gateway service proxy instead of talking to dynamodb via the aws-sdk directly: https://aws.amazon.com/blogs/compute/using-amazon-api-gateway-as-a-proxy-for-dynamodb/
- Currently we set DYNAMODB_ENDPOINT on the lambdas which tell the lambda which region to access.  We could temporarly set everything to hit east until after we successfully delete / re-create the west tables with this deploy
- We could also maybe disable the route53 record for the west region, and all traffic would go to the east region.  We could just turn it back on after the deploy.

**Comment by mmarcotte** [comment]
Might this only work if the west table is down? I removed the east able, and the application is currently 400'ing.

The `test` environment is currently in this state with the east table down.
