### ISSUE TITLE
Court: Style Change for Orders

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8112]
As a court user, so that orders conform to the new style guide requirements, I need the new style guidelines implemented in DAWSON.

The court conference has approved a new set of style guidelines that take effect on 1/1/2022. These guidelines need to be incorporated into the formatting of all Orders generated and entered in DAWSON.

Template for visual reference:
[https://app.zenhub.com/files/152320868/b1015f3a-0c6f-46e4-8f43-451f8643672e/download](https://app.zenhub.com/files/152320868/b1015f3a-0c6f-46e4-8f43-451f8643672e/download)

## Acceptance Criteria
* The header "United States Tax Court" is formatted in 20-point font
* The header "United States Tax Court" is formatted in Old English font
* The subheader "Washington, DC 20217" is formatted in 10-point font
* The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
* All other text on the order is formatted in Century Schoolbook font
* All other text on the order is formatted in 12-point font
* Header on multiple pages should be 12-point Century Schoolbook font
* The petitioner's name(s) in the Caption are rendered in all capital letters
* The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
* All text paragraphs are justified
* The new style is applied to all types of Orders in DAWSON

## Notes
* _Question: Do we need to update the text on the print paper service page?_  No - The text that is in the "Print paper service" that contains the Petitioners Name and Address (in the envelope window), as well as the docket number, can remain the same as it currently is.
## Test Cases
* Generate a new Order of any type in DAWSON. Confirm that the Order is compliant with the new style.
* View a previously generated Order of any type in DAWSON. Confirm that the style has not changed on prior Orders.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
**### Test Cases**

**1. Generate a new Short Order of any type in DAWSON. Confirm that the Short Order is compliant with the new style.**
- Log into DAWSON as a docket clerk
- Type in a docket number in the upper right (ex 6543-21), and click search
- Click Create
- Select Order or Notice from the menu
- Select Order Type = Order
- Order Title = you can type whatever you would like
- Click continue
- A new DAWSON Tab will open
- Add in some test text into the body of the Order generator (Keep the body short enough so that the order doesn't go onto a second page.)
- Click the Preview tab

Expected Results: 
- [x] The preview should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified

- Click Save

Expected Results
- [x] The apply signature page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified

- Click Save Signature

Expected Results
- [x] The draft Order on the drafts page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified

- Click Add Docket Entry

Expected Results
- [x] The draft Order on the  Add Docket Entry page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified

- Click the Served button, and then click on "Save and Serve"
- Click "Yes, Serve"

Expected Results:

- [x] The order on the Print Order for Paper Service should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
- [x] The first page in this preview has the Petitioners Name and address for the envelope window, this remains the same Font and size as it was before.

- Click "Done"
- Click on the Docket Entry URL of the Order that you just created. This will open up the Document View.

Expected Results:
- [x] The order on the Document View page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified

**2. Generate a new Long Order of any type in DAWSON. Confirm that the Long Order is compliant with the new style.**
- Log in as a docket clerk
- Type in a docket number in the upper right (ex 6543-21), and click search
- Click Create
- Select Order or Notice from the menu
- Select Order Type = Order
- Order Title = you can type whatever you would like
- Click continue
- A new DAWSON Tab will open
- Add in some test text into the body of the Order generator (Ensure that the body of the Order will go to a second or third page.)
- Click the Preview tab

Expected Results: 
- [x] The preview should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Header on multiple pages should be 12-point Century Schoolbook font

- Click Save

Expected Results
- [x] The apply signature page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Header on multiple pages should be 12-point Century Schoolbook font

- Click Save Signature

Expected Results
- [x] The draft Order on the drafts page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Header on multiple pages should be 12-point Century Schoolbook font

- Click Add Docket Entry

Expected Results
- [x] The draft Order on the  Add Docket Entry page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Header on multiple pages should be 12-point Century Schoolbook font

- Click the Served button, and then click on "Save and Serve"
- Click "Yes, Serve"

Expected Results:

- [x] The order on the Print Order for Paper Service should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
      - [ ] Header on multiple pages should be 12-point Century Schoolbook font
- [ ] The first page in this preview has the Petitioners Name and address for the envelope window, this remains the same Font and size as it was before.

- Click "Done"
- Click on the Docket Entry URL of the Order that you just created. This will open up the Document View.

Expected Results:
- [x] The order on the Document View page should display the Order in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Header on multiple pages should be 12-point Century Schoolbook font

**3. Confirm that the Standing Pretrial Order (an Autogenerated Order in DAWSON) is compliant with the new style**
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session"
- Fill in the Session information (It shouldn't matter if it is in person or remote)
- Click "Add Session"
- A green message will appear indicating "Trial Session added".
- Click on the "New" link, and navigate to the trial session you just created.
- Click on the City URL
- Check the "QC Complete?" boxes for a few cases in the Eligible case list.
- Click "Set Calendar"
- A modal will appear, click "Yes, Set Calendar"

Expected Results:
- [ ] The Print and mail all paper service documents will have the SPTO for all the cases in the trial in the New Style format (The Notice Style format will be addressed in a future story - Just ensure SPTO is compliant)
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
      - [ ] Header on multiple pages should be 12-point Century Schoolbook font
- [ ] The first page in this preview has the Petitioners Name and address for the envelope window, this remains the same Font and size as it was before.

- Click Done
- Click on the "Open" tab to go find the Trial session you just created
- Click on the City, State URL of the trial session
- Select a docket number from the list of cases (I chose to open it in a new tab)
- Scroll down the docket record to find the SPTO
- Click on the SPTO URL. This will open the document up in the document view

Expected Results:
- [ ] The Document View will have the SPTO in the New Style format 
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in Century Schoolbook font
     - [ ] All other text on the order is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
      - [ ] Header on multiple pages should be 12-point Century Schoolbook font


**4. View a previously generated Short Order of any type in DAWSON. Confirm that the style has not changed on prior Short Orders.**
- Log in as a Docket Clerk
- Type in a docket number into the search box in the upper left (ex 7890-21) (Any docket number is fine, as long as there is a previously generated Order on the docket record)
- Click on the Docket entry URL of the Order. 

Expected Results
- [x] The previously generated Order is in the older style format.

**5. View a previously generated Long Order of any type in DAWSON. Confirm that the style has not changed on prior Long Orders.**
- Log in as a Docket Clerk
- Type in a docket number into the search box in the upper left (ex 13491) (Any docket number is fine, as long as there is a previously generated Long Order on the docket record. Standing Pretrial Orders are 6 pages!  You can search for these!)
- Click on the Docket entry URL of the Long Order (in 13491-21, it is docket entry ustaxcourt/ef-cms#6496). 

Expected Results
- [x] The previously generated Long Order is in the older style format.

**Comment by TomElliottFlexion** [comment]
New order format: [https://app.zenhub.com/files/152320868/91e61f7c-fc89-4fa8-90ae-ff52b0846c6f/download](https://app.zenhub.com/files/152320868/91e61f7c-fc89-4fa8-90ae-ff52b0846c6f/download)

Notice with updated header (ad hoc generated): [https://app.zenhub.com/files/152320868/69ce2bf9-5af7-42d2-9c2a-6007e327bf48/download](https://app.zenhub.com/files/152320868/69ce2bf9-5af7-42d2-9c2a-6007e327bf48/download)

**Comment by codyseibert** [comment]
note: This work is basically completed and stored in the `9093-order-style-changes` branch.

**Comment by cholly75** [comment]
@codyseibert - two pieces of feedback re: this story

1) We need to add commas after the Petitioner's name and the Respondent's name (i.e., the word "Revenue") as in the attached sample in the story body above.
2) Let's put the word "Revenue" in Respondent's name on a new line aligned with "Commisioner" as in the attached sample in the story body above so it doesn't butt up against the caption divider.

Sample generated in TEST: [https://app.zenhub.com/files/152320868/6d945fa3-da9e-4fef-be9c-e87dc8bb4ba4/download](https://app.zenhub.com/files/152320868/6d945fa3-da9e-4fef-be9c-e87dc8bb4ba4/download)

Thanks!
Chris

**Comment by cholly75** [comment]
Additional comment related to general PDF style changes (DevEx work, if I'm not mistaken): it appears the wrong font (and possibly size, but it's hard to tell what's a function of the font difference) is being used on several PDFs resulting in documents with strange or multiple fonts being used. I didn't see these in the preview sent prior to reviewing the story, some examples are attached here.

[https://app.zenhub.com/files/152320868/988e50fb-5ff6-4095-9807-8f3d8ecab627/download](https://app.zenhub.com/files/152320868/988e50fb-5ff6-4095-9807-8f3d8ecab627/download)

[https://app.zenhub.com/files/152320868/bc92c709-6859-44ec-ab71-6377cfd136ff/download](https://app.zenhub.com/files/152320868/bc92c709-6859-44ec-ab71-6377cfd136ff/download)

**Comment by cholly75** [comment]
@codyseibert - generated an order ([https://app.zenhub.com/files/152320868/4db95788-2128-48ef-ba57-4d3068574bfc/download](https://app.zenhub.com/files/152320868/4db95788-2128-48ef-ba57-4d3068574bfc/download)) and it looks like the work done to normalize the header font for pages 2 and beyond has reverted? Are you seeing the same?

**Comment by cholly75** [comment]
All tests pass except ustaxcourt/ef-cms#6493 (SPTO) - it still retains the old header styling. I think that's OK, as that one really resembles a notice more than an order anyway. @codyseibert - do you know if the code for the 2nd page header font correction just never made it over to TEST when we implemented it, or is it a regression bug?

**Comment by cholly75** [comment]
Update: yeah, we need to fix the SPTO.
