### ISSUE TITLE
Docket Clerk: Unseal an individual document

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8141]
As a docket clerk, so that I can appropriately represent the sealed state of a particular document, I need to be able to unseal individual docket entries.

ustaxcourt/ef-cms#7164 -- back-end work to allow the sealed flag at the document level

## Pre-Conditions
ustaxcourt/ef-cms#7042
ustaxcourt/ef-cms#8120

## Acceptance Criteria
* Docket clerk has the ability to unseal one or more individual sealed documents on a case
* Docket clerk can select a document to be unsealed, and must explicitly confirm they wish to unseal the selected document
* Unsealing a document makes that document visible to all users following normal visibility rules
* Docket record reflects unsealed status of document once the document is unsealed
* Unsealing a document does not change the sealed status of the Case
* Unsealing an Order makes that Order eligible to be returned as a search result in Order Search, following normal visibility rules
* Unsealing process is the same regardless of whether a document was initially sealed to "all" or "public" users
* Unsealing process is the same between legacy and new sealed documents.
* Both legacy and "new" sealed documents can be unsealed.

## Notes

* Is there any modification that needs to be made to existing data to enable this functionality? - _Not expected_

### Remaining tasks
- [x] Confirm that sealing and unsealing permissions are the same 
- [x] Replace red lock symbol with similar red unlock symbol as used in the Case Details section (?)
- [x] Confirm unchecked test scenarios
- [ ] Fix unseal button overflow on docket entry with edit button

## Test Cases
* Docket clerk navigates to Sealed case with one sealed document. Clerk unseals document; case remains sealed, unviewable to public; UI on Docket record updated to reflect unsealed status of document
* Docket clerk navigates to Sealed case with multiple sealed documents. Clerk unseals some of the sealed documents; case remains sealed, unviewable to public; UI on Docket record updated to reflect unsealed status of documents; documents not selected to be unsealed remain sealed
* Docket clerk navigates to Sealed case with multiple sealed documents. Clerk unseals all of the sealed documents; case remains sealed, unviewable to public; UI on Docket record updated to reflect unsealed status of documents
* Docket clerk navigates to unsealed case with one sealed document. Clerk unseals document; case remains unsealed, viewable to public; UI on Docket record updated to reflect unsealed status of document
* Docket clerk navigates to unsealed case with multiple sealed documents. Clerk unseals some of the sealed documents; case remains unsealed, viewable to public; UI on Docket record updated to reflect unsealed status of documents; documents not selected to be unsealed remain sealed
* Docket clerk navigates to unsealed case with multiple sealed documents. Clerk unseals all sealed documents; case remains unsealed, viewable to public; UI on Docket record updated to reflect unsealed status of documents
* Docket clerk selects any number of docket entries on a case to be unsealed, cancels out of explicit confirmation of unsealing. Documents remain sealed.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [x] Deployed to the Court's migration environment

**Comment by swongCO** [comment]
**See ustaxcourt/ef-cms#7042 for sealing a document**
 
![USTC Docket Record Unseal modal.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cf212036-83ff-4b68-81b2-d9aa49fd04bc)

- When the Unseal link is clicked, display modal
- When the user unseals a document, the lock icon in the status column disappears and the Unseal link changes to the Seal link

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Docket Clerk navigates to a sealed case with one sealed document, unseals the sealed document**
- Log in as a docket clerk

There are some steps to take to set up this test:
- Navigate to an unsealed case
- Go to the Case information tab
- On the Overview sub-tab 
- Click on the Seal link 
     - You should see the red banner on the top of the page, indicating that the case is now sealed
     - You should also see a red URL that says "Unseal case"
- Next, navigate to the docket record on the newly sealed case.
- Select a document on the docket record to seal
- Click the seal link on the far right column of the docket record.
     - A modal will pop up, keep the default select and select "Seal"
     - You should see the red lock symbol appear next to the document name

Now you have the Case set up for this test.
- Click the "Unseal link" on the far right of the docket record
- A model will pop-up asking you "Are you sure you want to unseal this document?"
- Click "Unseal"

Expected results
- [ ] The lock icon next to the document name is no longer present
- [ ] The far right column now has the "Seal" link in blue
- [ ] Case remains sealed - You should see the red banner at the top of the screen.


**2. (NEW) Docket Clerk navigates to a sealed case with one legacy sealed document, unseals the sealed document**
- Log in as a docket clerk
- Navigate to a legacy sealed case that has one legacy sealed document (I couldn't find one in this state, but I did find 1078-20 which only has a few legacy sealed documents.)
- There are a few steps to take to set up this test:
     - Unseal docket entry # 8 and ustaxcourt/ef-cms-flexion#10
     - This should only leave docket entry # 17 sealed

- Now you have the case set up for this test
- Click the "Unseal link" on the far right of the docket record for index ustaxcourt/ef-cms#6499
- A model will pop-up asking you "Are you sure you want to unseal this document?"
- Click "Unseal"

Expected results
- [ ] The lock icon next to the document name is no longer present
- [ ] The far right column now has the "Seal" link in blue
- [ ] Case remains sealed - You should see the red banner at the top of the screen.


**3. (UPDATED)Public user attempts to view case by entering the docket number on case search screen.**
- Navigate to the DAWSON dashboard
- Type in the docket # of the sealed cases that you used in test case 1 and 2 and click search

Expected results:
- [ ] You should see a page that states "This case is sealed and not accessible to the public"


**4. (UPDATED) Docket Clerk navigates to a sealed case with multiple legacy sealed documents, unseals some (but not all) sealed documents**
- Log in as a docket clerk
- Navigate to a sealed case that has multiple legacy sealed documents (ex: 16927-19)
- Click the unseal link on the far right of the docket record for multiple documents (Orders will be tested in a separate test case - Please stick with documents for this step, rather than orders.)

Expected Results:
- [ ] A modal will pop up asking you "Are you sure you want to unseal this document?" for each document that you click to unseal.
- [ ] The lock symbol that was next to each of the document names on the docket record will no longer appear after you confirm that you would like to unseal.
- [ ] Lock symbol next to the documents that you did not unseal remains present on the docket record, indicating that these documents are still sealed.
- [ ] Case remains sealed - You should see the red banner at the top of the page indicating that the case is sealed.


**5. Public user attempts to view case by entering the docket number on case search screen.**
- Navigate to the DAWSON dashboard
- Type in the docket # of the sealed case that you used in test case 4 and click search

Expected results:
- [ ] You should see a page that states "This case is sealed and not accessible to the public"


**6. (UPDATED) Docket clerk navigates to a sealed case with multiple legacy sealed documents, unseals all sealed documents** 
- Log in as a docket clerk
- Navigate to a sealed case that has multiple legacy sealed documents (ex: 20399-17)
- Click the unseal link on the far right of the docket record for all of the documents that are already sealed (Depending on the case, you may be unsealing documents AND Orders with this test.)

Expected Results:
- [ ] A modal will pop up asking you "Are you sure you want to unseal this document?" for each document that you click to unseal.
- [ ] The lock symbol that was next to each of the document names on the docket record will no longer appear after you confirm that you would like to unseal.
- [ ] Case remains sealed - You should see the red banner at the top of the page indicating that the case is sealed.

**7. Public user attempts to view case by entering the docket number on case search screen.**
- Navigate to the DAWSON dashboard
- Type in the docket # of the sealed case that you used in test case 6 and click search

Expected results:
- [ ] You should see a page that states "This case is sealed and not accessible to the public"


**8. Docket clerk navigates to unsealed case with one sealed document, unseals document**
- Log in as a docket clerk

There are some steps to take to set up this test:
- Navigate to an unsealed case
- Select a document on the docket record to seal
- Click the Seal link on the far right column of the docket record.
     - A modal will pop up, keep the default select and select "Seal"
     - You should see the red lock symbol appear next to the document name

Now you have the Case set up for this test.
- Click the "Unseal link" on the far right of the docket record for the document that you just sealed in the previous steps.
- A model will pop-up asking you "Are you sure you want to unseal this document?"
- Click "Unseal"

Expected results
- [ ] The lock icon next to the document name is no longer present
- [ ] The far right column now has the "Seal" link in blue
- [ ] Case remains unsealed - You should NOT see the red banner at the top of the screen.

**9. Public user attempts to view case by entering the docket number on case search screen.**
- Navigate to the DAWSON dashboard
- Type in the docket # of the unsealed case that you used in test case 8 and click search

Expected results:
- [ ] You should see the "public view" of the docket record 
- [ ] Orders/Opinions that are on the docket record should have active hyperlinks, so that you can open and view them
- [ ] No document on the docket record should have the lock symbol.
- [ ] You should be able to read all of the information about the document on the docket record, but not actually be able to open the document.


**10. Docket Clerk navigates to an unsealed case with multiple sealed documents, unseals some (but not all) sealed documents.**
- Log in as a docket clerk

There are some steps to take to set up this test:
- Navigate to an unsealed case
- Select multiple documents on the docket record to seal. For each document: 
     - Click the seal link on the far right column of the docket record.
          - A modal will pop up, keep the default select and select "Seal"
          - You should see the red lock symbol appear next to the document name

Now you have the Case set up for this test.
- Click the "Unseal link" on the far right of the docket record for SOME of the documents that you just sealed (Not all of them!)
- A model will pop-up asking you "Are you sure you want to unseal this document?"
- Click "Unseal"

Expected results
- [ ] The lock icon next to the document names that you clicked "unseal" for are no longer present
- [ ] The far right column for these documents now have the "Seal" link in blue
- [ ] The lock icon next to the document names that you did not "unseal" are still present on the docket record
- [ ] Case remains unsealed - You should NOT see the red banner at the top of the screen.

**11. Public user attempts to view case by entering the docket number on case search screen**
- Navigate to the DAWSON dashboard
- Type in the docket # of the unsealed case that you used in test case 10 and click search

Expected results:
- [ ] You should see the "public view" of the docket record 
- [ ] Unsealed Orders that are on the docket record should have active hyperlinks, so that you can open and view them
- [ ] You should see that some of the documents on the docket record have the lock symbol. (these should be the index numbers that you did not unseal from the previous test case)
- [ ] The lock symbol should not be present next to any of the documents that you unsealed from the previous test case.
- [ ] For the sealed and unsealed documents, you should be able to read all of the "metadata" information about the document on the docket record, but not actually be able to open the document.

**12. Docket clerk navigates to an unsealed case with multiple sealed documents, unseals all sealed documents** 
- Log in as a docket clerk

There are some steps to take to set up this test:
- Navigate to an unsealed case
- Select multiple documents on the docket record to seal. For each document: 
     - Click the seal link on the far right column of the docket record.
          - A modal will pop up, keep the default select and select "Seal"
          - You should see the red lock symbol appear next to the document name

Now you have the Case set up for this test.
- Click the "Unseal link" on the far right of the docket record for ALL of the documents that you just sealed 
- A model will pop-up asking you "Are you sure you want to unseal this document?"
- Click "Unseal"

Expected results
- [ ] The lock icon next to the document names that you clicked "unseal" for are no longer present
- [ ] The far right column for these documents now have the "Seal" link in blue
- [ ] There should be no individual lock symbols present on the docket record
- [ ] Case remains unsealed - You should NOT see the red banner at the top of the screen.

**13. Public user attempts to view case by entering the docket number on case search screen.**
- Navigate to the DAWSON dashboard
- Type in the docket # of the unsealed case that you used in test case 12 and click search

Expected results:
- [ ] You should see the "public view" of the docket record 
- [ ] Unsealed Orders that are on the docket record should have active hyperlinks, so that you can open and view them
- [ ] The lock symbol should not be present next to any of the documents that you unsealed from the previous test case.
- [ ] You should be able to read all of the "metadata" information about the document on the docket record, but not actually be able to open the document.

**14. Docket clerk selects any number of docket entries on a case to be unsealed, cancels out of explicit confirmation of unsealing.**
- Log in as a docket clerk
- Navigate to a case that has multiple sealed documents on the docket record
- Click the Unseal link on the far right side of the docket record
- A modal will pop-up asking you "Are you sure you want to unseal this document?"
- Click "Cancel"

Expected results:
- [ ] Modal closes and the document that you clicked Unseal on remains sealed

**15. (UPDATED) Docket clerk navigates to a sealed case with a legacy sealed Order, unseals the order**
- Log in as a docket clerk
- Navigate to a sealed case that has at least one legacy sealed Order (ex: 21582-18)
- Click the unseal link on the far right of the docket record for at least one of the Orders that are already sealed 

Expected Results:
- [ ] A modal will pop up asking you "Are you sure you want to unseal this document?" 
- [ ] The lock symbol that was next to the Order name on the docket record will no longer appear after you confirm that you would like to unseal.
- [ ] Case remains sealed - You should see the red banner at the top of the page indicating that the case is sealed.


**16. Public user searches for unsealed order in a sealed case**
- Navigate to the DAWSON dashboard
- Click on the Order tab
- Search for the Order from test case ustaxcourt/ef-cms-flexion#15 by using all (and a combination) of the search fields:
     - Enter the Docket Number, search
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that served the Order
 - Click Search

Expected results:
- [ ] You should see a page that states "This case is sealed and not accessible to the public"


**17. Docket clerk navigates to an unsealed case that has a sealed order, unseals the Order**
- Log in as a docket clerk

There are some steps to take to set up this test:
- Navigate to an unsealed case
- Select an Order on the docket record to seal
- Click the Seal link on the far right column of the docket record.
     - A modal will pop up, keep the default select and select "Seal"
     - You should see the red lock symbol appear next to the Order name

Now you have the Case set up for this test.
- Click the "Unseal link" on the far right of the docket record for the Order that you just sealed in the previous steps.
- A model will pop-up asking you "Are you sure you want to unseal this document?"
- Click "Unseal"

Expected results
- [ ] The lock icon next to the Order name is no longer present
- [ ] The far right column now has the "Seal" link in blue
- [ ] Case remains unsealed - You should NOT see the red banner at the top of the screen.


**18. Public user searches for the unsealed order in the unsealed case**
- Navigate to the DAWSON dashboard
- Search for the Order from test case ustaxcourt/ef-cms#6499 by using all (and a combination) of the search fields:
     - Enter the Docket Number, search
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that served the Order
 - Click Search

Expected Results:
- [ ] Order from Test case ustaxcourt/ef-cms#6499 should be available in the search results.
- [ ] Lock symbol should be NOT be present next to the Order Name in the Search results list
- [ ] When clicking on the Order, it should open a new tab, and the public user should be able to view the Order

**Comment by ttlenard** [comment]
@TomElliottFlexion, @codyseibert 

I'm running into errors on Test Case ustaxcourt/ef-cms#6493.  When attempting to unseal a legacy sealed document, I get a 400 error.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cc8151d8-f972-4e95-a0e3-6b2e057ae5d6)

Here is the log entry from Kibana:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/96dd8648-88eb-4c13-a588-e9ce94328776)

This isn't happening when I seal, and then unseal a document on a case. Seems to only happen with the legacy sealed documents.
