### ISSUE TITLE
Notice of Change to In Person Proceeding

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8158]
As a docket clerk, so that I do not have to manually generate and serve needed documentation, I need DAWSON to generate and serve a Notice of Change to In Person Proceeding when a Trial Session with calendared cases has its proceeding type changed from Remote to In Person.

Depending on local circumstances, some calendared trial sessions are being changed from Remote to In Person. When this happens, docket clerks must create a docket entry and generate a Notice of Change To In Person Proceeding for all open cases that are currently assigned to that trial session, then serve said notice. We would like DAWSON to do this for them. 

[https://app.zenhub.com/files/152320868/8471202d-cd24-449e-ae75-a4a1d7d52de3/download](https://app.zenhub.com/files/152320868/8471202d-cd24-449e-ae75-a4a1d7d52de3/download)

## Acceptance Criteria
* When a calendared Trial Session with one or more active cases is edited to change the Proceeding Type from Remote to In Person, upon saving the changes to a Trial Session a Notice of Change to In Person Proceeding (NOIP) is generated for each open case currently attached to that Trial Session.
* The NOIP generated uses the template attached to this story and derives values from the Trial Session data:
  - Building Location: derived from the Courthouse Name data on the Trial Session
  - Address: derived from the Address 1 and Address 2 data on the Trial Session 
  - City, St, ZIP: derived from the City, State, and ZIP Code data on the Trial Session
  - Judge: derived from the Judge data on the Trial Session
  - [location]: derived from the Location data on the Trial Session
  - [date, graf 1]: derived from the Date of the Trial Session prior to the edit that changes the Proceeding Type to In Person
  - [time, graf 1]: derived from the Time of the Trial Session prior to the edit that changes the Proceeding Type to In Person
  - [day, date, graf 2]: derived from the current Date of the Trial Session
  - [time, graf 2]: derived from the current Time of the Trial Session 
* The NOIP is added as a docket entry to the docket record with the link text "Notice of Change to In Person Proceedings"
* The NOIP is immediately served via email to parties on the case with electronic service
* A print queue for NOIPs needing to be printed and served manually is presented to the clerk in the same way that the Notices Setting Case For Trial (NTDs) are upon calendaring a Trial Session

## Notes
* Event code: NOIP

## Tasks

- [x] Generate notice when trial session is changed from remote to in person
  - [x] Create notice document
  - [x] Add docket entry for document on cases
  - [x] Serve notice to parties
  - ~[ ] DOD: research and refactor the calendaredCases and userNotes that we removed from this PR (https://github.com/ustaxcourt/ef-cms/pull/2160/files)~ devex task

## Test Cases
* Case w/ parties receiving electronic service is calendared for Remote trial session; Trial Session is changed from Remote to IP; NOIP is generated and served electronically; NOIP appears on docket record
* Case w/ parties receiving paper service is calendared for In Person trial session; Trial Session is changed from Remote to IP; NOIP is generated and presented to clerk for printing and service; NOIP appears on docket record 
* Trial Session is changed from Remote to IP but the changes are not saved; no NOIP is generated for any cases
* Trial Session is changed from Remote to IP along with date/time values; NOIP is generated using all new values on Trial Session
* NOIPs are generated appropriately for all open cases on trial session, none are generated for closed cases on trial session

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
@liadmccabe - are you OK with me adding AC in this story to address the better UI for waiting for generated documents we discussed (i.e., progress bar), or would you prefer I add it to the next story in the pipeline (9467) that will have the same behavior?

**Comment by liadmccabe** [comment]
@cholly75 yeah that's fine to have it here

**Comment by ttlenard** [comment]
## Test Cases

####  1) Case w/ parties receiving electronic service is calendared for Remote trial session; Trial Session is changed from Remote to IP; NOIP is generated and served electronically; NOIP appears on docket record
* Log in as a Petitions clerk
* Click on Trial Sessions
* Click on Add Trial Session
* Pick a date in the future, Proceeding type = Remote, fill in all other required fields (including judge, chambers phone #, etc.)
* Click Add Session
* You should receive confirmation that the trial session was added.
* log out of DAWSON

* Log in as an Admissions Clerk
* Navigate to the trial session that you just created and find a case in the Eligible case list that has a Petitioner that is currently receiving paper service
* Add in an email that you have access to for one of the petitioners (if it is a new email, be sure to verify it so that it is not in a pending state)
* Log out of DAWSON

* Log in as Petitions Clerk
* Navigate back to the Trial Session that you created in the previous steps
* On the Eligible case list, make sure that you mark the case that you just added an email in as QC Complete
* Click a few more cases as QC Complete
* Click Set Calendar
* Click Yes, Set Calendar
* You should get a confirmation that the calendar was set.
* You should have also received an email indicating that a document was served on your case

* Next, Open the trial session that you just created and click on the Edit link next to session information
* Update the Proceeding type from Remote to In Person
* Fill in the Courthouse Name, Address, City, State, and Zip
* Click Save
Expected Results
- [ ] Green confirmation that the Trial session was updated
- [ ] After clicking on the docket number link of the cases in the trial sessions, there will be a Notice of Change to In Person Proceeding on the Docket Record
- [ ] After opening the document on the docket record, the document is in the correct format as listed in this example: https://app.zenhub.com/files/152320868/fbef13a7-983c-4f60-87be-6cdc6c49d84c/download
- [ ] You should have received an email indicating Service of the document on the docket record.



#### 2) Case w/ parties receiving paper service is calendared for In Person trial session; Trial Session is changed from Remote to IP; NOIP is generated and presented to clerk for printing and service; NOIP appears on docket record
* Log in as a Petitions clerk
* Click on Trial Sessions
* Click on Add Trial Session
* Pick a date in the future, Proceeding type = Remote, fill in all other required fields (including judge, chambers phone #, etc.)
* Click Add Session
* You should receive confirmation that the trial session was added.
* On the Eligible case list, make sure that you mark some cases that have Petitioners receiving paper service as QC complete.
* Click Set Calendar
* Click Yes, Set Calendar
* You should get a confirmation that the calendar was set.
* Next, Open the trial session that you just created and click on the Edit link next to session information
* Update the Proceeding type from Remote to In Person
* Fill in the Courthouse Name, Address, City, State, and Zip
* Click Save
Expected Results
- [x] The Print for paper service appears, and the Notice of Change to In Person Proceeding should be available for printing to send to the paper petitioners
- [x] The Notice should be in the correct format as listed in this example: https://app.zenhub.com/files/152320868/fbef13a7-983c-4f60-87be-6cdc6c49d84c/download
- [x] Click Done
- [ ] Green confirmation that the Trial session was updated
- [x] After clicking on the docket number link of some of the cases in the trial session, there will be a Notice of Change to In Person Proceeding on the Docket Record
- [ ] After opening the document on the docket record, the document is in the correct format as listed in this example: https://app.zenhub.com/files/152320868/fbef13a7-983c-4f60-87be-6cdc6c49d84c/download


#### 3) Trial Session is changed from Remote to IP but the changes are not saved; no NOIP is generated for any cases
* Log in as a Petitions clerk
* Click on Trial Sessions
* Click on Add Trial Session
* Pick a date in the future, Proceeding type = Remote, fill in all other required fields (including judge, chambers phone #, etc.)
* Click Add Session
* You should receive confirmation that the trial session was added.
* On the Eligible case list, make sure that you mark some cases that have Petitioners receiving paper service as QC complete.
* Click Set Calendar
* Click Yes, Set Calendar
* You should get a confirmation that the calendar was set.
* Next, Open the trial session that you just created and click on the Edit link next to session information
* Update the Proceeding type from Remote to In Person
* Fill in the Courthouse Name, Address, City, State, and Zip
* Click Cancel
* Click Yes, Cancel
Expected Results
- [ ] DAWSON navigates back to the Trial Sessions Open tab
- [ ] When you click on the Trial session that you just cancelled out of, all of the original fields remain the same.
- [ ] When you open one of the cases in the trial session, no NOIP of generated on the Docket record.

#### 4) Trial Session is changed from Remote to IP along with date/time values; NOIP is generated using all new values on Trial Session
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on the "Open" tab to find a Remote trial session that is in the future
- Click on the City, State URL
- Click on the Edit link next to "Session Information"
- Change the date of the Trial Session
- Change the time 
- Scroll down on the Edit Trial Session Page until you get to the Location Information Section
- Change the Proceeding type from "Remote" to "In Person"
- Fill in the In Person proceeding fields (Court house name, address, etc.)
- Click Save

Expected Results:
- [ ] The Print for Paper Service page appears for Court user to print all paper service
- [ ] The NOIP presented for paper service has the following information:
     - [ ] Building Location: derived from the Courthouse Name data on the Trial Session
     - [ ] Address: derived from the Address 1 and Address 2 data on the Trial Session
     - [ ] City, St, ZIP: derived from the City, State, and ZIP Code data on the Trial Session
     - [ ] Judge: derived from the Judge data on the Trial Session
     - [ ] [location]: derived from the Location data on the Trial Session
     - [ ] [date, graf 1]: derived from the Date of the Trial Session prior to the edit that changes the Proceeding Type to In Person
     - [ ] [time, graf 1]: derived from the Time of the Trial Session prior to the edit that changes the Proceeding Type to In Person
     - [ ] [day, date, graf 2]: derived from the current Date of the Trial Session
     - [ ] [time, graf 2]: derived from the current Time of the Trial Session
     - [ ] Service stamp at the bottom of the Notice has today's date

- Click Done
- DAWSON will bring you back to the Session Information Screen.
- Validate that the Session information now indicates all of the In Person Proceeding fields you added.
- Open one of the docket records from the Open Cases list (I opened in a new tab)
- Verify that the Notice of Change to In Person Proceeding is present on the Docket Record

Expected Results:
- [ ] The NOIP is the last docket index on the record
- [ ] Date is Today's date
- [ ] Event Code = NOIP
- [ ] Filings and Proceedings = Notice of Change to In Person Proceeding, this should be a link
- [ ] Pages = the total pages of the Notice
- [ ] Filed by = Blank
- [ ] Service Date = Today's date
- [ ] Parties = B

- Open the NOIP by clicking on the URL on the docket record.

Expected Results:
- [ ] The NOIP opened via the document viewer has the following information:
     - [ ] Building Location: derived from the Courthouse Name data on the Trial Session
     - [ ] Address: derived from the Address 1 and Address 2 data on the Trial Session
     - [ ] City, St, ZIP: derived from the City, State, and ZIP Code data on the Trial Session
     - [ ] Judge: derived from the Judge data on the Trial Session
     - [ ] [location]: derived from the Location data on the Trial Session
     - [ ] [date, graf 1]: derived from the Date of the Trial Session prior to the edit that changes the Proceeding Type to In Person
     - [ ] [time, graf 1]: derived from the Time of the Trial Session prior to the edit that changes the Proceeding Type to In Person
     - [ ] [day, date, graf 2]: derived from the current Date of the Trial Session
     - [ ] [time, graf 2]: derived from the current Time of the Trial Session
     - [ ] Service stamp at the bottom of the Notice has today's date

#### 5) NOIPs are generated appropriately for all open cases on trial session, none are generated for closed cases on trial session
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on the "Open" tab to find a Remote trial session that is in the future
- Click on the City, State URL
- Scroll down to the Case list
- Ensure that there are multiple cases on the trial session that you selected, and that there are both Open (Active) Cases, as well as inactive (closed) cases associated with the trial session.  I selected a large Metropolitan city to test with. 
- While you are on the Inactive Cases list, find a case where the Petitioner has paper service and remember this docket number for a later test.
- Click on the Edit link next to "Session Information" 
- Scroll down on the Edit Trial Session Page until you get to the Location Information Section
- Change the Proceeding type from "Remote" to "In Person"
- Fill in the In Person proceeding fields (Courthouse address, etc.)
- Click Save

Expected Results:
- [ ] The Print for Paper Service page appears for Court user to print all paper service
- [ ] The NOIP presented for paper service has all of the information from Test case 1 for Active Cases (If you already validated via Test Case 1, a quick review on this is fine).
- [ ] The NOIP is NOT generated for paper service for the docket number of the closed case that you noted above

- Click Done
- DAWSON will bring you back to the Session Information Screen.
- Validate that the Session information now indicates all of the In Person Proceeding fields you added.
- Scroll down to the Case List section, an click on the Inactive Cases link.
- Open a few of the docket records from the Inactive Cases list (I opened each in a new tab)

Expected Results:
- [ ] The NOIP is the NOT Present as the last docket index on the record for any of the Inactive cases

**Comment by cholly75** [comment]
@rachelschneiderman - there has been an update to the event code for this notice: instead of NOCIP, we would like the code to be NOIP. Let me know if you want to discuss. I will update the language in the story. Thanks!

**Comment by cholly75** [comment]
Updated template file to remove reference to time zone in notice text.
