### ISSUE TITLE
Send out Clinic Letters w/ Notice Setting Case for Trial

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8173]
As a petitions clerk, so that I can send pro se petitioners needed tax clinic documentation prior to their trial, I need to be able to send these letters with the Notice Setting Case for Trial.

For pro se petitioners who may not be able to afford or locate counsel to guide them through their case, there are tax clinics available as a resource who often advise and/or represent lower income petitioners. These clinics provide the Court with letters for petitioners indicating the details on how to use these resources, and as part of the Court's commitment to taxpayer equity prior to DAWSON we sent these letters to pro se petitioners along with official Court notices at various points in the life of the case.

These letters are not official Court or IRS documentation, but we provide them as a courtesy. There are one or more letters for each place of trial where the Court conducts business.

We would like to re-establish the process of generating and sending out these letters at the same time we send the Notice Setting Case for Trial by appending them to said Notices at the time the Notices are generated.

The letters themselves are provided in toto by the clinics to the Court; no customization is needed to the letter text itself, and these are not docketed separately as entries on the official record.

## Pre-Conditions
ustaxcourt/ef-cms#8316
ustaxcourt/ef-cms#8317
ustaxcourt/ef-cms#8172

## Acceptance Criteria
* When a Notice Setting Case for Trial is generated for any case where the Petitioner is unrepresented by counsel, the appropriate clinic letter is appended to the Notice after the final page of the Notice.
* The specific letter appended to the Notice Setting Case for Trial is determined by Location data on the session and the Case Procedure on the case. If there are multiple letters available for a particular location, the specific letter appended is determined by the Case Procedure data on the case.
* If any NTD was generated with a clinic letter appended for a case, the appended clinic letter displays along with the Notice in its entirety when viewed in DAWSON from docket record 
* When a clinic letter is replaced with a new version, all Notices Setting Case For Trial generated after that use the new version of that letter
* When multiple petitioners are attached to a case:
- If only one Notice Setting Case for Trial is generated, if any of the petitioners are represented by counsel, do not append the clinic letter to the Notice.
- If multiple Notices Setting Case for Trial are generated for the case, evaluate each petitioner individually and attach the clinic letter to each Notice where the petitioner is not represented by counsel.

## Test Cases
* Pro se petition is calendared for trial session with a Trial Location that has only one clinic letter available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document
* Pro se petition is calendared for a trial session with a Trial Location that has multiple clinic letters available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document
* Represented petition is calendared for a trial session with a Trial Location that has one or more clinic letters available; notice setting case for trial is generated; notice document has no clinic letter appended
* Clinic letter for location is updated in repository; new pro se petition is calendared for trial; notice setting case for trial is generated with appropriate clinic letter appended as final pages of document
* Notice Setting Case for Trial is generated w/ clinic letter appended; Notice is viewed from Docket Record; Notice displays in its entirety along with clinic letter; no separate entry exists on docket for clinic letter  
* Multiple Petitioners (same address) - repped, unrepped, mix
* Multiple Petitioners (different address) - repped, unrepped, mix

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Pro se petition is calendared for trial session with a Trial Location that has only one clinic letter available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document**
- Ensure that there is a clinic letter in the repository for a small proceeding type in Denver, CO. Be sure that there is NOT a clinic letter available for Denver, CO for a regular proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading a new clinic letter, be sure that it is in this format: _clinic-letter-denver-colorado-small_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Small
     - Proceeding type = In Person
     - Location = Denver, CO 
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "Denver, Colorado" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that these petitioners are not represented by counsel.)
- Be sure that some of the petitioners have paper service, and some of the petitioners in the cases selected receive electronic service. Take note of the specific docket numbers that have electronic vs. paper service for testing with later.
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results:

- [x] The Print for Paper Service page will appear
- [x] Ensure that the docket number that you noted earlier for the paper petitioner is available on this print paper service screen.
- [x] Ensure that the docket number for the electronic petitioner is NOT available on this print paper service screen
- [x] First page is mostly blank with the petitioners address for the envelope window
- [x] Next is the Notice Setting Case for Trial
- [x] After the Notice Setting Case for Trial, there should be the appropriate clinic letter that was loaded in the Denver, CO repository for Small proceeding types.
- [x] After the Clinic Letter, it should have the Standing Pre-Trial Order for Small Tax Cases, and then the Petitioners Checklist, and finally the Pretrial Memorandum.
- [x] Continue to scroll through the Print for Paper service page, and ensure that the appropriate clinic letter is appended after the Notice Setting Case for Trial Page

**2.  Notice Setting Case for Trial is added to the Docket Record. When opened, the appropriate Clinic Letter is appended to the end of the Notice.**
- Continuing from Test Case 1
- Click "Done" on the Print Paper Service Screen
- Click on the Open tab
- Find the Trial Session that you created in Test Case 1 for Denver, CO
- Click on the link for "Denver, Colorado" to open the session
- Click on the Docket number for a few of the cases (I opened in a new tab for each one)
- Click on the Notice of Trial link

Expected Results

- [x] On the Document View page, if you scroll down, the appropriate Clinic letter should be appended to the end of the Notice.
- [x] No separate entry exists on the docket record for the Clinic Letter

**3. Pro se petition is calendared for a trial session with a Trial Location that has multiple clinic letters available; notice setting case for trial is generated; notice document has appropriate clinic letter appended as final pages of document**
- Ensure that there are two clinic letters in the repository for Denver, CO. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-denver-colorado-small_ and _clinic-letter-denver-colorado-regular_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Regular
     - Proceeding type = In Person
     - Location = Denver, CO 
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "Denver, Colorado" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that these petitioners are not represented by counsel.)
- Be sure that some of the petitioners have paper service, and some of the petitioners in the cases selected receive electronic service. Take note of the specific docket numbers that have electronic vs. paper service for testing with later.
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results:

- [x] The Print for Paper Service page will appear
- [x] Ensure that the docket number that you noted earlier for the paper petitioner is available on this print paper service screen.
- [x] Ensure that the docket number for the electronic petitioner is NOT available on this print paper service screen
- [x] First page is mostly blank with the petitioners address for the envelope window
- [x] Next is the Notice Setting Case for Trial
- [x] After the Notice Setting Case for Trial, there should be the appropriate clinic letter that was loaded in the Denver, CO repository for Regular proceeding types.
- [x] After the Clinic Letter, it should have the Standing Pre-Trial Order, and then the Petitioners Checklist, and finally the Pretrial Memorandum.
- [x] Continue to scroll through the Print for Paper service page, and ensure that the appropriate clinic letter is appended after the Notice Setting Case for Trial Page

**4.  Notice Setting Case for Trial is added to the Docket Record. When opened, the appropriate Clinic Letter is appended to the end of the Notice.**
- Continuing from Test Case 3
- Click "Done" on the Print Paper Service Screen
- Click on the Open tab
- Find the Trial Session that you created in Test Case 3 for Denver, CO
- Click on the link for "Denver, Colorado" to open the session
- Click on the Docket number for a few of the cases (I opened in a new tab for each one)
- Click on the Notice of Trial link

Expected Results

- [x] On the Document View page, if you scroll down, the appropriate Clinic letter should be appended to the end of the Notice.
- [x] No separate entry exists on the docket record for the Clinic Letter

**5. Represented petition is calendared for a trial session with a Trial Location that has one or more clinic letters available; notice setting case for trial is generated; notice document has no clinic letter appended**
- Ensure that there are two clinic letters in the repository for New York City, New York. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-new-york-city-new-york-small_ and _clinic-letter-new-york-city-new-york-regular_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Regular
     - Proceeding type = In Person
     - Location = New York City, New York
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "New York City, New York" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that the cases you select have petitioners that ARE represented by counsel.)
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results

- [x] Green banner indicating that the Eligible cases set for trial
- [x] No "print for paper service screen" appears (since you only selected cases that were represented)
- [x] When reviewing a case that is on the eligible case list (I opened in a new tab), the Notice is on the docket record.
- [x] When opening the Notice on the docket record, there will NOT be any clinic letter appended to the Notice.


**6. Hybrid Trial Session is calendared, has both small and regular proceeding types for Pro Se Petitioners and Represented Petitioners, notice setting case for trial is generated; notice documents have appropriate clinic letter appended as final pages of document, depending on the proceeding type.**
- Using the clinic letters you uploaded for test case 5:
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Hybrid
     - Proceeding type = In Person
     - Location = New York City, New York
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "New York City, New York" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that the cases you select are both S and regular cases, and be sure that you select some cases that are Pro se and some that are represented)
- Write down the docket number of a Pro se (small) case that is paper
- Write down the docket number of a Pro se (Regular) case that is paper
- Write down the docket number of a represented case
- Write down the docket number of a Pro se (small) case that is electronic.
- Write down the docket number of a Pro se (regular) case that is electronic.
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results

- [x] The Print for Paper Service page will appear
- [x] Ensure that the docket number that you noted earlier for the small case paper petitioner is available on this print paper service screen, and has the appropriate clinic letter
- [x] Ensure that the docket number that you noted earlier for the regular case paper petitioner is available on this print paper service screen, and has the appropriate clinic letter
- [x] Ensure that the docket number for the electronic petitioner is NOT available on this print paper service screen
- [x] Ensure that the docket number for the represented petitioner is NOT available on this print paper service screen
- [x] First page is mostly blank with the petitioners address for the envelope window
- [x] Next is the Notice Setting Case for Trial
- [x] After the Notice Setting Case for Trial, there should be the appropriate clinic letter that was loaded in the repository for New York City, New York
- [x] After the Clinic Letter, it should have the Standing Pre-Trial Order, and then the Petitioners Checklist, and finally the Pretrial Memorandum.
- [x] Continue to scroll through the Print for Paper service page, and ensure that the appropriate clinic letter is appended after each of the Notice Setting Case for Trial Pages


**7. Appropriate Notice Setting Case for Trial is added to the Docket Record, depending on which proceeding type the case is in a hybrid trial session. When opened, the appropriate Clinic Letter is appended to the end of the Notice. No Notice is appended for represented Petitioners in a hybrid trial session**
- Continuing from Test Case 6
- Click "Done" on the Print Paper Service Screen
- Click on the Open tab
- Find the Trial Session that you created in Test Case 6 for New York City, New York
- Click on the link for "New York City, New York" to open the session
- Click on the Docket number for the cases that you wrote down in the previous test case (I opened in a new tab for each one)
- Click on the Notice of Trial link on the docket record

Expected Results

- [x] On the Document View page, if you scroll down, the appropriate Clinic letter should be appended to the end of the Notice.
- [x] For the docket number that you noted earlier for the small case paper petitioner, ensure that the Notice of trial has the small case clinic Letter appended 
- [x] For the docket number that you noted earlier for the regular case paper petitioner, ensure that the Notice of trial has the regular case clinic Letter appended 
- [x] For the docket number that you noted earlier for the small/regular case electronic petitioner, ensure that the Notice of trial has the appropriate small/regular case clinic Letter appended 
- [x] For the docket number for the represented petitioner, ensure that there is NOT a clinic letter appended to the Notice of trial on the docket record.
- [x] No separate entry exists on the docket record for the Clinic Letter

**8. Clinic letter for location is updated in repository; new pro se petition is calendared for trial; notice setting case for trial is generated with appropriate clinic letter appended as final pages of document**
- Using the Clinic Letters that you uploaded for Test Case 1 and 3 (Denver, Co):
- Replace the small clinic letter with a new version
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - Be sure that it is in this format: _clinic-letter-denver-colorado-small_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Small
     - Proceeding type = In Person
     - Location = Denver, CO 
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "Denver, Colorado" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that these petitioners are not represented by counsel.)
- Be sure that some of the petitioners have paper service. Take note of the specific docket numbers.
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results:

- [x] The Print for Paper Service page will appear
- [x] After the Notice Setting Case for Trial, there should be the appropriate updated clinic letter that was loaded in the Denver, CO repository for Small proceeding types.

- Next, Click Done
- Navigate to the docket number of one of the pro se petitioners that you wrote down in the previous steps.
- Open the Notice of trial on the docket record

Expected Results:

- [x] The updated clinic letter for Denver, CO small case proceeding types is appended to the end of the notice.

**9. Regular Trial Session is calendared, has cases that have multiple paper service Pro Se Petitioners (ex: petitioner and spouse) with the same address. Petitioners are NOT represented by counsel. Two printed notice setting case for trial are generated; notice documents have the appropriate clinic letter appended as final pages of documents, and there is only 1 NTD that is on the docket record that has the appropriate clinic letter appended to the final pages.**
- Ensure that there are two clinic letters in the repository for Denver, CO. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-denver-colorado-small_ and _clinic-letter-denver-colorado-regular_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Regular
     - Proceeding type = In Person
     - Location = Denver, CO 
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "Denver, Colorado" to open the trial session
- Click the checkboxes for cases that have multiple petitioners in the Eligible case list as QC Complete. (Be sure that these petitioners are not represented by counsel, and be sure that both petitioners have the same address - you can open up the cases to double check. Once you are in the case, click on the case information tab, and then on Parties.)
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results:

- [x] The Print for Paper Service page will appear
- [x] There will be  2 NTD for the case that has multiple petitioners with the same address
- [x] First page is mostly blank with the petitioners address for the envelope window
- [x] Next is the Notice Setting Case for Trial
- [x] After the Notice Setting Case for Trial, there should be the appropriate clinic letter that was loaded in the Denver, CO repository for Regular proceeding types.
- [x] After the Clinic Letter, it should have the Standing Pre-Trial Order, and then the Petitioners Checklist, and finally the Pretrial Memorandum.


**10. Regular Trial Session is calendared, has cases that have multiple Petitioners (ex: petitioner and spouse) with the same address. Both petitioners are represented by counsel. Notice document generated on the docket record does NOT have a clinic letter appended.**
- Ensure that there are two clinic letters in the repository for New York City, New York. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-new-york-city-new-york-small_ and _clinic-letter-new-york-city-new-york-regular_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Regular
     - Proceeding type = In Person
     - Location = New York City, New York
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "New York City, New York" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that the cases you select have multiple petitioners that have the same address and they are both represented by counsel. You can open up a case to ensure that the petitioners have the same address by clicking on case information and then the parties tab.)
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results

- [x] Green banner indicating that the Eligible cases set for trial
- [x] No "print for paper service screen" appears (since you only selected cases that were represented)
- [x] When reviewing a case that is on the eligible case list (I opened in a new tab), the Notice is on the docket record.
- [x] When opening the Notice on the docket record, there will NOT be any clinic letter appended to the Notice.

**11. Regular Trial Session is calendared, has cases that have multiple Petitioners (ex: petitioner and spouse) with the same address. One of the petitioners is represented by counsel, the other is NOT, and has paper service. The printed notice setting case for trial is generated for the unrepresented petitioner, and the NTD on the docket record has a clinic letter appended to the end of the document**
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Regular
     - Proceeding type = In Person
     - Location = New York City, New York
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "New York City, New York" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that the cases you select have multiple petitioners that have the same address, but only ONE petitioner is represented by counsel, and the other petitioner has Paper service. You can open up a case to ensure that the petitioners have the same address by clicking on case information and then the parties tab. If there isn't a case that is set up like this already, you might need to set this up manually by logging in as a docket clerk, clicking on case information tab, then parties, and then editing the Petitioner information)
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results
- [ ] The "print for paper service screen" appears for the one petitioner on the case that was not represented
- [ ] When reviewing a case that is on the eligible case list (I opened in a new tab), the Notice is on the docket record.
- [ ] When opening the Notice on the docket record, there will be a clinic letter appended to the Notice.

**12. Small Trial Session is calendared, has cases that have multiple paper service Pro Se Petitioners (ex: petitioner and spouse) with different addresses. Petitioners are NOT represented by counsel. Two printed notice setting case for trial documents are generated; notice documents have the appropriate clinic letter appended as final pages of document, and the NTD that is on the docket record has the appropriate clinic letter appended to the final pages.**
- Ensure that there are two clinic letters in the repository for Denver, CO. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-denver-colorado-small_ and _clinic-letter-denver-colorado-regular_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Small
     - Proceeding type = In Person
     - Location = Denver, CO 
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "Denver, Colorado" to open the trial session
- Click the checkboxes for cases that have multiple petitioners in the Eligible case list as QC Complete. (Be sure that these petitioners are not represented by counsel, and be sure that both petitioners have different addresses - you can open up the cases to double check. Once you are in the case, click on the case information tab, and then on Parties. If needed, you may have to manually set this up by logging in as a docket clerk, clicking on case information, and then the Parties tab.  Click the edit button to edit the petitioners information.)
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results:

- [x] The Print for Paper Service page will appear
- [x] Ensure that there are two separate NTD for the case, one for each petitioner since they have different addresses
- [x] First page is mostly blank with the petitioners address for the envelope window
- [x] Next is the Notice Setting Case for Trial
- [x] After the Notice Setting Case for Trial, there should be the appropriate clinic letter that was loaded in the Denver, CO repository for small proceeding types.
- [x] After the Clinic Letter, it should have the Standing Pre-Trial Order for Small Tax Cases, and then the Petitioners Checklist, and finally the Pretrial Memorandum.


**13. Small Trial Session is calendared, has cases that have multiple Petitioners (ex: petitioner and spouse) with the different address. Both petitioners are represented by counsel. Notice document generated on the docket record does NOT have a clinic letter appended.**
- Ensure that there are two clinic letters in the repository for New York City, New York. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-new-york-city-new-york-small_ and _clinic-letter-new-york-city-new-york-regular_
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Small
     - Proceeding type = In Person
     - Location = New York City, New York
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "New York City, New York" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that the cases you select have multiple petitioners that have different addresses and they are both represented by counsel. You can open up a case to ensure that the petitioners have the different addresses by clicking on case information and then the parties tab. If needed, you may have to manually set this up by logging in as a docket clerk, clicking on case information, and then the Parties tab.  Click the edit button to edit the petitioners information.)
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results

- [x] Green banner indicating that the Eligible cases set for trial
- [x] No "print for paper service screen" appears (since you only selected cases that were represented)
- [x] When reviewing a case that is on the eligible case list (I opened in a new tab), the Notice is on the docket record.
- [x] When opening the Notice on the docket record, there will NOT be any clinic letter appended to the Notice.


**14. Small Trial Session is calendared, has cases that have multiple Petitioners (ex: petitioner and spouse) with different addresses. One of the petitioners is represented by counsel, the other is NOT. The printed notice setting case for trial is generated for the unrepresented petitioner, and the NTD on the docket record has the appropriate clinic letter appended to the end of the document.**
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session" button
- Fill out the required fields on the Session information screen
- Be sure that you fill in these specifically: 
     - Session Scope = Location Based
     - Session type = Small
     - Proceeding type = In Person
     - Location = New York City, New York
- Fill in the Session Assignments (Judge, Chambers Phone #, Trial Clerk)
- Click "Add Session" button
- Click on the "New" Tab
- Click on the URL for "New York City, New York" to open the trial session
- Click a handful of checkboxes in the Eligible case list as QC Complete. (Be sure that the cases you select have multiple petitioners that have different addresses, but only ONE petitioner is represented by counsel. You can open up a case to ensure that the petitioners have different addresses by clicking on case information and then the parties tab. If there isn't a case that is set up like this already, you might need to set this up manually by logging in as a docket clerk, clicking on case information tab, then parties, and then editing the Petitioner information)
- Click "Set Calendar" Button
- Click "Yes, Set Calendar" on the pop-up

Expected Results

- [x] The Print for Paper Service page will appear
- [x] Ensure that there is a NTD for the unrepresented petitioner since they have different addresses
- [x] Ensure that there is NOT a printed NTD for the represented petitioner.
- [x] First page is mostly blank with the petitioners address for the envelope window
- [x] Next is the Notice Setting Case for Trial
- [x] After the Notice Setting Case for Trial, there should be the appropriate clinic letter that was loaded in the New York City, New York repository for small proceeding types.
- [x] After the Clinic Letter, it should have the Standing Pre-Trial Order for Small Tax Cases, and then the Petitioners Checklist, and finally the Pretrial Memorandum.
- [x] When reviewing a case that is on the eligible case list (I opened in a new tab), the Notice is on the docket record.
- [x] When opening the Notice on the docket record, there will be the appropriate clinic letter appended to the Notice.

**Comment by TomElliottFlexion** [comment]
Clarified logic: Each pro se, paper-service petitioner on a case gets a clinic letter appended to their NTD. If any petitioner on the case needs a clinic letter, then the copy of the NTD on the docket record should have that clinic letter appended to it.

**Comment by codyseibert** [comment]
@ttlenard test case 11 seems incorrect.  It says setup a case and keep one petitioner as paper.  This would mean we should see some type of print paper service page, but the expected results say it should show a green success message which seems incorrect to me.

**Comment by ttlenard** [comment]
@codyseibert I think you are correct.  Sorry about that!  I'll get test case 11 updated.

**Comment by cholly75** [comment]
Spoke w/ @TomElliottFlexion - NTD is not appending clinic letters for efilers. PO feedback delivered.

**Comment by ttlenard** [comment]
FYI - I did a few load tests with over 100 cases calendared.  The biggest trial session I created had 123 cases.  It completed in 11:20.  Big trial sessions seem ok!
