### ISSUE TITLE
BUG: Document filed in error cannot be served; needs to be stricken

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8178]
**Describe the Bug**

A document was filed in production that has become inoperable. See below for specific replication steps.

They wish to strike the document, but In order to strike the document, I believe they have to serve it. And they cannot serve it due to the JS error.

We did see some errors in the logs when they attempted service on the document. Those are shared below.

This was the original report that was submitted from Docket:

> In docket no. 5050-19 entry ustaxcourt/ef-cms-flexion#56, the proposed trial exhibits need to be stricken off the record. When I tried to serve the document an Error 400 message came up & then I tried to strike the document but it will not let me. I can't edit the document at all.  A docket clerk filed the document under the wrong title, I tried to change the title using misc. then it would not let me do anything else to the entry. 
> 
> I refiled the document the correct way now I just need entry ustaxcourt/ef-cms-flexion#56 stricken from the record.

After talking more with Docket, here is the play-by-play of what happened:
- A judge sent a docket clerk a message with an attached document - this was the Proposed Trial Exhibits
- Docket opened the message, and clicked "Add to docket record". Since the document was added via PDF upload originally, the option for **Proposed** Trial exhibits was not available on the document type dropdown.  Instead, they selected the document type of "Trial Exhibits" from the dropdown list, and clicked save Entry.
- Next, upon review, they realized that having the document type of "Trial Exhibits" was incorrect, since the trial had not occurred yet.  Since "Proposed Trial Exhibits" wasn't in the dropdown list, they needed to file it differently.
- Docket clicked the Edit button on the docket record, and switched the Trial Exhibits document type to "Miscellaneous", and clicked Save.
- At this step, there is no edit button on the docket record for this record anymore.  To access the document, you have to go back into the Message to open it.  
- They attempted to serve the document, but when clicking the serve button from the document view area from the message screen, they continued to receive a 400 error (as shown in the kibana logs).
- Since the document cannot be served, there is no way to strike the document, as it appears that you have to have a served document in order to strike it?  (Would like to confirm this...)
- Ultimately docket re-filed the document under the correct document type code, **so all that is needed is that docket index ustaxcourt/ef-cms-flexion#56 needs to be stricken from the record.  The court would prefer NOT to have to serve this errant document and then Strike it if possible.  Court would also like to know if we can just manipulate the data on the back end to show Document Stricken = Y, without unwanted side effects?**

Errors [via Kibana](https://search-info-4vkmt6q7gikrqmth5bknb4mj6u.us-east-1.es.amazonaws.com/_plugin/kibana/goto/4a415e097bfbb5f515523e359d956042)

```
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at completeWorkItem (/var/task/api.js:519465:10)
    at Object.exports.serveCourtIssuedDocumentInteractor (/var/task/api.js:519593:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async genericHandler.logResults (/var/task/api.js:550705:14)
    at async /var/task/api.js:551971:23
    at async exports.handle (/var/task/api.js:552623:20)
    at async /var/task/api.js:552072:22
```

Goal is to understand how the document got into this state and address so that it can't happen in the future.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

Prod, MIG

**Who were you logged in as?**

Docket

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
- Log in as a docket clerk
- Navigate to case 5050-19 (or any case, but this is the one that this issue happened with)
- Click on the Create button, and select PDF upload
- Upload a document
- Next, click on Create, and select "Message"
- Send a message to yourself (I was logged in as docketclerk1 - so I just sent the message to myself). Be sure that you attach the PDF upload that you just added to the case to the message.
- Access the new message in your DAWSON inbox
- Click on the "Add docket entry" option on the top blue bar of the document preview screen
- On the edit Docket Entry screen, Select "Trial Exhibits" from the document type dropdown
- Click Save Entry
- Navigate to the docket record, click on the Edit link for this docket entry
- Change the document type to "Miscellaneous" 
- Click Save
- Notice that on the docket record, the date of filing has disappeared, and the edit button is missing on the far right of the docket index. 
- go back to your message, and you can access the document here, or you can click on the URL of the document from the docket record.  There is a "Serve" link at the top of the document. Click "Serve", and confirm Service.
- A 400 error will appear, and you are unable to serve the document.

**Expected Behavior**

They should be able to serve the document and then strike it. 

**Actual Behavior**

Attempting to serve the document results in a 400 error.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

A work item appears to be required for this service to happen, but the work item has gone away.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
I went down some rabbit holes with this one, because this all started with a docket entry that was filed in error. This bug in particular is that the document cannot be served - they keep getting a 400 error for this, and this is preventing them from being able to serve the document and then strike it from the record.

This led me to looking over this workflow as a whole. "What happens if a court employee makes a mistake with the way that they add a document to the docket record into a case in DAWSON, and they catch the mistake BEFORE they serve it?  How do they "correct" it?"  After some research, it seems that the only way to strike the document from the record is to first serve it, and then immediately strike it from the record.   I am wondering if the court would need a workflow that allows a docket clerk to strike a document from the record before it is served?  I emailed docket to ask about this, awaiting a response.

Here are some older stories/bugs that I found that helped me in my research of this bug and this additional workflow question regarding striking of documents:

[5676](https://github.com/flexion/ef-cms/issues/5676)
[8926](https://github.com/flexion/ef-cms/issues/8926)
[8097](https://github.com/flexion/ef-cms/issues/8097)
[7652](https://github.com/flexion/ef-cms/issues/7652)
[7787](https://github.com/flexion/ef-cms/issues/7787)
[7506](https://github.com/flexion/ef-cms/issues/7506)
[6818](https://github.com/flexion/ef-cms/issues/6818)
[6713](https://github.com/flexion/ef-cms/issues/6713)
[6697](https://github.com/flexion/ef-cms/issues/6697)
[5525](https://github.com/flexion/ef-cms/issues/5525)
[3914](https://github.com/flexion/ef-cms/issues/3914)

**Comment by rosiehsmith** [comment]
The source of this appears to be updating a docket entry from an unservable document type (TE) to a servable document type (MISC), since TE will not create a work item, thus when trying to serve the updated MISC it has no work item associated and fails to serve it. Waiting for more info from [Docket](https://flexion.slack.com/archives/CD4PNKEPK/p1645561917388049) on the preferred direction - either enable unservable to servable conversion OR remove ability to convert unservable to servable.

**Comment by ttlenard** [comment]
Note: We had a second report of this occurring today.  The case that this happened to was 27243-15 (index 119) as reported in ZenDesk Ticket 11690. Guidance from the court was for the docket clerk to re-upload the Trial exhibit, and leave the "bad" entry on the docket record for when the issue described by Rosie (above) is figured out.  Wanted to be sure that I documented that this happened again in this ticket, so that we can trace it.
