### ISSUE TITLE
Docket Clerk: Identify Consolidated Cases in QC Display

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8189]
As a docket clerk, so that I can tell if a document needing QC is a part of a consolidated group, I need to be able to identify consolidated Lead and member cases quickly from the QC display.

Currently, consolidated case QC items display as separate unconnected entities on the Section and user QC displays. In order to facilitate work assignment more quickly and allow clerks to work more efficiently, we would like to call out the consolidated status of cases that appear on the QC display for docket clerks.

When QC items are displayed for sections or users, they are accompanied by the docket number to which that entry is attached; however, there is no indication on the QC display whether that docket is part of a consolidated group. Feedback from court users has indicated that being able to discern at a glance whether an entry pertains to a consolidated group would be helpful in assigning work and organizing the user's work. Currently a user must click into a QC item to determine whether or not the entry is for a case that is part of a consolidated group.

We would like to indicate visually on aggregate QC views whether a particular docket number is the Lead Case in or a member of a consolidated group.

## Acceptance Criteria
* Visual cues for Lead Case and member case of group are distinctive and different from each other
* Section Document QC views visually indicate in the Docket No. column along with the docket number when a case is the Lead Case in a consolidated group
* Section Document QC views visually indicate in the Docket No. column along with the docket number when a case is a member of a consolidated group
* User QC views visually indicate in the Docket No. column along with the docket number when a case is the Lead Case in a consolidated group
* User QC views visually indicate in the Docket No. column along with the docket number when a case is a member of a consolidated group
* This applies across all views for Document QC (Inbox, In Progress, Processed).

## Notes
- Use the same iconography employed in ustaxcourt/ef-cms#8193

## Test Cases
* External document is filed in a case that is a Lead Case in a consolidated group; QC entry displays w/ visual cue indicating Lead Case status on Section Document QC view. QC item is assigned to docket clerk; QC entry displays w/ visual cue indicating Lead Case status on user's personal Document QC view.
* External document is filed in a case that is a member (not Lead) case in a consolidated group; QC entry displays w/ visual cue indicating membership in consolidated group on Section Document QC view. QC item is assigned to docket clerk; QC entry displays w/ visual cue indicating Lead Case status on user's personal Document QC view.
* External document is filed in a case that is neither a Lead Case nor a member case in a consolidated group; QC entry displays w/ no additional visual cue on Section Document QC view. QC item is assigned to docket clerk; QC entry displays w/ visual cue indicating Lead Case status on user's personal Document QC view.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
## Test Cases

#### 1) External document is filed in a case that is a Lead Case in a consolidated group; QC entry displays w/ visual cue indicating Lead Case status on Section Document QC Inbox view. 

This test requires some set up:
- Log in as a docket clerk
- Navigate to a Lead case in a consolidated group (I used 22447-16)
- Click on Case information, and then Parties tab
- Add a Practitioner that you have access to (I added PT4444 - privatePractitioner6)
- Log out as the Docket clerk, and log in as the Practitioner that you just added
- Navigate to the Lead case (ex. 22447-16), and then click File a Document
- File something into the case
- Log out as Private Practitioner

Now the test is ready:
- Log in as a Docket Clerk
- Click on Document QC Tab
- Click on Section Document QC link
- On the Inbox Tab, scroll down to the bottom of the page and you should see the document that was just filed in the lead case

Expected Results:
- [x] **NEW FUNCTIONALITY** - Lead case icon is present next to the docket number of the Lead case on the Section Document QC inbox tab



#### 2) QC item is assigned to a docket clerk; QC entry displays w/ visual cue indicating Lead Case status on user's personal Document QC Inbox view.

- Continuing from Test Case 1
- Click on the checkbox next to the docket number
- Scroll up to the top of the page and click on the "Assign to" dropdown box
- Select the docket clerk that you are logged in as (you are assigning this QC item to yourself)
- Click on "Switch to My Document QC"

  
Expected Results:
- [x] **NEW FUNCTIONALITY** - Lead case icon is present next to the docket number of the Lead case on the Personal Document QC inbox tab



#### 3) Docket Clerk Completes QC; QC entry displays w/ visual cue indicating Lead Case status on user's personal Document QC Processed view.

- Continuing from Test Case 2
- Click on the Document link of the document from the lead case to QC it.
- Click Complete
- Click on the Processed tab 

Expected Results:
- [x] **NEW FUNCTIONALITY** - Lead case icon is present next to the docket number of the Lead case on the Personal Document QC Processed tab



#### 4) Docket Clerk views completed QC item on Section Document QC Processed tab; visual cue indicating Lead Case Status is present on Section QC Processed view.

- Continuing from Test case 3
- Click on the "Switch to Section Document QC"
- Click on the Processed tab

Expected Results
- [x] **NEW FUNCTIONALITY** - Lead case icon is present next to the docket number of the Lead case on the Section Document QC Processed tab



#### 5) External document is filed in a case that is a Lead case in a consolidated group; Docket clerk saves entry (does not complete); QC entry displays w/ visual cue indicating Lead Case status on Personal Document QC In Progress view.

- Log in as a Docket Clerk
- Navigate to a Lead case in a consolidated group (I used 22447-16)
- Click on the create menu, and select Paper filing
- Upload a document, and fill out the required fields
- Click "Save for later".
- Click on Document QC
- Click on the In Progress tab


Expected Results:
- [x] **NEW FUNCTIONALITY** - Lead case icon is present next to the docket number of the Lead case on the Personal Document QC In Progress tab



#### 6) External document is filed in a case that is a Lead case in a consolidated group; Docket clerk saves entry (does not complete); QC entry displays w/ visual cue indicating Lead Case status on Section Document QC In Progress view.

- Continuing from Test case 5
- Click on the link "Switch to Section Document QC"
- Click on the "In Progress" tab 

Expected Results:
- [x] **NEW FUNCTIONALITY** - Lead case icon is present next to the docket number of the Lead case on the Section Document QC In Progress tab



#### 7) External document is filed in a case that is a member (not Lead) case in a consolidated group; QC entry displays w/ visual cue indicating membership in consolidated group on Section Document QC Inbox view. 

This test requires some set up:
- Log in as a docket clerk
- Navigate to a member case in a consolidated group (I used 22448-16)
- Click on Case information, and then Parties tab
- Add a Practitioner that you have access to (I added PT4444 - privatePractitioner6)
- Log out as the Docket clerk, and log in as the Practitioner that you just added
- Navigate to the member case (ex. 22448-16), and then click File a Document
- File something into the case
- Log out as Private Practitioner

Now the test is ready:
- Log in as a Docket Clerk
- Click on Document QC Tab
- Click on Section Document QC link
- On the Inbox Tab, scroll down to the bottom of the page and you should see the document that was just filed in the member case

Expected Results:
- [x] **NEW FUNCTIONALITY** - Member case icon is present next to the docket number of the Member case on the Section Document QC inbox tab



#### 8) QC item is assigned to docket clerk; QC entry displays w/ visual cue indicating member Case status on user's personal Document QC Inbox view.

- Continuing from Test Case 7
- Click on the checkbox next to the docket number
- Scroll up to the top of the page and click on the "Assign to" dropdown box
- Select the docket clerk that you are logged in as (you are assigning this QC item to yourself)
- Click on "Switch to My Document QC"

  
Expected Results:
- [x] **NEW FUNCTIONALITY** - Member case icon is present next to the docket number of the member case on the Personal Document QC inbox tab



#### 9) Docket Clerk Completes QC; QC entry displays w/ visual cue indicating member Case status on user's personal Document QC Processed view.

- Continuing from Test Case 8
- Click on the Document link of the document from the member case to QC it.
- Click Complete
- Click on the Processed tab 

Expected Results:
- [x] **NEW FUNCTIONALITY** - Member case icon is present next to the docket number of the member case on the Personal Document QC Processed tab



#### 10) Docket Clerk views completed QC item on Section Document QC Processed tab; visual cue indicating member Case Status is present on Section QC Processed view.

- Continuing from Test case 9
- Click on the "Switch to Section Document QC"
- Click on the Processed tab

Expected Results
- [x] **NEW FUNCTIONALITY** - Member case icon is present next to the docket number of the Member case on the Section Document QC Processed tab



#### 11) External document is filed in a case that is a member case in a consolidated group; Docket clerk saves entry (does not complete); QC entry displays w/ visual cue indicating member Case status on Personal Document QC In Progress view.

- Log in as a Docket Clerk
- Navigate to a Member case in a consolidated group (I used 22448-16)
- Click on the create menu, and select Paper filing
- Upload a document, and fill out the required fields
- Click "Save for later".
- Click on Document QC
- Click on the In Progress tab


Expected Results:
- [x] **NEW FUNCTIONALITY** - Member case icon is present next to the docket number of the member case on the Personal Document QC In Progress tab


#### 12) External document is filed in a case that is a member case in a consolidated group; Docket clerk saves entry (does not complete); QC entry displays w/ visual cue indicating member Case status on Section Document QC In Progress view.

- Continuing from Test case 11
- Click on the link "Switch to Section Document QC"
- Click on the "In Progress" tab 

Expected Results:
- [x] **NEW FUNCTIONALITY** - Member case icon is present next to the docket number of the member case on the Section Document QC In Progress tab



#### 13) External document is filed in a case that is neither a Lead Case nor a member case in a consolidated group; QC entry displays w/ no additional visual cue on Section Document QC Inbox view. 

This test requires some set up:
- Log in as a docket clerk
- Navigate to a case that is NOT in a consolidated group 
- Click on Case information, and then Parties tab
- Add a Practitioner that you have access to (I added PT4444 - privatePractitioner6)
- Log out as the Docket clerk, and log in as the Practitioner that you just added
- Navigate to the case, and then click File a Document
- File something into the case
- Log out as Private Practitioner

Now the test is ready:
- Log in as a Docket Clerk
- Click on Document QC Tab
- Click on Section Document QC link
- On the Inbox Tab, scroll down to the bottom of the page and you should see the document that was just filed in the case

Expected Results:
- [x] There will NOT be any sort of consolidated case icon present next to the docket number of the case on the Section Document QC inbox tab



#### 14) QC item is assigned to docket clerk; QC entry displays w/ no additional visual cue on user's personal Document QC Inbox view.

- Continuing from Test Case 13
- Click on the checkbox next to the docket number
- Scroll up to the top of the page and click on the "Assign to" dropdown box
- Select the docket clerk that you are logged in as (you are assigning this QC item to yourself)
- Click on "Switch to My Document QC"

  
Expected Results:
- [x] There will NOT be any sort of consolidated case icon present next to the docket number of the case on the Personal Document QC inbox tab



#### 15) Docket Clerk Completes QC; QC entry displays w/ no additional visual cue on user's personal Document QC Processed view.

- Continuing from Test Case 14
- Click on the Document link of the document from the case to QC it.
- Click Complete
- Click on the Processed tab 

Expected Results:
- [x] There will NOT be any sort of consolidated case icon present next to the docket number of the case on the Personal Document QC Processed tab



#### 16) Docket Clerk views completed QC item on Section Document QC Processed tab; there is no additional visual cue present on Section QC Processed view.

- Continuing from Test case 15
- Click on the "Switch to Section Document QC"
- Click on the Processed tab

Expected Results
- [x] There will NOT be any sort of consolidated case icon present next to the docket number of the case on the Section Document QC Processed tab



#### 17) External document is filed in a case that is neither a lead nor a member case in a consolidated group; Docket clerk saves entry (does not complete); QC entry displays w/ no additional visual cue on Personal Document QC In Progress view.

- Log in as a Docket Clerk
- Navigate to a case that is NOT in a consolidated group 
- Click on the create menu, and select Paper filing
- Upload a document, and fill out the required fields
- Click "Save for later".
- Click on Document QC
- Click on the In Progress tab


Expected Results:
- [x] There will NOT be any sort of consolidated case icon present next to the docket number of the case on the Personal Document QC In Progress tab



#### 18) External document is filed in a case that is neither a lead nor a member case in a consolidated group; Docket clerk saves entry (does not complete); QC entry displays w/ no additional visual cue on Section Document QC In Progress view.

- Continuing from Test case 17
- Click on the link "Switch to Section Document QC"
- Click on the "In Progress" tab 

Expected Results:
- [x] There will NOT be any sort of consolidated case icon present next to the docket number of the case on the Section Document QC In Progress tab


## NEW - ADDED 8/23/2022

#### 19) Docket clerk saves a court issued document (does not serve it) in a lead case in a consolidated group; QC entry displays Lead Case indicator on the My Document QC In progress View and in the Section Document QC in Progress View.
- Log in as a docket clerk
- Navigate to the lead case in a consolidated group
- Upload a PDF
- Click Add Docket Entry
- Fill out the information on the Add docket entry screen
- Click Save Entry
- Navigate to the Document QC tab
- Click on the In Progress tab

Expected Results:
- [x]  The document that you just saved in the lead case of the consolidated group appears in the In Progress tab
- [x]  The lead case indicator is present next to the docket number of the new entry.


#### 20) Docket clerk saves a court issued document (does not serve it) in a member case in a consolidated group; QC entry displays the member case indicator on My Document QC In Progress view and in the Section Document QC in Progress View.
- Log in as a docket clerk
- Navigate to a member case in a consolidated group
- Upload a PDF
- Click Add Docket Entry
- Fill out the information on the Add docket entry screen
- Click Save Entry
- Navigate to the Document QC tab
- Click on the In Progress tab

Expected Results:
- [x]  The document that you just saved in the member case of the consolidated group appears in the In Progress tab
- [x]  The member case indicator is present next to the docket number of the new entry.


#### 21) Docket clerk saves a court issued document (does not serve it) in a case that is not part of a consolidated group; QC entry displays w/ no additional visual cue on My Document QC In Progress view and in the Section Document QC in Progress View.
- Log in as a docket clerk
- Navigate to a case that is NOT part of a consolidated group
- Upload a PDF
- Click Add Docket Entry
- Fill out the information on the Add docket entry screen
- Click Save Entry
- Navigate to the Document QC tab
- Click on the In Progress tab

Expected Results:
- [x]  The document that you just saved appears in the In Progress tab
- [x]  There is NO consolidated case indicator present next to the docket number of the new entry.

#### 22) Docket clerk serves a court issued document in a lead case in a consolidated group; QC entry displays Lead Case indicator on the My Document QC Processed View and in the Section Document QC Processed View.
- Log in as a docket clerk
- Navigate to the lead case in a consolidated group
- Upload a PDF
- Click Add Docket Entry
- Fill out the information on the Add docket entry screen
- Click Save and Serve
- Select all the cases in the CG on the new modal pop-up
- Serve the document to all the cases
- Navigate to the Document QC tab
- Click on the Processed tab

Expected Results:
- [x]  The document that you just saved in the lead case of the consolidated group appears in the Processed tab, and there should also be multiple cases listed with this document since all of the cases were selected in the group.
- [x]  The lead case indicator is present next to the docket number of the lead case.
- [x]  The member case indicator should be present next to the docket numbers of all the member cases in the group.

#### 23) Docket clerk serves a court issued document in a member case in a consolidated group; QC entry displays the member case indicator on My Document QC Processed view and in the Section Document QC Processed View.
- Log in as a docket clerk
- Navigate to a member case in a consolidated group
- Upload a PDF
- Click Add Docket Entry
- Fill out the information on the Add docket entry screen
- Click Save and Serve
- Confirm service
- Navigate to the Document QC tab
- Click on the Processed tab

Expected Results:
- [x]  The document that you just saved in the member case of the consolidated group appears in the Processed tab.
- [x]  The member case indicator is present next to the docket number of the case.


#### 24) Docket clerk serves a court issued document in a case that is not part of a consolidated group; QC entry displays w/ no additional visual cue on My Document QC Processed view and in the Section Document QC Processed View.
- Log in as a docket clerk
- Navigate to a case that is NOT part of a consolidated group
- Upload a PDF
- Click Add Docket Entry
- Fill out the information on the Add docket entry screen
- Click Save and Serve
- Confirm service
- Navigate to the Document QC tab
- Click on the Processed tab

Expected Results:
- [x]  The document that you just saved  appears in the Processed tab.
- [x]  There is no consolidated case indicator present next to the docket number of the case.

**Comment by liadmccabe** [comment]
@rgoshen i'm passing this back because although technically it passes the test without UX issues related to the icons themselves showing, I'd like to note that there are some gold icons that should be blue that show up when logged into the practitioner account.  An example is log into Practitioner6 and go to 22447-6 under 'Open Cases' Tab (see screenshot). ![Screen Shot 2022-08-11 at 3.47.51 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/7d82871d-a6ec-4bc1-ab95-8d5fa74e8d49)

**Comment by ttlenard** [comment]
@rgoshen

During testing, it appears that for court issued documents that a docket clerk saves, the icons are displaying correctly on the In progress tab, but if Docket files and serves the document, the consolidated icons aren't showing up on the Processed tab.  

I need to add in a few more test cases in this story to account for Docket Clerks processing internal court documents, and how they display on the In Progress and Processed tab. I will add those test cases in now.

**Comment by ttlenard** [comment]
@rgoshen The Consolidated case icons are not showing up on the Processed tab if you save an entry first.    This came up because I actually did test case 19, and then I went back and served that document that I first saved. Here are the steps to recreate the issue.

- Upload a pdf to a lead case in a consolidated group
- Click add docket entry
- SAVE the entry, do not save and serve
- The entry will be displayed correctly on the in progress tab of document QC
- Go back to the docket record of the case
- Click on the document link from the docket record
- Click Serve from the document preview
- Select all cases in the group
- Serve the doc
- Navigate to the processed tab - the icons will not be present.
- Not sure if this is a different issue, but the document is also not listed on the Section Document QC tab if it is first saved.

**Comment by ttlenard** [comment]
Hey there @rgoshen, I talked with Chris and for now, let's not worry about the last bullet from my comment above. It does appear to be a separate issue.  We'll tackle it with a separate story/bug.

**Comment by rgoshen** [comment]
Found an issue with court issued documents uploaded by petitions clerk.  Therefore, we are moving it back into progress.  When served, it will not show up in served tab within QC Documents.  It does show up under the Processed tab in QC Document when a Docket Clerk is logged in.
