### ISSUE TITLE
Updates to Create/Edit Trial Session Info Pages (Est. End Date/Styling)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8194]
As a court, so that I can manage resources and schedules for employees and parties, I want to be able to enter and view an Estimated End Date for a Trial session.

Currently although clerks can enter a start date for a trial, the trials themselves can be of varying length. In order to manage schedules for judges, clerks, courthouses, etc. and understand the expected duration of any given trial session, we would like the ability to enter an Estimated End Date when creating a new Trial Session or editing an existing Trial Session. We would also like the Estimated End Date to display on the Trial Sessions view.

Following discussion w/ team and UX, we would also like to incorporate some minor styling changes into the Create/Edit Trial Session pages.

## Acceptance Criteria
* On the Create Trial Session screen, there is a date field w/ calendar picker where the user can enter in the Estimated End Date for the session
* On the Edit Trial Session screen, there is a date field w/ calendar picker where the user can enter in the Estimated End Date for the session
* The Estimated End Date value for a Trial Session is displayed on the New and Open Trial Session screen
* The Estimated End Date value for a Trial Session is displayed on the Session Information screen for a Trial Session
* The Estimated End Date value for a Trial Session is displayed on the Trial Session Copy page
* The Estimated End Date field is labeled as Optional.
* Values in the EED field cannot be prior to the value in the Start Date field or the current date; validation triggered if present upon saving
* Make the following changes to the Create Trial Session/Edit Trial Session pages:
  - Append Start date label with “(MM/DD/YYY)” - same style as “optional” in Time label
  - Reduce width of date field
  - Move Time component up next to Start date
  - Add end date component beneath start date
  - Add hint text of date format inside field for both dates

## Test Cases
* User creates Trial Session and enters in an Estimated End Date; EED entered displays appropriately along with the other Trial Session info on the Trial Sessions (New) view; user clicks into Trial Session; Session Information displays EED correctly
* User creates Trial Session w/o Estimated End Date; user edits Trial Session and enters EED; EED entered displays appropriately along with the other Trial Session info on the Trial Sessions (New) view; user clicks into Trial Session; Session Information displays EED correctly
* User creates Trial Session and enters in an Estimated End Date; EED entered displays appropriately along with the other Trial Session info on the Trial Sessions (New) view; session is calendared; EED displays appropriately along with other Trial Session info on the Trial Sessions (Open) view; user clicks into Trial Session; Session Information displays EED correctly

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to the Court's `test` environment for PO Review

**Comment by swongCO** [comment]
![Create trial session.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/affe5099-4ca3-4d62-819b-7928aa539b87)

![Edit trial session.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/701062e7-961c-4f3e-8bbc-86cfeace70f6)
- Append date in blue header to include end date
–––––

![Trial sessions New.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/706e71ed-3eba-4df5-a636-b8bb9d117600)
![Trial sessions Open.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d454a7ef-c759-4564-af10-dcd172ee9606)
- Add a column labeled "Est. End Date" next to Start Date
- New column will display end date in the same format as start date
–––––

![Session info.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/57b2ad6c-92a5-41ba-8528-1b9d44f8e7f3)
- Append date in blue header to include end date
- Add end date to date in Details card
–––––

![Session copy page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d8bff5f1-8aa9-411c-87b0-056b023efd0e)
- Append date in blue header to include end date

**Comment by ttlenard** [comment]
## Test Cases

#### 1) User creates a new Trial Session, new field for Estimated End Date is present. 
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on Add Trial Session

Expected Results
- [x] **NEW FUNCTIONALITY** - Start date field size is smaller
- [x] **NEW FUNCTIONALITY** - MM/DD/YYYY help text is in the Start Date box
- [x] **NEW FUNCTIONALITY** - The Time field has moved so that it is up to the right of the Start Date field
- [x] **NEW FUNCTIONALITY** - The new field Estimated End Date is below the Start date and Time fields
- [x] **NEW FUNCTIONALITY** - The new field for Estimated End date indicates that it is an optional field.

#### 2) User enters in an Estimated End Date; EED entered displays appropriately along with the other Trial Session info on the Trial Sessions (New) view; 
- Continuing from Test Case 1
- Select Location Based
- Enter the start date and time
- Enter the Estimated End Date (be sure that the date is in the future, and greater than or equal to the start date) by either typing in a date in the correct date format, or clicking on the Calendar icon to select a date.

Expected Results
- [x] **NEW FUNCTIONALITY** - Estimated End Date displays appropriately

#### 3) After the Trial Session is created, Estimated End Date displays in new column on the Trial Sessions New Tab
- Continuing from Test Case 2
- Fill in the rest of the required fields for creating a new trial session, and click "Add Session"
- Navigate to the New tab after the confirmation is received that the new session was added.

Expected Results
- [x] **NEW FUNCTIONALITY** - A new column named "Est. End Date" is now present as the 2nd column on the Trial Session New tab
- [x] **NEW FUNCTIONALITY** - Date format for the Estimated End Date is the same as Start Date.


#### 4) User clicks into the new Trial Session; Session Information displays EED correctly
- Continuing from test case 3
- Click on the City, State link for the trial session that you just created

Expected Results
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present on the Details card of the Session Information Page.
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present in the Blue Banner at the top of the screen, underneath the City, State.


#### 5) User Sets the Calendar with the session that has the EED; EED displays appropriately on Trial Sessions "Open" View.
- Continuing from test case 4
- Click a few boxes for QC Complete
- Be sure that you have a indicated a Judge, Chambers phone number, and the Session Location information (I used Judge Buch and Test Trial Clerk 1 b/c you'll need a judge and trial clerk user that you can log in with in a later test)
- Next, Click on Set Calendar
- Click on Yes, Set Calendar
- Click the Done button on the Print paper service screen if your cases had Parties with paper service.
- Click on the Open tab

Expected Results
- [x] **NEW FUNCTIONALITY** - A new column named "Est. End Date" is now present as the 2nd column on the Trial Session Open tab
- [x] **NEW FUNCTIONALITY** - Date format for the Estimated End Date is the same as Start Date.



#### 6) User clicks on the Trial Session from the Open View, EED displays correctly
- Continuing from test case 5
- Click on the City, State link for the trial session that you just calendared

Expected Results
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present on the Details card of the Session Information Page.
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present in the Blue Banner at the top of the screen, underneath the City, State.



#### 7) Judge, Chambers, Trial Clerk see the EED displayed correctly when viewing the Session 
copy of the trial session
- Log in as the Judge that is assigned to the Trial Session that you calendared from test case 
- Click on the City, State link for the session you just created from the Upcoming Trial Sessions Card, or from the Open Menu (trial clerk)
- Be sure to repeat this test with Buch's Chambers User, and Trial Clerk

Expected Results
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present in the Blue Banner at the top of the screen, underneath the City, State.



#### 8) Judge, Chambers, Trial Clerk see the EED displayed correctly when viewing the "All Session Info"
- Continuing from Test case 7 for each user (Judge, Chambers, Trial Clerk)
- Click on the "View All Session Info" Link at the top of the page

Expected Results
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present on the Details card of the Session Information Page.
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present in the Blue Banner at the top of the screen, underneath the City, State.


#### 9) User enters an EED date that is before the start date, or in the past; receives validation error.
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on Add Trial Session
- Select Location Based
- Enter the start date and time
- Enter the Estimated End Date (be sure that the date is in the past, or before the start date of the Trial Session) by either typing in a date in the correct date format, or clicking on the Calendar icon to select a date.
- Fill in the rest of the required fields for creating a new trial session, and click "Add Session"

Expected Results
- [x] **NEW FUNCTIONALITY** - Validation error in red that states "Enter a valid Estimated End Date"
- [x] **NEW FUNCTIONALITY** - Red vertical bar next to the Estimated End Date field with the validation error below it that states "Enter a valid Estimated End Date"


#### 10) User creates Trial Session w/o Estimated End Date; should not receive any validation error.
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on Add Trial Session
- Select Location Based
- Enter the start date and time
- DO NOT enter any data in the Estimated End Date field - Leave this field blank.
- Fill in the rest of the required fields for creating a new trial session, and click "Add Session"
- Navigate to the New tab after the confirmation is received that the new session was added.

Expected Results
- [x] There should not be any requirement or validation error that the EED was required, and the session should have been created successfully without a date in the EED field.



#### 11) User Edits Trial Session, adds an EED; Session saves and EED displays appropriately
- Continuing from test case 10
- Click on the City, State link for the trial session that you just calendared
- Click the Edit link next to the Session Information header
- Enter the Estimated End Date (be sure that the date is in the future, and greater than or equal to the start date) by either typing in a date in the correct date format, or clicking on the Calendar icon to select a date.
- Scroll down the page, and click Save

Expected Results
- [x] Green banner that states "Trial Session updated."
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present on the Details card of the Session Information Page.
- [x] **NEW FUNCTIONALITY** - The Est. End Date is now present in the Blue Banner at the top of the screen, underneath the City, State.

**Comment by liadmccabe** [comment]
Recommendation: Update text for "Estimated End Date" to sentence case "Estimated end date" to stay consistent with the other headers. 

While we were testing this, we ran into some errors that we discovered were not tab-able and not read by the mac voice-over utility, which is not 508 compliant. PO has been informed.

**Comment by shumway-tm** [comment]
Talked with Lia and Chris Holly. Fixing the non tab-able errors will be addressed in a broader effort in the future.

**Comment by liadmccabe** [comment]
Findings from UX Review: 

1) During UX review, we found that the Trial Sessions filter does not have "Unassigned" listed as an option on the Judge dropdown selection.  As a result, if you don't have a judge assigned and click to sort by judge, the trial session does not appear.

2) Start time lists itself as optional on the field, however if you don't select anything it still defaults to a 10:00 am time.  Is this actually optional? Or is a time required? Is it better to say updating time is optional rather than time is optional?

3) Under Session Info, down by Eligible Cases, it is currently missing the Consolidation icons.

4) Under Session Info of Upcoming Trial Sessions, View All Session Info, scroll down by "Open Cases, Inactive Cases, and All" cases it is missing the Consolidation Icons.

5) Session Copy page where it shows "Cases by Trial Status" with the filters, missing Consolidation Icons.
