### ISSUE TITLE
Modify Caseless Petitioner 'My Cases' Page

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8198]
As a petitioner, so that I can easily understand court procedure, I need the initial, caseless 'My Cases' page to provide better direction on how to engage with the court.

Currently the court is seeing ~100 duplicate cases/mo. created in DAWSON. The vast majority of these are due to parties signing up for online access after having already sent in their petitions by mail; following the instructions on the 'caseless Welcome' page, they proceed with filing the same petition online, unaware that their mailed petition may have already been processed. This results in administrative work from the court to untangle the duplicates and frustration on the petitioner/counsel behalf in not understanding why they don't see their case immediately when granted eAccess or why they end up with two docket numbers.

Additionally,  we receive ~50 help desk tickets/mo. with questions from petitioners on how to pay their filing fee, who have signed up for eAccess explicitly to pay the fee. Currently on the caseless 'Welcome' page there is no option to pay a filing fee, which consequently also leads to duplicate case filing and petitioner confusion and administrative court work.

The court has requested a few modifications to the caseless view of the 'My Cases' page that displays for new users with no current case assignment in DAWSON to better inform them of the correct procedure and make certain options more prominent.

## Acceptance Criteria
* Petitioner 'My Cases' initial page (the view that displays when a user has **no** cases assigned to them in DAWSON) has the following dismissable block added to the top of the page:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/7d6a4d9c-84c7-487b-9fba-3d5d5fc2aa84) - the email in the text can be encoded as a link to bring up a new email message with the subject line "eAccess to existing case" to the support address.

* Petitioner 'My Cases' initial page (the view that displays when a user has **no** cases assigned to them in DAWSON) has the Filing Fee Options block (see below for screenshot) added to the right nav, second block from the top [this is the same block currently displayed in the nav on the petitioner My Cases view when a petitioner **does** have cases assigned to them]

* Filing Fee Options block has text added to it as in the following screenshot:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/6a864e07-bce8-42ee-8e0b-839e052f44a9). This new text displays everywhere the Filing Fee Options block is currently displayed. NOTE: see UX comment for update to this text which adds an example docket number.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to an environment for Engineering Review so an engineer who didn't work on the story can go through the test cases
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment for review.

**Comment by swongCO** [comment]
Additional enhancements from UX:
* When link for help email is clicked, auto-populate subject as “eAccess to existing case” so sorting/searching is easier for support staff
* For both blocks, add “(e.g. 12345-67)” after ‘docket number’ in the body to inform the user of the format they’re looking for
* Make the title of the dismissible block in sentence case for ease of reading

**Comment by ttlenard** [comment]
## Test Cases

#### 1) "Caseless" Petitioner logs in; New Information card is available at the top of the initial screen that they see.
- Log in as a Petitioner that does not have ANY existing cases in DAWSON.

Expected Results
- [x] **NEW FUNCTIONALITY** - New information card (as shown in above mockup) is available to the Petitioner at the top of the screen
- [x] **NEW FUNCTIONALITY** - Include "(e.g. 12345-67)" after 'docket number' in the body of the message (not shown in mockup above)
- [x] **NEW FUNCTIONALITY** - dawson.suppport@ustaxcourt.gov email in the information card is a clickable link
- [x] **NEW FUNCTIONALITY** - User can dismiss the information card by clicking the "x" in the top corner



#### 2) Caseless Petitioner clicks on the dawson.support@ustaxcourt.gov email; "eAccess to existing case" is auto-populated in the email subject
- Refresh the screen, so that the information card re-appears for the caseless Petitioner
- Click on the dawson.support@ustaxcourt.gov link

Expected Results
- [x] **NEW FUNCTIONALITY** - The subject of the email states, "eAccess to existing case"



#### 3) "Caseless" Petitioner logs in; New Information card for paying the filing fee is now the second card down on the right side of the screen.
- Log in as a Petitioner that does not have ANY existing cases in DAWSON.

Expected Results
- [x] **NEW FUNCTIONALITY** - New Filing Fee information card (as shown in above mockup) is available to the Petitioner and is the second card down from the top on the right hand side of the screen.
- [x] **NEW FUNCTIONALITY** - Include "(e.g. 12345-67)" after 'docket number' in the body of the message (not shown in mockup above)
- [x] Clicking the Pay now link directs the user to the USTC form on pay.gov

#### 4)  Petitioner with cases logs in; Updated Information card for paying the filing fee is now available on the 3rd card down on the right side of the screen.
- Log in as a Petitioner that has at least one electronic case in DAWSON

Expected Results
- [x] **NEW FUNCTIONALITY** -  Updated Filing Fee information card (as shown in above mockup) is available to the Petitioner and is the 3rd card down from the top on the right hand side of the screen.
- [x] **NEW FUNCTIONALITY** - Include "(e.g. 12345-67)" after 'docket number' in the body of the message (not shown in mockup above)
- [x] Clicking the Pay now link directs the user to the USTC form on pay.gov
