### ISSUE TITLE
Printable Trial Session Copy

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8199]
As a Judge, Chambers, or Trial Clerk, in order to keep a paper copy of my trial session worksheet, I need a print optimized view for, er, printing.

Many judges and chambers staff as well as trial clerks like to print out paper copies of their trial sessions for recordkeeping and to take notes on. Currently printing out the session copy from the browser wastes a lot of space and paper, so they would like a print-friendly format available to them.

We would like a print-friendly format available to users for printing the Session Copy, in the same vein as the "Printable Report" version of Reports in DAWSON.

## Acceptance Criteria
* Session Copy page allows user to view and subsequently print a print-optimized version of the current Session Copy view
* Printable version is formatted in black-and-white
* Printable version should display all cases currently showing on the Session Copy page as per selected filters
* Printable version should indicate which filters have been selected
* Printable version should include Trial Session header information and Session Notes
* Printable version should display for each case the docket no., title, petitioner counsel, respondent counsel, PTM indicator, and status 
* User should be able to choose whether to include or exclude Case Notes on the printable version

## Notes
Developers - please invite UX to the first mob to discuss brainstorming ideas

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to an environment for Engineering Review so an engineer who didn't work on the story can go through the test cases
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
## Test Cases


#### 1) Court user assigned to a Trial Session has the option to print Session Copy on the Session copy page.
- Log in as a Judge, CA, or Trial Clerk
- Click on the City, State link for one of your upcoming Trial Sessions

Expected Results:
- [x] New option is available for the Court User (Trial Clerk, CA, or Judge) to print the Session Copy



#### 2) Court user assigned to Trial Session has option to either print the case notes, or print without case notes.
- Log in as a Judge, CA, or Trial Clerk
- Click on the City, State link for one of your upcoming Trial Sessions

Expected Results:
- [x] Option is available to select printing with our without case notes



#### 3) Court user assigned to Trial Session selects the option to print with the case notes; printable Session Copy is formatted correctly.
- Log in as a Judge, CA, or Trial Clerk
- Click on the City, State link for one of your upcoming Trial Sessions
- Select the option to print with casenotes

Expected Results:
- [x] The printable document is print-optimized (minimal white space, formatted for ease of reading, etc.)
- [x] The printable document is in black and white 
- [x] The printable document includes the Trial Session Header and Session Notes
- [x] The printable document displays the Docket Number, Case Title, Petitioner Counsel, Respondent Counsel, PTM indicator, and Case Status
- [x] The printable document indicates that none of the filters were selected
- [x] The printable document displays case notes
- [x] The printable document displays all the cases that were listed on the screen (if there were 100 cases, there should be 100 cases in the printable document)


#### 4) Court user assigned to Trial Session selects the option to print without the case notes; printable Session Copy is formatted correctly.
- Log in as a Judge, CA, or Trial Clerk
- Click on the City, State link for one of your upcoming Trial Sessions
- Select the option to print without casenotes

Expected Results:
- [x] The printable document is print-optimized (minimal white space, formatted for ease of reading, etc.)
- [x] The printable document is in black and white 
- [x] The printable document includes the Trial Session Header and Session Notes
- [x] The printable document displays the Docket Number, Case Title, Petitioner Counsel, Respondent Counsel, PTM indicator, and Case Status
- [x] The printable document indicates that none of the filters were selected
- [x] The printable document does not display any case notes
- [x] The printable document displays all the cases that were listed on the screen (if there were 100 cases, there should be 100 cases in the printable document)


#### 5) Court user assigned to Trial Session selects some filters on the trial session, selects the the option to print with the case notes; printable report only displays cases that were identified in the filtered list.
- Log in as a Judge, CA, or Trial Clerk
- Click on the City, State link for one of your upcoming Trial Sessions
- On the Session copy screen, be sure to select some various values for Trial Status in mulitple cases.
- After you have added various Trial Status' to cases, Uncheck some of the boxes in the "Show Cases by Trial Status" section to filter the list.
- Also, be sure that you have some cases that have case notes
- Select the option to print with case notes.

Expected Results:
- [x] The printable document is print-optimized (minimal white space, formatted for ease of reading, etc.)
- [x] The printable document is in black and white 
- [x] The printable document includes the Trial Session Header and Session Notes
- [x] The printable document displays the Docket Number, Case Title, Petitioner Counsel, Respondent Counsel, PTM indicator, and Case Status
- [x] The printable document indicates that which of the Trial Status filters were selected
- [x] The printable document displays case notes
- [x] The printable document displays all the cases that were filtered and listed on the screen (if there were 55 cases, there should be 55 cases in the printable document)



#### 6) Court user assigned to Trial Session filters the cases on the trial session, selects the the option to print without the case notes; printable report only displays cases that were identified in the filtered list.
- Log in as a Judge, CA, or Trial Clerk
- Click on the City, State link for one of your upcoming Trial Sessions
- On the Session copy screen, be sure to select some various values for Trial Status in mulitple cases.
- After you have added various Trial Status' to cases, Uncheck some of the boxes in the "Show Cases by Trial Status" section to filter the list.
- Also, be sure that you have some cases that have case notes
- Select the option to print without case notes.

Expected Results:
- [x] The printable document is print-optimized (minimal white space, formatted for ease of reading, etc.)
- [x] The printable document is in black and white 
- [x] The printable document includes the Trial Session Header and Session Notes
- [x] The printable document displays the Docket Number, Case Title, Petitioner Counsel, Respondent Counsel, PTM indicator, and Case Status
- [x] The printable document indicates that which of the Trial Status filters were selected
- [x] The printable document does not display the case notes
- [x] The printable document displays all the cases that were filtered and listed on the screen (if there were 55 cases, there should be 55 cases in the printable document)

**Comment by liadmccabe** [comment]
UX Feedback:
We have some feedback on the modal and the verbiage that is used. We recommend rewording phrases like “run report” to be consistent with the terminology being used on different pages/modals (like "Session Copy" instead of "working copy").

**Comment by liadmccabe** [comment]
UX SPECS:

As per discussion with devs, the draft printable trial session copy currently does not provide enough spaces in the header to accommodate the longest combinations of options possible (edge cases).  An example discussed is if the user selected Washington, District of Columbia combined with the date December 25th, 2022, the Judge's name of Gustafson, and the page number. Currently, if all of these options are selected, there is not enough space to contain them all nicely so we have recommended shortening the date in order to accommodate these longer edge cases.

**Comment by swongCO** [comment]
### UX feedback
For the modal:

- [x] change title "Run Printable Trial Session Copy" to "Print Session Copy" (James)
- [x] change “case notes” to “<s>judge’s </s>your case notes” in the body (James)
- [x] change "Run Report" button to "Print" (James)

On the pdf page:
- [x] change the page title from "Trial Session Printable Working Copy" to "Printable   ##Session Copy" (James)
- [x] change the back link "Back to Trial Session Working Copy" to "Back to Session Copy” (James)

On the pdf - trial status filters:
- [x] in the header, shift "Total Shown: XXX" to the right so the right padding is the same as the left padding for "Trial Status Filters Selected" (James)
- [x] remove the extra row of spacing or reduce the spacing between rows in the body (James)
- [x] the five columns should be equal in width:
![equal columns.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/df13ebb8-9ebd-484b-a922-4f20fd0a001b) (James)
- [x] "Taken Under Advisement" can wrap to two lines = taken under / advisement (James)

On the pdf - table:
- [x] “Notes:” should be bolded in the table (James)
- [x] add an underline to the column that is being sorted by (Docket No. or Petitioner Counsel)
- [ ] the page header “Trial Session Copy: San Francisco, California; Oct 17, 2022; Buch” and “Page X of XX” should left and right align with the table:
    OR
- make the left/right margins the same with the page header:
![page header alignment.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/05769f68-cdc7-4b08-b4cc-fd7afc314074)
- [ ] if a bottom row doesn't fit on the page, force it to the next page so that the row isn't split between two pages:

![Screen Shot 2022-10-03 at 2.42.18 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3fb65b63-8258-440a-be0d-69a5e607611a)

![Screen Shot 2022-10-03 at 2.42.52 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/c93a8db4-e446-47ae-ad89-d2f05f0da176)
- [ ] the associated cases in a group are not indicated with anything other than an indent; we had discussed adding the chain/link icon to indicate these but they are not showing up (James)

**Comment by jamesobrooks** [comment]
@swongCO 
> change “case notes” to “judge’s notes” in the body

This view is for Judges, their chambers, and trial clerks. The notes being included are the notes added by the particular user, not specifically the Judge.

**Comment by swongCO** [comment]
@jamesobrooks There are two different types of notes for every case - case and judge's. In the Session Copy, only judge's notes are displayed in the table (they have the generic label "Notes"). Only the judge and their CA can view/edit judge's notes. They can also view/edit case notes. Everyone else, including trial clerks, are able to view/edit case notes only. So we wanted to clarify which type of note will be printed.

**Comment by ttlenard** [comment]
@swongCO @jamesobrooks Wanted to chime in here. There are actually 3 types of case notes. 1) Any court  user can add notes to the case, 2) Judges can add notes to the case in Judges Notes - these notes also appear on the Session Copy page, 3) Trial Clerks can also add notes to the Session Copy page. Their notes do not show up in the Case notes, or in the Judges Notes, they only appear on the Session Copy page for themselves, Judges and the CA do not see the Trial Clerk notes.  I would caution changing the title to "Judges notes" because a trial clerk could have their own notes in there, and that would make it confusing for trial clerks if they print out this page.

I think displaying the user-case-note of the logged in user is probably the most appropriate, and I think that is what James was suggesting???

This is me logged in as a Judge and adding a note. See the UserCaseNote:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1d9cafce-a025-45e7-b049-3604ce5f73e2)

This is me logged in as a trial clerk. See the UserCaseNote:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/3bd8de72-afc9-4e79-847f-6fa9547b6e0e)

Here are the UserCaseNotes for the case in Dynamo.  
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/a872c3e7-cfb4-405a-a188-156bdba1a97b)

Hope this breakdown helps with understanding how all the notes work!  Give me a shout if you need any additional clarification!

**Comment by swongCO** [comment]
Based on Tenille's comment, we'll be changing the feedback to "notes" and removing "judge's".

**Comment by jamesobrooks** [comment]
To be clear, calendar notes and session notes are not to be toggled. If they exist, we include them. So I also don't think that having the modal simply say "notes" will be clear.

P.S. session notes are also user based, but calendar notes are shared.

**Comment by swongCO** [comment]
Updated feedback from a discussion with James, Tenilla and Lia. We will refer to notes as "your case notes" in the body of the print modal.

**Comment by jamesobrooks** [comment]
Task Status:
- the page header “Trial Session Copy: San Francisco, California; Oct 17, 2022; Buch” and “Page X of XX” should left and right align with the table:
OR

This header is displaying differently on different machines locally. Deployed in the environment, it will display the same for all users. Troubleshooting this issue has already taking an inordinate amount of time to this point, and still continues to present an issue. We would suggest deferring this issue until after release to see if user's really want it fixed.

**Comment by ujahio** [comment]
Task Status:

if a bottom row doesn't fit on the page, force it to the next page so that the row isn't split between two pages:

From the findings of our experiment on modifying css classes on table rows rendered on pdf, our efforts have not proven impossible to check the position on the page so we can programmatically render the table row on a new page if the contents of the row extends to the new page. At this point, continuation of the experiment is not proving to be worth the time we've spent.

**Comment by liadmccabe** [comment]
UX Feedback
The table does not currently have a set width, so if a case title has a particularly long name, it expands the table off-screen. This may also be the case for the other columns, such as a respondent or counselor with a long name. 
![Screen Shot 2022-10-07 at 9.41.58 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/97f05c7b-3183-4ec4-9fc4-85935c0eeb42)

This is impacting the printable copy as well.  The table and columns should be a set width to accommodate this, and the content in the columns should wrap. It also appears that it is impacting the size of the text on the print-out- as longer text is added, the smaller the size of the font. 
![IMG_1221.JPG](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cca47b46-7ee0-4020-b8f4-a16c606bbd83)

**Comment by liadmccabe** [comment]
UX Feedback: We recommend making the table as wide as possible to increase the allowable copy space in the Case Title column to accommodate names and avoid wrapping mid-name. The current Case Title column is somewhat narrow and is causing names to be split. (E.g. in the screenshot below you see that the name "Kevin B. Cheam & Julie Lim" both have the 'm' from their last names pushed into the next row.)

![Screen Shot 2022-10-10 at 11.04.38 AM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/0697e16f-0286-4330-99f8-6007f511e72b).

@jamesobrooks @Absolutestunna @shumway-tm

**Comment by ttlenard** [comment]
@jamesobrooks @Absolutestunna @shumway-tm 

Found something while testing today 10/11/22.  Looks like the printed document is displaying the Judges name as the title even when a Trial Clerk is the one printing out the page.
- Log in as a Trial Clerk
- Navigate to a session that you are assigned to
- Print the Session Copy page
- Notice that on the printed version that it says "Judges name - Session Copy" instead of "Trial Clerk Name - Session Copy"
- This should display the trial clerk's name, not the Judges.

Note: When a CA views the page in DAWSON and the print out, it is ok that it says the Judges name. This only needs to be fixed for the Trial Clerk.

Here are some screen grabs:

Notice that I am logged in as the test trial clerk 1 in DAWSON. Check out the Header info:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/df8ee174-fbe5-4c16-9ea9-49d126ded6f7)

When this is printed, it says "Buch - Session Copy"
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cea8a64c-26a4-4b49-8aa1-3a72e6103960)
