### ISSUE TITLE
Add Pretrial Memorandum Column to Session Copy Page

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8200]
As a judge or their chambers staff, so that I know prior to trial whether parties have filed a pretrial memorandum, I need an indicator on the Session Copy page telling me whether a PTM has been filed in a case, and by whom.

After being calendared, if a basis for settlement has not been reached and it appears that a trial is necessary, each party must file a Pretrial Memorandum no later than 21 days before the first day of the trial session. When reviewing their Session Copy for a trial session, in looking at the inventory of cases it would be helpful for judges to know in which cases parties have filed a pretrial memorandum, and which parties those are.

This story will address the addition of a pretrial memorandum column and corresponding data on the Session Copy page.

## Acceptance Criteria
* On the Session Copy page, in the case listing portion of the screen an additional column is present titled "PTM"
* "PTM" column is located between "Respondent Counsel" and "Trial Status"
* In a given case, if a pretrial memorandum (event code: PMT) is present on the docket record, then a value is present in the PTM column for that case:
  - "P" if the PMT has been filed by the Petitioner
  - "R" if the PMT has been filed by the Respondent
  - "B" if there are PMTs from both Petitioner and Respondent on the docket record for the case
  - No value in the column if there are no PMTs on the docket record for the case

## Notes
Available for anyone who has Session Copy

## Test Cases
* Session Copy page displays PTM column in case listing; case(s) where only a petitioner has filed a PTM have a value of "P" in the column; case(s) where only the respondent has filed a PTM have a value of "R" in the column; case(s) where both petitioner and respondent have filed PTMs have a value of "B" in the column; cases where neither petitioner nor respondent have filed PTMs have no value in the column. 
* Session Copy page displays PTM values for calendared cases; PTM is added to a case currently calendared; Session Copy page is refreshed and PTM value is updated 
* Session Copy page displays P/R/B value for calendared case; PTM is stricken from case record; Session Copy page is refreshed and PTM value is updated.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Test cases reviewed by an engineer on a deployed environment for Engineering Review.
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [x] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Session Copy page displays PTM column in case listing with case(s) where only a petitioner has filed a PTM, and the column has a value of "P" in the column for this case(s).

This test case needs some set up:
- Log in as Judge Buch
- Click on a City, State of a trial session from the upcoming Trial Sessions card on your dashboard
- Click on the docket number of a case that is calendared, and look at the docket record to see if a Pre-trial Memorandum has been filed yet, and by whom.
- Take note of the docket number of the case, as you will need this as a reference later.
- If no PMT has been filed by the petitioner, you will need to file one as the Petitioner (be sure that Respondent has NOT filed one either).
- Log in as a docket clerk
- Navigate to the case that you took note of in the previous step
- Click on Create, and then Paper filing
- Upload a document
- Fill out date received, and then select Pretrial Memorandum as the document type
- Select Petitioner(s) as the Filed by
- Click Save and Serve
- Click Yes, Serve
- Print "Done" if the petitioner has paper service

Now the Test is Ready:
- Log in as Judge Buch
- Click on a City, State of the same trial session from the upcoming Trial Sessions card on your dashboard
- Repeat this by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - A new column between the "Respondent" Column and the "Trial Status" Column will be present and is titled PTM.
- [x] **NEW FUNCTIONALITY** - A "P" will be present in the column for the case that the Petitioner filed the Pretrial Memorandum in.



#### 2) Session copy page displays PTM column in case listing with case(s) where only the respondent has filed a PTM and the column has a value of "R" in the column for this case(s). 

This test case needs some set up:
- Log in as Judge Buch
- Click on a City, State of a trial session from the upcoming Trial Sessions card on your dashboard
- Click on the docket number of a case that is calendared (be sure that this is a different case from the one you used in Test Case 1), and look at the docket record to see if a Pre-trial Memorandum has been filed yet, and by whom.
- Take note of the docket number of the case, as you will need this as a reference later.
- If no PMT has been filed by the Respondent, you will need to file one as the Respondent (be sure that Petitioner has NOT filed one either)..
- Log in as a docket clerk
- Navigate to the case that you took note of in the previous step
- Click on Create, and then Paper filing
- Upload a document
- Fill out date received, and then select Pretrial Memorandum as the document type
- Select Respondent as the Filed by
- Click Save and Serve
- Click Yes, Serve
- Print "Done" if the petitioner has paper service

Now the Test is Ready:
- Log in as Judge Buch
- Click on a City, State of the same trial session from the upcoming Trial Sessions card on your dashboard
- Repeat this by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - A new column between the "Respondent" Column and the "Trial Status" Column will be present and is titled PTM.
- [x] **NEW FUNCTIONALITY** - A "R" will be present in the column for the case that the Respondent filed the Pretrial Memorandum in.


#### 3) Session copy page displays PTM column in case listing with case(s) where both petitioner and respondent have filed PTMs and has a value of "B" in the column for this case(s).

This test case needs some set up:
- Log in as a docket clerk
- Navigate to the case that you used in Test case 1
- Click on Create, and then Paper filing
- Upload a document
- Fill out date received, and then select Pretrial Memorandum as the document type
- Select Respondent as the Filed by
- Click Save and Serve
- Click Yes, Serve
- Print "Done" if the petitioner has paper service

Now the Test is Ready:
- Log in as Judge Buch
- Click on a City, State of the same trial session you used for test case 1 from the upcoming Trial Sessions card on your dashboard
- Repeat this by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - A new column between the "Respondent" Column and the "Trial Status" Column will be present and is titled PTM.
- [x] **NEW FUNCTIONALITY** - A "B" will be present in the column for the case that the Respondent filed the Pretrial Memorandum in.


#### 4) Session copy page displays PTM column in case listing with cases where neither petitioner nor respondent have filed PTMs, column has no (P, R, or B) value in the column for the case(s).
- Continuing from Test case 3
- Notice the other cases that are on the case list
- Find a case where there is no P, R, or B present in the column
- Click on the docket number

Expected Results
- [x] There should be no Pretrial Memorandum present on the docket record for this case



#### 5) Session Copy page displays PTM column in case listing with a case where Respondent previously filed the PTM, Petitioner then files a PTM on the case, PTM Column on the Session copy page is updated from R to B.

This test case needs some set up:
- Log in as a docket clerk
- Navigate to the case that you used in Test case 2
- Click on Create, and then Paper filing
- Upload a document
- Fill out date received, and then select Pretrial Memorandum as the document type
- Select Petitioner as the Filed by
- Click Save and Serve
- Click Yes, Serve
- Print "Done" if the petitioner has paper service

Now the Test is Ready:
- Log in as Judge Buch
- Click on a City, State of the same trial session you used for test case 2 from the upcoming Trial Sessions card on your dashboard
- Repeat this entire test by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - A new column between the "Respondent" Column and the "Trial Status" Column will be present and is titled PTM.
- [x] **NEW FUNCTIONALITY** - A "B" will be present in the column for the case that the Petitioner filed the Pretrial Memorandum in.




#### 6) Session Copy page displays PTM values for calendared cases; PTM is added to a case currently calendared; Session Copy page is refreshed and PTM value is updated



#### 7) Session Copy page displays P value for calendared case; PTM is stricken from case record; Session Copy page is refreshed and PTM value is updated.

This test case needs some set up:
- Complete the steps you took from test case 1, be sure that you log in as a judge and verify that the P is displayed on the Session copy of the case you selected before completing this test. (Be sure that you take note of the case that you added the Pretrial Memo to)

Now the Test is Ready:
- Log in as a docket clerk
- Navigate to the case that you uploaded a PTM for a Petitioner when setting this test case up
- Click on the Edit button on the far right of the docket record.
- Click on the Actions Tab
- Type (STRICKEN) in the Action area
- Click on Strike Entry
- Confirm that you want to Strike the entry
- The Pretrial Memo will now show up on the docket record with a line through it.
- Log in as Judge Buch
- Click on a City, State of the same trial session you used in the previous steps from the upcoming Trial Sessions card on your dashboard
- Repeat this entire test by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - On the Session copy page, there should not be a P present in the new PTM column for this case. This column should be empty.


#### 8) Session Copy page displays R value for calendared case; PMT is stricken from case record; Session Copy page is refreshed and PTM value is updated.

This test case needs some set up:
- Complete the steps you took from test case 2, be sure that you log in as a judge and verify that the R is displayed on the Session copy of the case you selected before completing this test. (Be sure that you take note of the case that you added the Pretrial Memo to)

Now the Test is Ready:
- Log in as a docket clerk
- Navigate to the case that you uploaded a PTM in for the Respondent when setting this test case up
- Click on the Edit button on the far right of the docket record.
- Click on the Actions Tab
- Type (STRICKEN) in the Action area
- Click on Strike Entry
- Confirm that you want to Strike the entry
- The Pretrial Memo will now show up on the docket record with a line through it.
- Log in as Judge Buch
- Click on a City, State of the same trial session you used in the previous steps from the upcoming Trial Sessions card on your dashboard
- Repeat this entire test by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - On the Session copy page, there should not be a R present in the new PTM column for this case. This column should be empty.


#### 9) Session Copy page displays B value for calendared case; Petitioner's PMT is stricken from case record; Session Copy page is refreshed and PTM value is updated to R.

This test case needs some set up:
- Complete the steps you took from test case 3, be sure that you log in as a judge and verify that the B is displayed on the Session copy of the case you selected before completing this test. (Be sure that you take note of the case that you added the Pretrial Memo to)

Now the Test is Ready:
- Log in as a docket clerk
- Navigate to the case that you uploaded a PTM in for the Respondent when setting this test case up
- Click on the Edit button on the far right of the docket record on the Pretrial memo that you added for the Petitioner.
- Click on the Actions Tab
- Type (STRICKEN) in the Action area
- Click on Strike Entry
- Confirm that you want to Strike the entry
- The Pretrial Memo will now show up on the docket record with a line through it.
- Log in as Judge Buch
- Click on a City, State of the same trial session you used in the previous steps from the upcoming Trial Sessions card on your dashboard
- Repeat this entire test by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - On the Session copy page, there should only be an R present in the new PTM column for this case. 



#### 10) Session Copy page displays B value for calendared case; Respondent's PMT is stricken from case record; Session Copy page is refreshed and PMT value is updated to P.

This test case needs some set up:
- Complete the steps you took from test case 3, be sure that you log in as a judge and verify that the B is displayed on the Session copy of the case you selected before completing this test. (Be sure that you take note of the case that you added the Pretrial Memo to)

Now the Test is Ready:
- Log in as a docket clerk
- Navigate to the case you used to set up this test
- Click on the Edit button on the far right of the docket record on the Pretrial memo that you added for the Respondent.
- Click on the Actions Tab
- Type (STRICKEN) in the Action area
- Click on Strike Entry
- Confirm that you want to Strike the entry
- The Pretrial Memo will now show up on the docket record with a line through it.
- Log in as Judge Buch
- Click on a City, State of the same trial session you used in the previous steps from the upcoming Trial Sessions card on your dashboard
- Repeat this entire test by logging in as Judge Buch's Chambers and as the Trial Clerk on the trial session (to test Trial clerk, you might need to add a test trial clerk user to the Calendared Trial Session so that you have access to view the session copy.)

Expected Results
- [x] **NEW FUNCTIONALITY** - On the Session copy page, there should be a P present in the new PTM column for this case.

**Comment by liadmccabe** [comment]
Please see screenshot below for column design to include PTM column and inclusion of "P" value.  Values would be substituted with "B" and "R" as needed.

![Add PTM Column - P.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/e0816ce9-22cf-41d3-b23a-e08b7258fec2)
