### ISSUE TITLE
Support for Longer/Bigger Trial Sessions

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8205]
As a court, so that I can schedule longer trial sessions, I need to be able to calendar trial sessions of approx. 250 cases at a time.

The court is seeing a higher volume of cases going to trial, which in some situations necessitates longer trial sessions, particularly in the larger cities. The court needs to be able to schedule a two-week volume of cases, potentially doubling the number of cases in a given trial session. Whereas the current model for calendaring has seen us able to successfully calendar trial sessions of around 125 cases successfully, attempts in the TEST environment to calendar cases in the 150 - 250 range result in failure (the symptom of which is the spinning wheel, an indication of a timeout).

We would like to be able to schedule a maximum of 250 cases for a given trial session successfully.

## Acceptance Criteria
* Trial sessions can be calendared with up to 250 cases successfully (i.e., all documents generated, served, presented for printing where appropriate)
* Calendared trial sessions with up to 250 cases can be edited to change the judge or proceeding type successfully (i.e., all documents generated, served, presented for printing where appropriate)
* Calendared trial sessions with up to 250 cases behave in all other regards as sessions with lower case counts, including Session Copy operability

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Test cases reviewed by an engineer on a deployed environment for Engineering Review.
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Trial session with 250 Cases is calendared; all documents generated, served, presented for printing where appropriate

- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on Add Trial Session
- Fill out the required fields (select a large metropolitan City so that there will be a lot of cases), and Add the Session
- Click on the City, State link from the New tab
- You will need to select QC Complete for 250 Cases.  
- To do this quickly, you can open the Console, and paste this in: 
- [...document.querySelectorAll('.usa-checkbox__label')].slice(0, 250).forEach(node => node.click());
- Next click enter on your keyboard, and 250 cases will be selected quickly for you.
- Click Set Calendar

Expected Results:
- [x] The Print for paper service option appears after the Trial Session is processed (this includes the Address label page, Notice of Trial, Standing Pre Trial Order (for small or regular), and the appropriate Clinic Letter)
- [x] Cases with Electronic Service get email service appropriately
- [x] Calendar is available on the Open Tab of the Trial Sessions Page


#### 2) Calendared trial session with 250 cases is edited to change the proceeding type;  (all documents generated, served, presented for printing where appropriate.

- Continuing from the previous test
- From the Open Tab, Click on the City, State link of the large Trial Session you just created 
- Click on Edit next to the Session information section
- Scroll down to the Proceeding type area, and change the proceeding type (if you had in-person before, switch it to Remote, or vice versa)
- Click Save

Expected Results
- [x] All of the cases on the large trial session will have a Notice of change from [In Person to Remote]/[Remote to In Person] Proceeding.
- [x] Print for paper service screen is presented
- [x] Cases with Electronic Service get email service appropriately
- [x] Updated Trial Session displays correctly on the Open tab


#### 3) Calendared trial session with 250 cases is edited to change the Judge;  (all documents generated, served, presented for printing where appropriate.

- Continuing from the previous test
- From the Open Tab, Click on the City, State link of the large Trial Session you just created 
- Click on Edit next to the Session information section
- Scroll down to the Judge Field, and change the Judge
- Click Save

Expected Results
- [x] All of the cases on the large trial session will have a Notice of change of Trial Judge
- [x] Print for paper service screen is presented
- [x] Cases with Electronic Service get email service appropriately
- [x] Updated Trial Session displays correctly on the Open tab


#### 4) Judge/CA/Trial Clerk accesses a session copy of a Calendared trial session with 250 cases; Session Copy behaves the same as sessions with lower case counts.

- Preconditions: You will need to log in as a Judge that is currently assigned to a Large Trial Session

- Log in as a Judge
- From your dashboard, click on the City/State link for the large trial session in your upcoming Trial Session Card

Expected Results:
- [x] Session Copy Page opens
- [x] Filters/sorting work appropriately
- [x] Can add session notes
- [x] Can add Notes to cases
- [x]  Can open the case by clicking on the docket record
- [x]  Can scroll through the list of all 250 cases on the page (is there a load more? or pagination? Dev decision?)
- [x] Can download all cases to a zip folder successfully
- [x] Can click "View all session info" link to see alternate view

- Repeat this last test with a CA and a Trial Clerk
