### ISSUE TITLE
Session Copy: Display Consolidation Status of Cases

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8214]
As a session copy viewer, so that I can see cases in a consolidated group together for trial planning, I need consolidated cases clearly indicated and grouped together in the trial listing part of the session copy page.

Cases in a consolidated group are typically calendared together for a trial session. When viewing a session copy page for the trial session however, there is no indication that a particular case is part of a consolidated group. 

We would like to extend the iconography recently applied to messaging in #whatever to the Session Copy page, and group cases belonging to the same consolidated group together.

## Acceptance Criteria
* On the Session Copy page, cases belonging to a consolidated group are indicated by an icon indicating whether or not the case is the Lead case or a Member case.
* On the Session Copy page, cases belonging to the same consolidated group are grouped together in the case listing, with the Lead case listed first followed by the member cases slightly indented underneath in ascending docket number order (i.e., oldest -> newest)
* Example: Cases 123-20, 234-20, and 345-21 are in a consolidated group together, with 123-20 being the Lead case. The case listing for these cases when calendared would be ordered as such:

123-15
123-16
123-20
  -234-20
  -345-21
150-20
123-22

## Notes
Use same icons that were used in other stories for consolidation. 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

Preconditions: You will need to ensure that there is a consolidated group of cases that have been calendared and assigned to a specific Judge that you have login access for.

#### 1) On the Session Copy page, a Consolidated Group of cases has iconography indicating if a case is the lead or a member case 
- Log in as a Judge, CA, or Trial Clerk and click on the City, State URL of the upcoming trial session that has the consolidated group calendared in.
- You will be routed to the Session Copy page
- Scroll down and view the case list.

Expected Results:
- [x] The lead case in the consolidated group has the Lead case indicator icon
- [x] The member cases in the condolidated group have the member case indicator icon
- [x] The member cases are indented slightly
- [x] The Cases in the consolidated group are grouped in ascending order (oldest to newest)


#### 2) Docket Clerk adds a new case to the consolidated group; manually calendars the case; Judge, CA, and Trial clerk see the new case displaying consolidated status appropriately on Session Copy Page
- Continuing from test case 1
- log in as a docket clerk
- Navigate to the trial sessions page and then click on the New tab.
- Find a case in the eligible case list that has the same case type as your cases in the consolidated group from test case 1
- Open the case and navigate to the case information tab
- Click on "Add to trial"
- Select the trial session that you used for test case 1, and click "Add Case"
- Next, click on the Case Information tab
- Under the consolidated Cases area, click on the add cases link and add this case to the consolidated group from test case 1 (you'll need to type in a case from that group)
- Now, log in as a Judge, CA, and Law clerk to view the session copy page

Expected Results:
- [x] The newly added case displays with the consolidated group, in acending order
- [x] If the case that was added was a member case, the indicator icon should be a member case icon
- [ ] If the case that was added was the new lead case, the indicator icon should be the lead case icon.
- [x] The member cases are indented slightly


#### 3) Docket Clerk removes a member case from the consolidated group; Judge, CA, and Trial Clerk see that the removed member case no longer has the consolidated iconography and is no longer grouped with the consolidated cases on the Session Copy page
- Continuing from Test Case 2
- Log in as a docket clerk
- Navigate to a case in the consolidated group that you have been using for the prevoius test cases
- Click on Case Information
- In the consolidated Cases area, click on the link for Remove cases
- Select a member case to remove, and then click "Unconsolidate Cases" button.
- Next, log in as a Judge, CA, and Law clerk to view the session copy page

Expected Results:
- [x] The newly removed case no longer displays with the consolidated group
- [x] The case no longer has the member case indicator icon
- [x] The case still appears in the case list, but it is not with the consolidated group.


#### 4) Docket Clerk removes the lead case from the consolidated group; Judge, CA, and Trial Clerk see that the removed lead case no longer has the consolidated iconography; is no longer grouped with the consolidated cases, and a new Lead case icon is displayed on the appropriate case.
- Continuing from Test Case 3
- Log in as a docket clerk
- Navigate to a case in the consolidated group that you have been using for the prevoius test cases
- Click on Case Information
- In the consolidated Cases area, click on the link for Remove cases
- Select the lead case to remove, and then click "Unconsolidate Cases" button.
- Take note of the new Lead case docket number
- Next, log in as a Judge, CA, and Law clerk to view the session copy page

Expected Results:
- [x] The newly removed case no longer displays with the consolidated group
- [x] The case that you removed no longer has the Lead case indicator icon
- [x] The case that you removed is still appears in the case list, but it is not with the consolidated group.
- [x] The case that you took note of in the previous step is now showing the Lead Case indicator icon.


#### 5) Sorting by Docket number or Petitioner Counsel on the Session Copy page retains the Consolidated Case Grouping, with the Lead case in the group listed first in Ascending Order.
- Log in as a Judge, CA, or Trial Clerk
- Click on a Session that has consolidated cases
- On the Session Copy page, click on the Docket Number header to sort by Docket Number (also test with clicking on the Petitioner Counsel Header).

Expected Results
- [x] The Consolidated case groupings retain their Order, so that the Lead Case in the Group remains the first case, followed by the member cases indented below it, regardless of where the member cases "fall" in the order of all of the docket numbers in the list.


#### 6) Judge/CA/Trial Clerk adds various filters for cases within the consolidated group; Filters by the Trial Status; WHAT IS THE DESIRED BEHAVIOR? - CHRIS IS CHECKING WITH THE COURT.

**Comment by ttlenard** [comment]
@TomElliottFlexion During testing, I found an issue with the grouping. Can you please take a look? Thank you!

If there is more than one consolidated group of cases on a trial session, it looks like it is indicating the lead case for both groups fine, but the member cases are duplicated below each lead case. Take a look on Test at this trial session. San Francisco, CA 9/26/2022 (Judge Buch) https://app.test.ef-cms.ustaxcourt.gov/trial-session-working-copy/1e26d148-647a-4fd4-85b6-6e05f653a6e1.

So:

**Lead Case 1**
- Member case A (should be part of Lead case 1)
- Member case B (should be part of Lead case 2)
- Member case C (should be part of Lead case 2)

**Lead case 2**
- Member case A (should be part of Lead case 1)
- Member case B (should be part of Lead case 2)
- Member case C (should be part of Lead case 2)

**Comment by ttlenard** [comment]
@TomElliottFlexion @liadmccabe @swongCO I also noticed that it is kind of hard to tell that the member cases were indented.  Maybe the indentation could be more pronounced?  Could the icons also be indented to help visually?

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/f21ae03f-38c2-45d6-a2cc-bc0676c1c2f5)
