### ISSUE TITLE
Calendaring: Case Type Filter on Eligible Cases List Hybrid Sessions

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8249]
As a calendaring user, so that I can easily assign the right balance of small and regular case types to Hybrid trial sessions, I need to be able to filter the Eligible Cases list by case type.

Hybrid trial sessions comprise both small and regular types of cases; these sessions often require careful calendaring so that the session is balanced appropriately based on volume and pending cases for the area. 

Currently, the Eligible Cases list presented when setting the calendar for a Hybrid session displays both small and regular case types as designed. To assist the calendaring user in assigning cases, we would like to implement a filter on this list to allow them to see just the small or just the regular cases eligible for the session if desired.

N.B.: We are NOT changing any of the criteria used to determine whether a case appears on the Eligible Cases list.

## Acceptance Criteria
* On the Trial Session page when the Eligible Cases list is presented, if the session Type is "Hybrid", the user can choose to display only cases with the type of "Small" on the Eligible Cases list.
* On the Trial Session page when the Eligible Cases list is presented, if the session Type is "Hybrid", the user can choose to display only cases with the type of "Regular" on the Eligible Cases list.
* On the Trial Session page when the Eligible Cases list is presented, if the list is currently filtered for a specific Case Type, the user can choose to display all cases with the types of both "Regular" and "Small" (i.e., the default view) on the Eligible Cases list.
* Any cases marked as "QC Complete" while the Case Type filter is applied remain marked as such when the filter is removed 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk adds a new Hybrid trial session, New functionality available to Filter by Small or Regular Cases.

- Log in as a Petitions Clerk
- Click on the Trial Session tab
- Click on Add Trial Session
- Fill out the details of the trial session, being sure to select Hybrid as the Session Type.
- Click Add Session.
- From the New tab, navigate to the city/state of the session you just created.

Expected Results
- [x] Petitions clerk now has the ability to filter by Small or Regular Case types listed in the Eligible case list.


#### 2) Petitions Clerk Filters the Eligible case list to display only Small cases.

- Continuing from the previous test
- Filter the list to only display Small cases

Expected Results:
- [x] The Eligible case list is filtered so that only Small cases appear in the list.


#### 3) Petitions Clerk checks the box for some of the Small cases appearing on the filtered list; the Completed total displays the total number of cases selected.

- Continuing from the previous test
- Check the box under the QC Complete for some of the Small cases.

Expected Results
- [x] The Completed total reflects the number of boxes that you checked as QC Complete.


#### 4) Petitions Clerk Filters the Eligible case list to display only Regular cases.

- Continuing from the previous test
- Update the filter to only display Regular cases

Expected Results:
- [x] The Eligible case list is filtered so that only Regular cases appear in the list
- [x] The Completed total reflects the number of boxes that you checked as QC complete for small cases in the previous test.


#### 5) Petitions Clerk checks the box for some of the Regular cases appearing on the filtered list; the Completed total displays the total number of cases selected (Small and Regular).

- Continuing from the previous test
- Check the box under QC Complete for some of the Regular Cases

Expected Results:
- [x] The completed total reflects the number of boxes that you checked as QC Complete (Regular and Small)


#### 6) Petitions Clerk clears the filter so that they see the default view (regular and small cases), Total number of cases that had the QC complete checkbox checked appear in the unfiltered view.

- Continuing from the previous test
- Clear the filter so that the Eligible case list is back to the default view (showing all cases (regular and small).

Expected Results:
- [x] The check boxes that you checked in the previous test cases are all still checked, and the Completed total reflects the total number of QC Completed boxes that you checked accurately.


#### 7) Petitions Clerk accesses a Hybrid trial session that has already been created on the New tab; New functionality available to Filter by Small or Regular Cases.

- Log in as a Petitions Clerk
- Click on the Trial Sessions Tab
- Click on the New tab
- Click on the City/State of a trial session that was created previously (prior to the release of this new code)

Expected Results:
- [x] Petitions clerk now has the ability to filter by Small or Regular Case types listed in the Eligible case list.


#### 8) Petitions Clerk filters the Eligible case list to display only Small cases.

- Continuing from the previous test
- Filter the list to only display Small cases

Expected Results:
- [x] The Eligible case list is filtered so that only Small cases appear in the list.


#### 9) Petitions Clerk checks the box for some of the Small cases appearing on the filtered list; the Completed total displays the total number of cases selected.

- Continuing from the previous test
- Check the box under the QC Complete for some of the Small cases.

Expected Results
- [x] The Completed total reflects the number of boxes that you checked as QC Complete.


#### 10) Petitions Clerk accesses a Hybrid trial session that has already been created; Filters the Eligible case list to display only Regular cases.

- Continuing from the previous test
- Update the filter to only display Regular cases

Expected Results:
- [x] The Eligible case list is filtered so that only Regular cases appear in the list
- [x] The Completed total reflects the number of boxes that you checked as QC complete for small cases in the previous test.


#### 11) Petitions Clerk checks the box for some of the Regular cases appearing on the filtered list; the Completed total displays the total number of cases selected (Small and Regular).

- Continuing from the previous test
- Check the box under QC Complete for some of the Regular Cases

Expected Results:
- [x] The completed total reflects the number of boxes that you checked as QC Complete (Regular and Small)


#### 12) Petitions Clerk clears the filter so that they see the default view (regular and small cases), Total number of cases that had the QC complete checkbox checked appear in the unfiltered view.

- Continuing from the previous test
- Clear the filter so that the Eligible case list is back to the default view (showing all cases (regular and small).

Expected Results:
- [x] The check boxes that you checked in the previous test cases are all still checked, and the Completed total reflects the total number of QC Completed boxes that you checked accurately.

#### 13) Petitions Clerk adds a new trial session that is NOT a Hybrid Session type; Filter is not available for the Clerk.

- Log in as a Petitions Clerk
- Click on the Trial Sessions Tab
- Click on Add New Session
- Fill out the required session information, being sure to pick a session type other than Hybrid.
- Click Add Session
- Click on the New tab, and then click on the City/State of the session you just created.

Expected Results
- [x] The Filter is not available for the clerk on this session

*Repeat this test for all of the session types (besides Hybrid) to ensure that the filter is not present in the view.

#### 14) Petitions Clerk edits a trial session on the New tab from a regular trial session to a Hybrid Trial session; Filter is available on the Eligible Case list.

- Log in as a Petitions Clerk 
- Click on the Trial Sessions Tab
- Click on the New Tab
- Click on the city/state link for a regular trial session
- Filter should NOT be available for the regular trial session
- Click on the Edit link 
- Change the Session type from Regular to Hybrid
- Click Save

Expected Results
- [x]  The Eligible case list now has the Filter available to filter the list by regular or small cases.

#### 15) Petitions Clerk edits a trial session on the New tab from a Hybrid trial session to a Small session; Filter is no longer available on the Eligible Case list.

- Log in as a Petitions Clerk 
- Click on the Trial Sessions Tab
- Click on the New Tab
- Click on the city/state link for a Hybrid trial session
- Filter should be available for the Hybrid trial session
- Click on the Edit link 
- Change the Session type from Hybrid to small
- Click Save

Expected Results
- [x]  The Eligible case list no longer has the Filter available.

**Comment by swongCO** [comment]
UX feedback:
1. Vertically align "Filter by" to the dropdown (see Docket Record filter for guidance-screenshot below)
![Screen Shot 2022-09-22 at 2.49.01 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3b5c4c4a-349f-4e8d-8754-42eebfa5be3f)

2. "Filter by" wraps to two lines when the browser window width is reduced (screenshot below)
![Screen Shot 2022-09-22 at 11.18.10 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/99dd49f5-28b9-4f34-b461-d6f9da790c1c)

3. The spacing between the filter and the table is slightly larger than the spacing in the Docket Record - I inspected the elements and it looks like the counter above the table has a margin below it which is adding to the overall spacing (screenshot below)
![Screen Shot 2022-09-22 at 2.40.23 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/8e540b57-48a7-48d8-a2eb-aac08dbdf45a)
If you removed the margin under the counter, would it break anything else that you know of? Since the spacing with the counter to table is so inconsistent across Dawson, I thought we could experiment with this one to see how it would look.
