### ISSUE TITLE
Practitioner: Consolidated Group Display on My Cases Page

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8254]
As a practitioner, so that I can easily understand which cases are in my consolidated group, I need the case listings for consolidated groups to be clear.

Currently the My Cases dashboard for a practitioner lists cases in a consolidated group together, ordered by docket number. We would like to update this display on both the Open and Closed views to reflect the current iconography for consolidated group cases.

## Pre-Conditions
ustaxcourt/ef-cms#8252

## Acceptance Criteria
* Consolidated groups displayed on the My Cases dashboard have iconography displaying whether the case is a Lead or Member case in the group (similar to the current iconography used in other areas of DAWSON)
* If a case in a CG is closed but at least one other case in the CG is open, display all cases in the CG on both the Open and Closed Cases tabs
* If all cases in the CG are closed, display all cases in the CG on the Closed Cases tab
* These changes are present on both the Open Cases and Closed Cases views
* Use same feature flag as ustaxcourt/ef-cms#8252

## Notes
Current view of consolidated case group on My Cases page for practitioners:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/a0f0a2b9-2b3b-4aee-8736-ab04c80b5583)
* NEEDS TESTING W/ IRS PERSONNEL

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by TomElliottFlexion** [comment]
Similar design from 9535: ![image.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/90eea63a-a361-45b1-8487-ac6c7fdc991f)

**Comment by ttlenard** [comment]
FYI - Here is the current mobile view for the My cases tab for a practitioner that has access to consolidated cases. UX would like to meet with the devs regarding this view when this story get's picked up. Thanks!
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/b2a7b56e-b75a-4938-a946-9ee23e60562e)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Private Practitioner is associated with an open case in a consolidated group of cases; Consolidated cases have updated iconography on the My Cases/Open Cases Screen.

Preconditions: Private Practitioner needs to be associated with at least one open case in a consolidated group, as well as at least one non-consolidated open case.

- Log in as a Private Practitioner
- You will be navigated to the My Cases Screen/Open Cases

Expected Results:
- [x] **NEW FUNCTIONALITY** - The lead case indicator is next to the new blue colored lead case in the consolidated group
- [x] **NEW FUNCTIONALITY** - The member case indicator is next to each member case in the consolidated group
- [x] **NEW FUNCTIONALITY** - Indentation remains the same (Member cases are indented slightly)
- [x] The case(s) that are not in the consolidated group are listed in order by date filed (in relation to the lead case); does not have the consolidated icons present next to the docket number.



#### 2) Private Practitioner view of the My Cases/Open Cases screen displays all of the cases in the consolidated group if all cases in the group are not all closed.

- Log in as a docket clerk, and navigate to the consolidated group from the test case above.
- Close a case that is in the consolidated group, making sure that at least one of the cases remains open.
- Next, log in as a Private Practitioner that is a party on at least one case in a consolidated group of cases.
- Review the My Cases/Open Cases screen

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case(s) that are closed, still remain in the list of cases on the Open Cases tab, if at least one case in the Consolidated group of cases is still open.
- [x] **NEW FUNCTIONALITY** - The Lead Case in the Consolidated group displays the new blue colored lead case icon
- [x] **NEW FUNCTIONALITY** - The member case(s) in the Consolidated group displays the member case icon
- [x] Indentation remains the same (Member cases are indented slightly)




#### 3) Private Practitioner view of the My Cases/Closed Cases screen displays updated consolidated case iconography for Lead and member cases.

- Log in as a Docket Clerk
- Close the rest of the cases that remain on the consolidated group, making sure that no cases remain open.
- Log in as a Private Practitioner that is a party on at least one case in a consolidated group of cases.
- Review the My Cases/Open Cases Screen

Expected Results:
- [x] The consolidated group of cases no longer appears under the Open Cases tab (Since all of the cases in the group are now closed.)


- Next, Click on the Closed Cases tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Lead Case in the Consolidated group displays the new blue colored lead case icon
- [x] **NEW FUNCTIONALITY** - The member case(s) in the Consolidated group displays the member case icon
- [x] Indentation remains the same (Member cases are indented slightly)
- [x] The case(s) that are not in the consolidated group are listed in order by date filed (in relation to the lead case); does not have the consolidated icons present next to the docket number.




#### 4) IRS Practitioner is associated with an open case in a consolidated group of cases; Consolidated cases have updated iconography on the My Cases/Open Cases Screen.

Preconditions: IRS Practitioner needs to be associated with at least one open case in a consolidated group, as well as at least one non-consolidated open case.

- Log in as a IRS Practitioner
- You will be navigated to the My Cases Screen/Open Cases

Expected Results:
- [x] **NEW FUNCTIONALITY** - The new blue colored lead case indicator is next to the lead case in the consolidated group
- [x] **NEW FUNCTIONALITY** - The member case indicator is next to each member case in the consolidated group
- [x] Indentation remains the same (Member cases are indented slightly)
- [x] The case(s) that are not in the consolidated group are listed in order by date filed (in relation to the lead case); does not have the consolidated icons present next to the docket number.



#### 5) IRS Practitioner view of the My Cases/Open Cases screen displays all of the cases in the consolidated group if all cases in the group are not all closed.

- Log in as a docket clerk, and navigate to the consolidated group from the test case above.
- Close a case that is in the consolidated group, making sure that at least one of the cases remains open.
- Next, log in as an IRS Practitioner that is a party on at least one case in a consolidated group of cases.
- Review the My Cases/Open Cases screen

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case(s) that are closed, still remain in the list of cases on the Open Cases tab, if at least one case in the Consolidated group of cases is still open.
- [x] **NEW FUNCTIONALITY** - The Lead Case in the Consolidated group displays the new blue colored lead case icon
- [x] **NEW FUNCTIONALITY** - The member case(s) in the Consolidated group displays the member case icon
- [x] Indentation remains the same (Member cases are indented slightly)




#### 6) IRS Practitioner view of the My Cases/Closed Cases screen displays updated consolidated case iconography for Lead and member cases.

- Log in as a Docket Clerk
- Close the rest of the cases that remain on the consolidated group, making sure that no cases remain open.
- Log in as an IRS Practitioner that is a party on at least one case in a consolidated group of cases.
- Review the My Cases/Open Cases Screen

Expected Results:
- [x] The consolidated group of cases no longer appears under the Open Cases tab (Since all of the cases in the group are now closed.)


- Next, Click on the Closed Cases tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Lead Case in the Consolidated group displays the new blue colored lead case icon
- [x] **NEW FUNCTIONALITY** - The member case(s) in the Consolidated group displays the member case icon
- [x] Indentation remains the same (Member cases are indented slightly)
- [x] The case(s) that are not in the consolidated group are listed in order by date filed (in relation to the lead case); does not have the consolidated icons present next to the docket number.




#### 7) Mobile Device - Regression test by repeating tests 1-6 on various mobile devices.

- Log in as Private Practitioner and IRS Practitioner

Expected Results:
- [x] Ensure that the functionality as listed in tests 1-6 function the same
- [x] **NEW FUNCTIONALITY** - Ensure that the iconography is appropriately displayed/formatted and "looks nice" when viewing the Open Cases/Closed Cases lists on a mobile device



#### 8) Regression test this story with the Feature Flag OFF

- Log in as a Private Practitioner that is a party on at least one case in a consolidated group of cases.
- Review the My Cases/Open Cases and the My Cases/Closed Cases tabs

Expected Results:
- [x] The updated consolidated case icons are now present on the Open Cases/Closed Cases tab, but none of the other grouping functionality.
- [x] If a case in the consolidated group is closed, but others are still open, the singular closed case is present on the closed cases tab if the user is associated with that case. If the user is not associated with that case, it does not appear on the closed cases tab.

*Repeat this test by logging in as an IRS Practitioner.

**Comment by TomElliottFlexion** [comment]
Completed in combination with ustaxcourt/ef-cms#8256

**Comment by ttlenard** [comment]
Feature flag name: `consolidated-cases-group-access-petitioner`

**Comment by ttlenard** [comment]
All tests pass. Thanks all!
