### ISSUE TITLE
Calendar: Display Case Type Counts on Hybrid Sessions

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8264]
As a calendaring user, so that I can easily tell how many of each type of case has been QC'ed for a Hybrid trial session, I need to see current counts of QC'd cases broken out by case type.

The current calendaring UI displays an ongoing count (labeled as "Completed") of the cases that have been checked as "QC Complete?" in the Eligible Cases list. A hybrid trial session comprises both regular and small case types; in order to give the user an accurate count of the number of each type of case that has had QC completed for the session, we would like to display the "Completed" number for both regular and small cases in addition to the overall "Completed" count. 

## Acceptance Criteria
* When setting cases for trial in a hybrid trial session, the number of Regular cases marked as "QC Complete" in the Eligible Cases list is visible
* When setting cases for trial in a hybrid trial session, the number of Small cases marked as "QC Complete" in the Eligible Cases list is visible
* When setting cases for trial in a hybrid trial session, the overall number of cases marked as "QC Complete" in the Eligible Cases list is visible (current behavior)
* The displayed counts for Regular, Small, and overall should be all be visible regardless of the Case Type filter (implemented with ustaxcourt/ef-cms#8249) selected 
* All displayed counts should update as cases are selected and de-selected as "QC Complete"

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### UX specs
![Trial Session - Eligible cases - type count.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/fc954da4-b43b-4252-a51c-2dfdab83b3c3)

- Change existing "Completed" count label to "Total Completed"
- Add "Regular" and "Small" before the above count
- Font weight of the labels (Regular, Small, Total Completed) to remain BOLD
- Change font weight of the number output after the labels to REGULAR (to align with the label/data conventions throughout Dawson)
- Spacing between each counter is 50px, with a minimum spacing of 20px for responsive views of smaller breakpoints

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk adds a new Hybrid trial session; total counts for how many Regular, Small and the Overall total QC completed cases is displayed. 

- Log in as a Petitions Clerk
- Click on the Trial Session tab
- Click on Add Trial Session
- Fill out the details of the trial session, being sure to select Hybrid as the Session Type.
- Click Add Session.
- From the New tab, navigate to the city/state of the session you just created.
- Scroll down to the Eligible case list 

Expected Results:
- [x] The displayed counts for Regular, Small, and Total Completed should be visible to the user (at this point they total counts should be 0, since no QC complete boxes have been checked yet)



#### 2) Petitions Clerk filters by Small Cases; Marks some Small cases as QC complete; Number of Small Cases selected is visble.

- Continuing from the previous test
- Filter the Eligible case list to only display only Small cases
- Mark some of the Small cases as QC complete by checking the box.

Expected Results:
- [x] The total number of Small cases that have been marked as QC Complete is totaled for the user.
- [x] The overall number of cases (Small and Regular) that have been marked as QC complete is totaled for the user and should match the total small cases that you marked as QC completed.
- [x] The total number of Regular cases should remain at 0.



#### 3) Petitions Clerk clears the filters to show all cases; Small Cases previous checked display in the list; total counts for how many Regular, Small and the total QC completed cases is displayed. 

- Continuing from the previous test
- Update the filter to show both Small and Regular Cases

Expected Results
- [x] The Small cases that you previously checked appear in the Eligible case list with their check boxes checked
- [x] The total number of Small cases that have been marked as QC Complete is totaled for the user.
- [x] The overall number of cases (Small and Regular) that have been marked as QC complete is totaled for the user and should match the total small cases that you marked as QC completed.
- [x] The total number of Regular cases should remain at 0.



#### 4) Petitions Clerk Filters the Eligible case list to display only Regular cases; Marks some Regular cases as QC complete; Number of Regular Cases selected is visble.

- Continuing from the previous test
- Update the filter to only display Regular cases
- Mark some of the Regular Cases as QC complete by checking the box

Expected Results:
- [x] The total number of Regular cases that have been marked as QC Complete is totaled for the user.
- [x] The overall number of cases (Small and Regular) that have been marked as QC complete is totaled for the user and should match the total small cases + Regular Cases that you marked as QC completed.
- [x] The total number of Small cases should match the total small cases that you selected in the earlier test.



#### 5) Petitions Clerk clears the filters to show all cases; Small and Regular Cases previous checked display in the list; total counts for how many Regular, Small and the Overall total QC completed cases is displayed. 

- Continuing from the previous test
- Update the filter to show both Small and Regular Cases

Expected Results
- [x] The Small cases that you previously checked appear in the Eligible case list with their check boxes checked
- [x] The Regular cases that you previously checked appear in the Eligible case list with their check boxes checked
- [x] The total number of Small cases and the total number of Regular Cases that have been marked as QC Complete is totaled separately for the user next to the Total Completed.
- [x] The overall number of cases (Small and Regular) that have been marked as QC complete is totaled for the user and should match the total number of cases that you marked as QC completed.



#### 6) Petitions Clerk accesses a Hybrid trial session that has already been created on the New tab; total counts for how many Regular, Small and the Overall total QC completed cases is displayed.

- Log in as a Petitions Clerk
- Click on the Trial Sessions Tab
- Click on the New tab
- Click on the City/State of a trial session that was created previously (prior to the release of this new code)
- Scroll down to the Eligible Case List

Expected Results:
- [x] The displayed counts for Regular, Small, and Total Completd QC'd cases should be visible to the user 




#### 7) Petitions Clerk edits a trial session on the New tab from a regular trial session to a Hybrid Trial session; Filter is available on the Eligible Case list; total count is present.

- Log in as a Petitions Clerk 
- Click on the Trial Sessions Tab
- Click on the New Tab
- Click on the city/state link for a regular trial session
- Filter should NOT be available for the regular trial session. 
- Be sure that some of the regular cases have been marked as QC completed.
- Click on the Edit link 
- Change the Session type from Regular to Hybrid
- Click Save

Expected Results
- [x] The Eligible case list now has the Filter available to filter the list by regular or small cases.
- [x] The total number of Regular cases that had previously been checked is now showing in the Count
- [x] The total number of Small cases should display as 0
- [x] The total completed cases should match the Regular count.


#### 8) Petitions Clerk edits a trial session on the New tab from a Hybrid trial session to a Small session; Filter is no longer available on the Eligible Case list.

- Log in as a Petitions Clerk 
- Click on the Trial Sessions Tab
- Click on the New Tab
- Click on the city/state link for a Hybrid trial session
- Filter should be available for the Hybrid trial session
- Click on the Edit link 
- Change the Session type from Hybrid to small
- Click Save

Expected Results
- [x] The Eligible case list no longer has the Filter available.
- [x] The total count of QC'd cases for Small or Regular cases no longer appears.
- [x] The Total Completed Count is available.

**Comment by swongCO** [comment]
@rgoshen Updated UX specs with spacing between counters

**Comment by swongCO** [comment]
@rgoshen Looks good. Have a couple of minor UI adjustments (screenshot below):

![Screen Shot 2022-10-03 at 10.36.00 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/86b7d4a3-ac0b-4613-8da6-eb32e20a3a68)

Use existing components to help future dev efforts with consistency:
- Filter By dropdown in Docket Record
- Table counter in Trial Session Info

cc @liadmccabe
