### ISSUE TITLE
Petitioner: Docket Search Capability

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8268]
As a petitioner, so that I can take advantage of DAWSON's search capabilities, I need to be able to search for cases while logged in.

Currently a logged in petitioner has no access to the search functionality in DAWSON. They should. We would like to implement the same search functionality extended to practitioners in the nav bar for petitioners (see screenshot below).

This story will address implementing the search UI applet on the petitioner My Cases view.

## Acceptance Criteria
* When logged in, the petitioner can search by docket number from their My Cases view
* When searching for a docket number, if the case is sealed and the petitioner is not a party to it then return the "sealed case UI" (see screenshot below)
* When searching for a docket number, if the case is sealed and the petitioner is a party to it then display the case as normal
* When docket record is found, displays in the current tab w/ persistent link back to My Cases view (same behavior as for practitioner)
* When docket record is NOT found, display "No Matches Found page", with updated text (See image below - this is different wording than what is displayed for a Practitioner or when this page appears for advanced search).
* Do not include link to Advanced Search - will address in separate story

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/f54926a5-3707-4c83-ae01-9f81438fea04)

Sealed Case UI (Returned when searching for docket that is sealed at the case level):

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/1c5233a4-fd9c-4d5f-a4b4-2115095dafd2)

No Matches Found UI - when searching for a docket record that doesn't exist - "contact us" link will redirect to the Contact Us page in the footer nav:

![Screen Shot 2022-10-18 at 3.18.01 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/8b16a0d8-6d67-4fd4-b166-411643e77d18)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### UX Specs
Use the search card from the practitioner homepage and modify per the AC. Place the search card above the taxpayer tools card.
![My Cases - Search docket.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/10f89c8b-7edb-4383-be7b-89caf5addea1)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Search for a Case card is on the My Cases page for a Petitioner.

- Log in as a Petitioner

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Search for a Case card is now above the Taxpayer Tools card
- [x] **NEW FUNCTIONALITY** - There is no link for Advanced Search on the Card, and there is no additional text about filing an entry of appearance (as it displays for a logged in Practitioner).


#### 2) Petitioner searches for a case by a docket number; Docket number exists; Docket record of case opens on same tab; My Cases link is available to Petitioner.

- Continuing from the previous test case
- Type in a docket number in the Search box
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case loads on the same tab and Petitioner can view the docket record
- [x] **NEW FUNCTIONALITY** - The Docket record view is the same as if a non-logged in user searched for the case (only Orders/Opinions) have active links, all other documents do not have any links.
- [x] **NEW FUNCTIONALITY** - Petitioner can click on either the My Cases header OR the USTC seal to return to the My Cases page.


#### 3) Petitioner searches for a case by a docket number; Docket number does not exist; Message indicating docket number not found; My Cases link is available to Petitioner.

- Log in as a petitioner
- Type in a docket number that does not exist in the Search Box (try a really large number, or 100-22)
- Click Search

Expected Results
- [x] **NEW FUNCTIONALITY** - Page loads and states "No Matches Found. Check your docket number and try again. If you need help, contact us."
- [x] **NEW FUNCTIONALITY** - Petitioner can click on either the My Cases header OR the USTC seal to return to the My Cases page.


#### 4) Petitioner searches for a sealed case by typing in the docket number; Sealed Case page loads for Petitioner; My cases link is available to Petitioner.

- Log in as a Petitioner
- Type in a docket number for a case that is sealed (I used 9771-22W)
- Open up the Console app
- Click Search

Expected Results
- [x] **NEW FUNCTIONALITY** - The Sealed Case page loads (Red banner on top indicating that the case is sealed. No petitioner information appears. Text states "This case is sealed and not accessible to the public.)
- [x] **NEW FUNCTIONALITY** - When looking at the case JSON in the Console, the very limited view of the case info is displayed since the case is sealed.


#### 5) Petitioner searches for a case that has sealed Orders; Docket record of case opens on the same tab, Sealed Orders do not have active links; Red lock icon displays next to the document.

- Log in as a Petitioner
- Type in a docket number for a case that has at least one sealed Order 
- Click Search

Expected Results
- [x] **NEW FUNCTIONALITY** - The case loads on the same tab and Petitioner can view the docket record
- [x] **NEW FUNCTIONALITY** - The Sealed Order does not have an active hyperlink, it has the red lock icon, and when hovering over the red lock, help text indicates the seal level.



#### 6) Petitioner searches for a case that they are a party to by docket number; Docket record of case opens on same tab; Petitioner view of docket record opens.

- Log in as a Petitioner
- Type in a docket number for a case that you are a party to.
- Click Search

Expected Results
- [x] **NEW FUNCTIONALITY** - The Petitioner docket record view opens in the same tab (File a document button is available (assuming petition has been served), all documents on the docket record are active links, Case information tab is available, etc.

**Comment by swongCO** [comment]
@ttlenard The no matches found message in test case 3 doesn't match what's in the AC. We passed it per the AC.

**Comment by ttlenard** [comment]
@swongCO I updated the test case with the updated "No Cases Found" wording. Thanks for pointing that out.  

All tests pass! Looks great!
