### ISSUE TITLE
Replace "Miscellaneous" as Default Document Type on Add Docket Entry Screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8283]
As a docket supervisor, so that I can cut down on the number of documents filed as Miscellaneous, I need to replace "Miscellaneous" as the default document type entry on the Add Docket Entry screen.

We see a larger-than-desired number of documents being docketed with the event code "MISC" by court users. One theory as to the root of this behavior is that by making "Miscellaneous" - a document type that requires no other field validation - the default option, we are encouraging users to leave it selected when a more appropriate event code/document type is already in the menu.

MISC should be an event code of last resort, not the default; in order to better understand gaps in our document type library and increase the accuracy of the docket record, we would like to replace "Miscellaneous" as the default entry in this menu with text requiring the user to affirmatively select a document type.

## Acceptance Criteria
* Default entry in the Document Type field on the Add Docket Entry screen is " - Select -"
* Docket entries cannot be saved or served unless a valid Document Type is chosen from the Document Type dropdown menu
* Choosing a Document Type from the dropdown menu displays UI elements as required by that Document Type in the usual manner

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk Uploads a PDF, on the Add Docket Entry Screen, the Document Type field displays "-Select-". 

- Log in as a docket clerk
- Navigate to a case
- Click on the Create menu
- Select PDF Upload
- Upload a PDF, add a description, click save
- Click Add Docket Entry from the document viewer

Expected Results:
- [x] The Document type field no longer has "Miscellaneous" as the default document type
- [x] The Document type field displays the word "-Select".


#### 2) Docket Clerk attempts to Save and Serve a document from the Add Docket Entry screen without indicating a document type; Receives Validation error.

- Continuing from the previous test
- Be sure that the default "-Select-" is active in the Document type dropdown
- Click Save and Serve

Expected Results:
- [x] Clerk receives Validation Error indicating that they need to select a document type.



#### 3) Docket Clerk attempts to Save a document from the Add Docket Entry screen without indicating a document type; Receives Validation Error.

- Continuing from the previous test
- Be sure that the default "-Select-" is active in the Document type dropdown
- Click Save Entry

Expected Results:
- [x] Clerk receives Validation Error indicating that they need to select a document type.



#### 4) Docket Clerk selects a document type from the picklist; additional fields display in the usual manner, depending on the document type selected

- Continuing from the previous test
- Select a document from the Document Type dropdown.

Expected Results
- [x] Additional fields display in the usual manner depending on the document type selected.
- [x] When you save and serve the document, the document is served in the usual manner and docketed appropriately.

*Repeat this test by clicking the "Save entry" button, rather than the "Save and Serve"
