### ISSUE TITLE
Add Filtering to ADC User Messages

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8345]
As a ADC user, so that I can prioritize and understand my work, I need to be able to filter my displayed messages.

The ADC section is facing a large backlog of work that needs to be addressed. Operationally so that a more targeted view of messages that need responding to can be addressed, we want each ADC user to be able to filter their Messages for specific values.

We expect to extend this functionality to other user messages in the near future.

## Pre-Conditions
ustaxcourt/ef-cms#8347

## Acceptance Criteria
* ADC user messages Inbox display can be filtered for a specific value present in the Case Status field
* ADC user messages Inbox display can be filtered for a specific value present in the From field
* ADC user messages Inbox display can be filtered for a specific value present in the Section field
* ADC user messages Sent display can be filtered for a specific value present in the Case Status field
* ADC user messages Sent display can be filtered for a specific value present in the To field
* ADC user messages Sent display can be filtered for a specific value present in the Section field
* Filter selections refresh the list of displayed messages according to the selected filters immediately upon selection
* Multiple filters can be selected concurrently
* Filters can be cleared
* Filters are available on views (Inbox, Sent)
* No filters required on user messages Completed messages view
* Filters can be applied in conjunction with sorting criteria

## Test Cases
* User messages display all messages; filter selection is made for From field; displays only messages with the corresponding value in the From field
* User messages display all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field
* User messages display all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field
* Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately
* Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages
* Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
##  Test Cases

_You will most likely need to send some test messages (~10 +?) in DAWSON to a test ADC user in order to perform these tests._
- To set these up:
- Log in as a docket clerk
- Go to a case (take note of the case status) and click on create and then choose Message
- Send a message to ADC 1 user
- Go to a different case with a different case status as the first case, and send a message
- Log out as a docket clerk and log in as a Petitions Clerk
- Repeat the steps above and send a few messages to ADC 1 user
- Log in as an Admissions Clerk
- repeat the steps above and send a few messages to ADC 1 user

#### 1) User messages display all messages for user; filter selection is made for From field; displays only messages with the corresponding value in the From field
**Inbox tab**
- Log in as an ADC 1
- Be sure that you are on the My Messages tab screen
- On the Inbox tab
- Click on the "From" filter and make a selection

Expected Results
- [ ] The Inbox tab is now filtered and only display messages with the corresponding value in the "From" field.
- [ ] The message count of the Inbox has updated to reflect the number of messages that are in the tab associated with the "From" value.


#### 2) User messages display all messages for user; filter selection is made for To field; displays only messages with the corresponding value in the To field
**Sent tab**
- Continuing from the above, click on a message from your inbox
- Click Reply to Send a message back to the user that sent the message
- Add some text in the message box, and click send.
- Do the above steps with a few of your messages
- Go back to your messages tab and click on Sent
-  Click on the "To" filter and make a selection

Expected Results
- [ ] The Sent tab is now filtered and only display messages with the corresponding value in the "To" field.
- [ ] The message count of the Sent tab has updated to reflect the number of messages that are in the tab associated with the "To" value.


#### 3) User messages display all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field
- Log in as an ADC
- Be sure you are on the Messages tab
- Be sure that you run this test with the Inbox and Sent tabs
- Click on the "Case Status" filter and make a selection

Expected Results
- [ ] The Inbox and Sent tabs are now filtered and only display messages with the corresponding value in the "Case Status" field.
- [ ] The message count of Inbox and Sent tabs have updated to reflect the number of messages that are in the tab associated with the "Case Status" value.


#### 4) User messages display all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field
- Log in as an ADC
- Be sure you are on the Messages tab
- Be sure that you run this test with the Inbox and Sent tabs
- Click on the "Section" filter and make a selection

Expected Results
- [ ] The Inbox and Sent tabs are now filtered and only display messages with the corresponding value in the "Section" field.
- [ ] The message count of Inbox and Sent tabs have updated to reflect the number of messages that are in the tab associated with the Section value.


#### 5) Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately
- Continuing from Test Case 4
- Be sure that you run this test with the Inbox and Sent tabs 
- Change the selection you had in the Section Filter to a new selection (Spot check doing this same test with all the other filters)

Expected Results
- [ ] The Inbox and Sent tabs are now filtered and only display messages with the new corresponding value in the "Section" field (or other filter applied).
- [ ] The message count of Inbox and Sent tabs have updated to reflect the number of messages that are in the tab associated with the newly selected "Section" value (or other filter applied)

#### 6) Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages
- Be sure that you run this test with the Inbox and Sent tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Clear the filters (set them back to the default)

Expected Results
- [ ] The Inbox and Sent tabs are no longer filtered and display all messages with no filters on
- [ ] The message count of Inbox and Sent tabs have updated to reflect the total number of messages that are in the tab

**Repeat the above steps with these other filters**
- Click on the "From" filter and make a selection
- Clear the filters (set them back to the default)
- Click on the "Case Status" filter and make a selection
- Clear the filters (set them back to the default)
- Click on the "Section" filter and make a selection
- Clear the filters (set them back to the default)


#### 7) Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection
- Be sure that you run this test with the Inbox and Sent tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Click on the "From" filter and make a selection
- Click on the "Case Status" filter and make a selection
- Click on the "Section" filter and make a selection

Expected Results
- [ ] The Inbox and Sent tabs are now filtered and only display messages with the corresponding values based off of the filtered values.
- [ ] The message count of Inbox and Sent tabs have updated to reflect the number of messages that are in the tab associated with the filtered value.


#### 8) Filter is applied, display updates appropriately; sort the filtered column to arrange results in descending order
- Be sure that you run this test with the Inbox and Sent tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Click on the caret on the Docket Number header to Sort the results in descending order

Expected Results:
- [ ] Columns are filtered appropriately and sorted in descending order

**Repeat the steps above with these columns.**
- Click on the "From" filter and make a selection
- Click on the "Case Status" filter and make a selection
- Click on the "Section" filter and make a selection

**Repeat this test by sorting additional columns (column header varies by tab)**
- Received/Sent
- Message Subject


#### 9) Filter is applied, display updates appropriately; sort the filtered column to arrange results in ascending order
- Be sure that you run this test with the Inbox and Sent  tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Click on the caret on the Docket Number header to Sort the results in ascending order

Expected Results:
- [ ] Columns are filtered appropriately and sorted in ascending order

**Repeat the steps above with these columns.**
- Click on the "From" filter and make a selection
- Click on the "Case Status" filter and make a selection
- Click on the "Section" filter and make a selection

**Repeat this test by sorting additional columns (column header varies by tab)**
- Received/Sent
- Message Subject

**Comment by swongCO** [comment]
![My Messages - Inbox.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/83d600b1-ca41-4fc4-a57b-a0ab50c3b3f5)
![My Messages - Sent.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/186f1c91-1e7b-4255-80b7-0708ac9c5aa6)

1. Use existing design and interaction for filter components
2. Inbox filters: Case Status, From, Section
3. Sent filters: Case Status, To, Section
4. No filters for Completed
