### ISSUE TITLE
BUG: View Full PDF link on Safari mobile no longer can be opened in new tab

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8360]
**Describe the Bug**
When tapping the View Full PDF link on a document in the Document View on iPad/mobile Safari browser, the link can no longer be opened in a new tab.

According to user reports this was introduced in the 10/29 deployment.

**Business Impact/Reason for Severity**
This is a problem because currently on iOS the only way to scroll through a multi-page document on mobile devices is to open them in a new tab, which can no longer be done.

**In which environment did you see this bug?**
PROD/TEST

**Who were you logged in as?**
Judge Buch

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Responding to bug report

**To Reproduce**
1) Go to a document (any document) on the Document View in DAWSON on an iPad or mobile device Safari browser
2) Tap the `View Full PDF` link

**Expected Behavior**
Document opens in a new tab.

**Actual Behavior**
Nothing happens. New tab does not open.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
A refactoring was completed which moved the call to `window.open()` outside of an asynchronous operation. Safari treats the window.open() method as an async call but doesn't mark it as async. When it was moved to be called after the async call that retrieves the URL to load, the window.open() method had not yet "resolved" so it was attempting to set the URL on an undefined object. 

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by rachelschneiderman** [comment]
Bug fix PR: https://github.com/ustaxcourt/ef-cms/pull/2825

**Comment by rosiehsmith** [comment]
This is deployed to https://app.exp2.ustc-case-mgmt.flexion.us/messages/my/inbox as the `test` environment is blocked, and this bug does not require prod-like data.

**Comment by rachelschneiderman** [comment]
DOD PR: https://github.com/flexion/ef-cms/pull/9722

**Comment by rachelschneiderman** [comment]
We are seeing differences in behavior across iOS devices. The fix was deployed to flexion/exp2 and I confirmed I could open the PDF in a new tab using xcode simulator for iOS 15.1 and 16.0 on both an iPhone and iPad. @rosiehsmith tried reproducing the bug with her iPhone (iOS v16) on exp2 and also was able to open the document in a new tab.  Rosie also tried on her iPad (iOS 14.7) and was able to open a document in a new tab. @cholly75 tried with his iPad and was unable to open the document in a new tab.

@cholly75 Will talk with Judge Buch and see if he can log into `flexion/exp2` to test the fix as well. Deploying to `ustc/test` would be preferable but it's still blocked from being able to deploy to. He will also ask if the desired behavior is 'tap' to open a document in a new tab or 'tap and hold'.

@rosiehsmith and @rachelschneiderman Will investigate the feasibility of enabling 'tap and hold' to open a new tab and also enabling scrolling on multi-page pdfs in the document view while we wait for an answer.

**Comment by rachelschneiderman** [comment]
@rosiehsmith and I investigated the feasibility of enabling scrolling on multi-page PDFs in the document view for Safari mobile browser. It seems that Apple intentionally disables that behavior in favor of opening a PDF in a new tab to make use of the 'Quick Look' feature.

https://discussions.apple.com/thread/250581755

**Comment by cholly75** [comment]
@rachelschneiderman Aw, nerts. Thanks for checking on that.

**Comment by rachelschneiderman** [comment]
https://github.com/ustaxcourt/ef-cms/pull/2859
https://github.com/flexion/ef-cms/pull/9737

**Comment by rosiehsmith** [comment]
For some extra background, since the nature of the reported bug has changed:

It appears that “View Full PDF” link was broken post-10/29, and a new tab could not be opened in Safari. We have fixed this behavior with this issue.

Tapping and holding the “View Full PDF” does not appear to be something that was an option, even prior to 10/29. We attempted to tap & hold to open the link by using an older version of the app from 9/2022, but the button is still interpreted as text. No code was changed to alter this specific behavior. Tap & hold does not work on buttons, it only works on links, and “View Full PDF” has always been a button.
