### ISSUE TITLE
Streamline Trial Session Data Returned for Dashboards

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8379]
As a judge and chambers users, so that I am not logged out immediately upon viewing my dashboard, I need the logic that returns my relevant trial sessions to query specifically for sessions I am associated to. 

On 12/19/22 we started experiencing immediate logouts for judge and chambers users; the root cause of this was traced to the accumulated volume of overall trial session data. Apparently the logic responsible for displaying relevant sessions on the user dashboard queries for all available trial sessions before filtering them for applicable user data; the amount of data initially returned in the query exceeds the size limitation and causes an automatic logout for the user.

Based on recommendations by @codyseibert this can be refined to query for the specific needed data initially, preventing the need to return the entirety of the trial session data and avoiding the forced logout symptom described above. 

## Acceptance Criteria
* Judges and chambers users can log in to DAWSON and be presented with their dashboard reflecting Current and Upcoming trial sessions associated to them.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by mmarcotte** [comment]
When deployed, we will need to restore the following trial sessions:

* D8AEBF7F-A2E5-41A3-821E-CCF9B89785DD
* 477BB40D-B7AA-43DC-852D-12BBECBD1CCD
* 841A7670-A2EE-4E9A-AF90-E33F189BD286
* 729B20A7-F8E6-4217-93BD-0276610B54E9
* D4210BC9-FDF1-4CB1-993F-00299F83A4E5
* EEF8EAB2-8B9A-43A9-B5A3-6ACB158C73BC
* 5CDD5081-FEF2-4B6F-B140-337C0EAB227C
* 41693117-043E-44C2-9224-9A88978C8F6E
* 4DFAF0D5-F21B-4EE0-9491-D7C257B19F0F
* 8744FF21-020A-4493-82C1-1848AD716EE6

**Comment by ttlenard** [comment]
Testing Feedback 12/20/2022.
@codyseibert  @cholly75 

I went through and clicked on everything from the Session copy page and Session detail page as a Judge and CA.  Results are expected.  Testing looks great!  Here are my testing notes.

1. Judge/CA can log in and view dashboard
2. Can Click on upcoming and recent trial sessions - session copy page opens 
3. From Session Copy page:
     - Print with/without notes
     - Add trial status
     - Add Case Note
     - Delete Case Note
     - Add Session Note
     - Delete Session Note
     - Update Filter view 
     - Download all Cases
     - Open Cases by from session copy by clicking on Docket number
     - Can then view documents as you normally would.
4. Once in a Case that is scheduled for trial, Judge/CA can click on Case information tab, and then click on the Trial Session link to return to the Session Copy Page.
5. Can click on the View All Session Info Link
6. From the View All Session Info page
     - Print the trial session detail page
     - Open Cases by from trial session detail page by clicking on Docket number
     - Can then view documents as you normally would.
     - Can navigate around the Open, Inactive, All tab
7. Can work with the recent messages from the dashboard as you normally would

What the Judge/CA **CANNOT** do at this point in time (with the payload exceeding our limit). This is to be expected until the next story is deployed. (#9759)
1. Judge/CA cannot click on the Trial Sessions Tab - Results in the user getting logged out
2. Judge/CA cannot click on the Edit link from the Trial Session Detail page


When reviewing the JSON in the console, I see that the trial-session json now only shows the data for the specific judge, rather than EVERY judge and EVERY trial session. I do have some things to consider for the future:

1. Do we need to include the case order?  There is still ALOT of data getting returned.  Will we eventually exceed the limit at some point in the future even if we have filtered by Judge in this view?
2. Maybe we could just display the upcoming and recent sessions in the json?  Do we need to list out ALL of the cases that the Judge has ever had?  Maybe we could make this match whatever is displayed in the UI?
3. Is there other data that we could not display that could free up some space?
