### ISSUE TITLE
Reporting: Case Status Audit Trail

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8383]
As a Court manager, so that I can accurately track a case lifecycle in DAWSON, I need to be able to see a history of changes to the Case Status.

In DAWSON, a case will be assigned multiple statuses over the course of its life depending on how far the case has progressed. Some of these status changes are done manually, while others occur automatically in DAWSON as a result of functionality (e.g., calendaring, entry of a decision, elapsed time). Right now, only the current status of the case is displayed as part of the case record, which can make it difficult to infer past system behavior or case activity that may have occurred. 

Additionally, changes in case status can be useful as milestones w/r/t reporting out on processes both at the macro- and operational level (e.g., tracking how many cases were appealed in the same quarter that they were closed, or how many cases flipped to Ready for Trial in a given month).

When answering specific questions about a case (including troubleshooting potential issues in workflow or data) or aggregating case data for reporting, we would like to be able to pinpoint dates of status changes to a case throughout its life in DAWSON.

## Acceptance Criteria
* When the Case Status is changed either manually or via automation the change is recorded with the date of change, the new status assigned to the case, and whether the change was made by a specific user or by a system process
* Full record of changes to Case Status can be viewed in the context of the Case Information in DAWSON by any internal court user
* Changes to Case Status are logged to the case every time such a change occurs
* Do not expose case audit trail data externally

## Notes
* The list of Case Status changes is *never* editable in DAWSON

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**

![Case status history 9767.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/2bc33572-c3e3-4fcc-9c7c-906f9fbe58f6)

1. Add "History" tab next to "Statistics"
2. Add table of data points with label "Case Status"
3. Sort order is from oldest to newest

**Comment by ttlenard** [comment]
## Test Cases


#### 1) Court User sees a new History Tab located within the Case Information Tab.

- Log in as any Court User
- Navigate to a case
- Click on the Case information tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a new History Sub-tab located after the Statistics tab.

*Repeat this test with various Court Users to ensure that the History tab is available to all internal court users.



#### 2) Court User can view the case status history of a case when viewing the information on the new History tab

- Continuing from the previous test
- Click on the History tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - New table with a title of Case status is present.
- [x] **NEW FUNCTIONALITY** - Columns in the table include Date Changed, Case Status, and Changed by.
- [x] **NEW FUNCTIONALITY** - There is a Count available on the top right of the table
- [x] If viewing an older case, there will not be any case status history data available yet in the table

*Repeat this test with various Court Users to ensure that the History tab is available to view for all internal court users.



#### 3) Court User manually updates the Case Status in a case. The update is reflected appropriately in the table on the History tab.

- Log in as a Docket Clerk or CotC user
- Navigate to a case
- Click on the Case information tab
- Click on the Edit Case Status/Caption link
- Change the case status to something else and save.
- Click on the History tab.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Date Changed column shows todays date
- [x] **NEW FUNCTIONALITY** - The Case Status reflects the new status that you selected above
- [x] **NEW FUNCTIONALITY** - The Changed by reflects the logged in user's name.
- [x] **NEW FUNCTIONALITY** - The Count is at 1.

*Repeat this test by changing the Case status manually a few times.  Go and check the History tab to ensure that the changes are reflected correctly.

- [x] **NEW FUNCTIONALITY** - The sorting order of the data in the table is oldest to newest by case status change.
- [x] **NEW FUNCTIONALITY** - The Count reflects the total number of rows in the table.



#### 4) Court user adds a decision type document to a case; Case status is automatically updated; Case status information on the History tab is updated to reflect system changes.

- Log in as a docket clerk or CotC user
- Navigate to a case that is in an open status
- Click on the Create menu
- Select Order or Notice
- Select one of the Dismissal/Decision types of Orders (see list below)
- Add some text to the draft, save and then apply the signature, click save signature
- Click on the Add docket entry link on the Drafts page
- Add the judges name and a description, click save and serve.
- Click Yes, Serve.
- You should receive the green confirmation banner indicating that the document was served, and the case status in the header should have been automatically updated.
- Click on the Case information tab
- Click on the History sub-tab.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Date Changed column shows todays date
- [x] **NEW FUNCTIONALITY** - The Case Status reflects the new case status that was automatically adjusted after the order was processed.
- [x] **NEW FUNCTIONALITY** - The data in the Changed by column should indicate "System", since the case status update was trigged by a system rule. 
- [x] **NEW FUNCTIONALITY** - The sorting order of the data in the table is oldest to newest by case status change.
- [x] **NEW FUNCTIONALITY** - The Count reflects the total number of rows in the table.


* Repeat this test by adding docket entries for all of the different types of decision documents that automatically close a case when added to the docket record 
- [x] Stipulated Decision
- [x] Decision
- [x] Order and Decision
- [x] Order of Dismissal and Decision
- [x] Order of Dismissal
- [x] Order of Dismissal for lack of Jurisdiction 



#### 5) Court user manually adds a case to a trial session; Case status is automatically updated; Case status information on the History Tab is updated to reflect system changes.

- Log in as a Docket Clerk
- Navigate to a case that is in the general docket 
- Click on the Case Information tab
- Click on Add to trial link
- Select a trial session, and then click add case
- The case's status in the header will update to Calendared
- Click on the History tab

Expected results:
- [x] **NEW FUNCTIONALITY** - The Date Changed column shows todays date
- [x] **NEW FUNCTIONALITY** - The Case Status reflects the new case status of Calendared. 
- [x] **NEW FUNCTIONALITY** - The data in the Changed by column should indicate "System", since the case status update was trigged by a system rule. 
- [x] **NEW FUNCTIONALITY** - The sorting order of the data in the table is oldest to newest by case status change.
- [x] **NEW FUNCTIONALITY** - The Count reflects the total number of rows in the table.



#### 6) Case is calendared using the set calendar function; Case status is automatically updated; Case status information on the History Tab is updated to reflect system changes.

- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on the New tab
- Click on the City, State link for a trial session
- Ensure that all of the required trial session assignments and info are filled in.
- Ensure that some cases have been QC'd.
- Click Set Calendar
- Click Done on the Paper service screen if any cases have parties receiving paper service
- Click on the docket number of a few of the cases that you just calendared
- Click on the Case information tab
- Click on the History Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Date Changed column shows todays date.
- [x] **NEW FUNCTIONALITY** - The Case Status reflects the new case status of Calendared. 
- [x] **NEW FUNCTIONALITY** - The data in the Changed by column should indicate "System", since the case status update was trigged by a system rule. 
- [x] **NEW FUNCTIONALITY** - The sorting order of the data in the table is oldest to newest by case status change.
- [x] **NEW FUNCTIONALITY** - The Count reflects the total number of rows in the table.



#### 7) Calendared case is removed from trial session and the case status manually updated by the clerk; Case Status information on the History tab is updated to reflect the appropriate changes made by the user.

- Log in as a Docket clerk
- Navigate to a calendared case
- Click on the Case information tab
- Click on the Edit link in the Trial-Calendared Card
- Click on the Remove from Trial link
- Enter a Disposition and then select a Case Status
- Click Remove Case
- The Case Status in the header should be updated to the case status that you selected
- Click on the History tab

Expected Results
- [x] **NEW FUNCTIONALITY** - The Date Changed column shows todays date.
- [x] **NEW FUNCTIONALITY** - The Case Status reflects the new case status that you selected.
- [x] **NEW FUNCTIONALITY** - Changed by displays the clerks name that made the case status update.
- [x] **NEW FUNCTIONALITY** - The sorting order of the data in the table is oldest to newest by case status change.
- [x] **NEW FUNCTIONALITY** - The Count reflects the total number of rows in the table.



#### 8) Case that was in a NEW status is served to the IRS, Case Status information on the History tab is updated to reflect the appropriate changes made by the system.

- Log in as a Petitions Clerk
- Click on Document QC
- Click on Section Document QC
- Click on a Petition that is in the New Status
- QC the petition, and then click Serve to the IRS
- The Case Status in the Header should have been updated automatically to General Docket - Not at issue
- Click on the Case information tab
- Click on the History tab

Expected Results
- [x] **NEW FUNCTIONALITY** - The Date Changed column shows todays date.
- [x] **NEW FUNCTIONALITY** - The Case Status reflects the change to General Docket - Not at Issue
- [x] **NEW FUNCTIONALITY** - The data in the Changed by column should indicate "System", since the case status update was trigged by a system rule. 
- [x] **NEW FUNCTIONALITY** - This should be the first status change reflected for this case
- [x] **NEW FUNCTIONALITY** - The Count reflects the total number of rows in the table.



#### 9) Case that was in a General Docket - Not at issue Case status, and has an answer filed by the IRS has just passed the 45 day since petition was filed mark; Case Status information on the history tab is updated to reflect system changes.

- Log in as any court user
- Navigate to a case that was submitted over 45 days ago, and that also has an answer filed on the case (we are not going back in time to populate status changes, this will have to be a case that JUST had a status update AFTER this code has been deployed to the test environment)
- Click on the Case information tab
- Click on the History tab

Expected Results
- [x] **NEW FUNCTIONALITY** - The Date Changed column shows todays date.
- [x] **NEW FUNCTIONALITY** - The Case Status reflects the change to General Docket - At Issue - Ready for Trial
- [x] **NEW FUNCTIONALITY** - The data in the Changed by column should indicate "System", since the case status update was trigged by a system rule. 
- [x] **NEW FUNCTIONALITY** - The Count reflects the total number of rows in the table.



#### 10) All Court users can view the data in the Case History tab

- Log in as all of the different types of Court Users
- Navigate to some of the cases from above that you were updating the case statuses for

Expected Results:
- [x] **NEW FUNCTIONALITY** - All court users have access to the History tab
- [x] **NEW FUNCTIONALITY** - All Court users can view the data in the History table and see the case status updates 
- [x] **NEW FUNCTIONALITY** - Data in the table is represented per the A/C and design.



#### 11) Case status history is available in the Case JSON for internal Court users (Dev Determination on this one!)

- Log in as any Court user
- Open up the console, and be sure that you are on the Network tab 
- Navigate to a case that has data in the History tab for case status changes.
- Click on the Case json entry in the console

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case history is documented in the Case JSON 



#### 12) Case Status History is not available in the Case JSON for external parties on a case.

- Log in as a party to a case that has data available in the History tab for case status changes.
- Open up the console, and be sure that you are on the Network tab 
- Navigate to a case that has data in the History tab
- Click on the Case json entry in the console

Expected Results:
- [x] The Case history is NOT available in the Case JSON 

*Repeat this test with all of these party types:
- [x] Petitioner
- [x] Private Practitioner
- [x] IRS Practitioner
- [x] Intervenor
- [x] Participant



#### 13) Case Status History is not available in the Case JSON for a public user.

- Navigate to the DAWSON search page.
- Open up the console, and be sure that you are on the Network tab 
- Type in the docket number for a case that has data available in the History tab for case status changes.
- Click Search
- Click on the Case json entry in the console

Expected Results:
- [x] The Case history is NOT available in the Case JSON  

*Repeat this test with the Terminal User

**Comment by cholly75** [comment]
As per discussion during UX Review - for initial New status row for e-filed petitions, we can simply put "Petitioner" or "Practitioner" based on the role of the filer as the value for Changed By. - cc: @ttlenard @swongCO @liadmccabe @katiecissell

**Comment by swongCO** [comment]
**UX Review feedback**
• for the empty state message, remove "on this case"
• per Chris comment above, add a New status row to efiled petitions (it only shows up for paper petitions)

**Comment by swongCO** [comment]
Per discussion with @TomElliottFlexion, second bullet from ux feedback above can be ignored. New status row does get added for new petitions created, not ones already in progress.

**Comment by ttlenard** [comment]
@codyseibert @Absolutestunna @TomElliottFlexion 

All tests pass! Thank you!
