### ISSUE TITLE
Prevent Deletion of Served Documents When Draft is Deleted

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8441]
As a party to a case, so that I can trust that the docket record accurately reflects documents served in my case, I need to prevent accidental deletion of documents that have been served and placed on the record.

While investigating a missing document reported by the IRS, we discovered a method by which a user can unintentionally delete a docket record entry. We need to explicitly prevent deletion (accidental or otherwise) of any docket record entry saved and served.

The steps discovered in this case were:

1) Create a draft document for a case on Computer/Window A
2) Open the drafts tab for the case on Computer/Window B
3) Save and serve the document on Computer/Window A. Note that service is performed and the document is added to the docket record.
4) Delete the "draft" document on Computer/Window B.
5) Refresh the docket record view for the case on either computer. Note that the docket entry has been removed. Links issued in service documents for the entry no longer work.

## Acceptance Criteria
* Deletion of a Draft document will *not* delete the document if it has been served.
* Attempting to delete a Draft document that has been served results in a message to the user attempting to delete the draft informing them that the document has been served.

## Notes
- From within the delete interactor we will likely need to check to see if the document being deleted has already been served.
- Not sure if we want to address this in this story or not, but while writing test cases for this story, I notice that if a user attempts to edit a notice that has already been served, they get a never ending spinning wheel and a type error:
- ![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/96052495-0590-44da-8033-b231408f37f6)
- Not sure if we want to address this in this story or not, but while writing test cases for this story, I notice that if a user attempts to edit an Order that has already been served, they get a 400 error.
- ![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/8ab71942-f4d9-406b-b2a2-22d43baf808e)
- ![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/da82325c-8eb5-45b3-a43a-3b53feb6f7aa)

## DOD
- [ ] Look into unifying how errors are captured on the frontend.
- [ ] Make a sequence to get the full case. 

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
If a user tries to delete a document draft and that draft was already served, a new modal should appear that has
- a header of "Document Already Served"
- a description of "This action could not be completed because this document was already served."
- a primary button that says "Close and Refresh" 
- There should be NO close button on the top right

We have identified this scenario can occur with orders with signatures, orders without signature, and notices. 

![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/f8430160-c0ae-475f-86f9-f6dd6ff1f278)



Figma file link https://www.figma.com/file/L3j41x6FdMblljxsSFZ4ea/USTC-%7C-Prevent-Deletion-of-Served-Documents-When-Draft-is-Deleted-%7C-10018?type=design&node-id=46%3A2295&t=QYYggIMPHtAWqEDE-1

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user has two windows open on their computer displaying the same signed Order in the drafts tab of a case; Clerk serves the Order in one window, attempts to delete the Order in the second window; modal indicating that the document was already served is displayed.

This test has some set up
- Ensure that you have added a party to a case that you can receive service emails for (petitioner or Private Practitioner).
- Next, Log in as a judge or a CA
- Navigate to the case and click the Create button
- Select Order or Notice
- Create an Order and sign it
- Next, as a docket clerk, navigate to the case that you just created a draft order in
- Duplicate the tab so that you have two windows open with the draft order.
- In the first tab, click Add Docket Entry
- Select a Service Stamp, and then Click Save and Serve.
- Click Yes, Serve
- You should have received the green confirmation banner indicating the document was served.
- Ensure that the Order you just served is on the docket record. Take note of the document Index Number.
- Check your email to ensure that you received a service email about the Order (including the information about the document index number for the document)
- Next, from the second tab (you should still be logged in as the docket clerk), click on the delete button from the drafts tab.  

Expected Result
- [x] **NEW FUNCTIONALITY** - A new modal appears that matches what is in the mockup.



#### 2) Court User clicks the Close and Refresh button; user is navigated to the drafts tab, there is no longer the draft Order present, Order is served on the docket record.

- Continuing from the previous test
- Click Close and Refresh

Expected Results:
- [x] **NEW FUNCTIONALITY** - The user is navigated back to the drafts tab
- [x] **NEW FUNCTIONALITY** - The draft Order is no longer present in the drafts tab
- [x] The Order that was Served in Test case 1 remains on the docket record.
- [x] Service was only sent to the parties once.



#### 3) Court user has two windows open on their computer displaying the same unsigned Order document in the drafts tab of a case; Clerk serves the Order in one window, attempts to delete the Order in the second window; modal indicating that the document was already served is displayed.

This test has some set up
- Ensure that you have added a party to a case that you can receive service emails for (petitioner or Private Practitioner).
- Next, Log in as a judge or a CA
- Navigate to the case and click the Create button
- Select Order or Notice
- Create an Order, but do not sign it.
- Next, as a docket clerk, navigate to the case that you just created a draft order in
- Duplicate the tab so that you have two windows open with the draft order.
- In the first tab, click Apply signature
- Apply a signature and save it.
- Click the Add Docket Entry link
- Select a Service Stamp, and then Click Save and Serve.
- Click Yes, Serve
- You should have received the green confirmation banner indicating the document was served.
- Ensure that the Order you just served is on the docket record. Take note of the document Index Number.
- Check your email to ensure that you received a service email about the Order (including the information about the document index number for the document)
- Next, from the second tab (you should still be logged in as the docket clerk), click on the delete button from the drafts tab.  

Expected Result
- [x] **NEW FUNCTIONALITY** - A new modal appears that matches what is in the mockup.



#### 4) Court User clicks the Close and Refresh button; user is navigated to the drafts tab, there is no longer the draft Order present, Order is served on the docket record.

- Continuing from the previous test
- Click Close and Refresh

Expected Results:
- [x] **NEW FUNCTIONALITY** - The user is navigated back to the drafts tab
- [x] **NEW FUNCTIONALITY** - The draft Order is no longer present in the drafts tab
- [x] The Order that was Served in Test case 3 remains on the docket record.
- [x] Service was only sent to the parties once.


#### 5) Court user has two windows open on their computer displaying the same signed Notice in the drafts tab of a case; Clerk serves the Notice in one window, attempts to delete the Notice in the second window; modal indicating that the document was already served is displayed.

This test has some set up
- Ensure that you have added a party to a case that you can receive service emails for (petitioner or Private Practitioner).
- Log in as a Docket Clerk
- Navigate to the case
- Select Order or Notice
- Create Notice 
- Save the notice
- You should be on the drafts tab
- Duplicate the tab so that you have two windows open with the draft Notice.
- In the first tab, click Add Docket Entry
- Click Save and Serve
- Click Yes, Serve
- You should have received the green confirmation banner indicating the document was served.
- Ensure that the Notice you just served is on the docket record. Take note of the document Index Number.
- Check your email to ensure that you received a service email about the Notice (including the information about the document index number for the document)
- Next, from the second tab (you should still be logged in as the docket clerk), click on the delete button from the drafts tab.  

Expected Result
- [x] **NEW FUNCTIONALITY** - A new modal appears that matches what is in the mockup.



#### 6) Court User clicks the Close and Refresh button; user is navigated to the drafts tab, there is no longer the draft Notice present, Notice is served on the docket record.

- Continuing from the previous test
- Click Close and Refresh

Expected Results:
- [x] **NEW FUNCTIONALITY** - The user is navigated back to the drafts tab
- [x] **NEW FUNCTIONALITY** - The draft Notice is no longer present in the drafts tab
- [x] The Notice that was Served in Test case 3 remains on the docket record.
- [x] Service was only sent to the parties once.
