### ISSUE TITLE
Adjust Timing On NOTT Reminder

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8517]
As a petitions clerk, so that I have flexibility in issuing NOTTs, I need to extend the period during which the NOTT reminder appears/notices can be generated to 25 days prior to the trial start date.

Due to unforeseen circumstances the Court sometimes will decide to issue NOTTs for a trial session several days past the actual 30-day mark prior to a trial session start date. Currently in these cases these must be manually docketed, as the reminder clock and the option to generate these disappears (as per current design) once the trial start date has hit the 29-day pretrial mark.

Case Services has requested that we adjust this to happen once the trial is 25 days from its start date, effectively adding another 4 days to the period in which the reminder appears and these notices can be generated. 

See ustaxcourt/ef-cms#8542 for the original story implementing the NOTT reminder and ustaxcourt/ef-cms#8543 for the original story implementing the NOTT generation.

## Acceptance Criteria
* NOTT reminder clock appears for the trial session until 25 days prior to the trial session start date
* NOTTs can be generated at any point while the reminder appears for the trial session
* No changes to functionality for the NOTT generation/content

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk accesses the Open Trial Sessions page; Calendared trial sessions that are between 25-35 calendar days from the scheduled session have a clock icon next to the date.

- Log in as a Petitions Clerk.
- Click on the Trial Sessions tab.
- Be sure that you are on the Open Tab.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Sessions that are between 25 - 35 calendar days now have a clock icon next to the session date.
- [x] Regression test - If you hover your cursor over the clock icon, a tooltip states "The 30-day notice is due before xx/xx/xx (where the date = the 30 day mark).
- [x] Regression test - Session information page has the yellow alert banner for all cases 25-35 days from trial start date

*You can edit certain trial session start dates to see the clock icon/yellow alert on the session info page appear/disappear based on the date.
- [x] If 36+ days, no clock icon/no alert
- [x] If 24 or < days from trial start date, no clock icon/no alert

*Repeat this test with a CSS and CotC user



#### 2) Petitions Clerk sets a calendar, schedules the start date to 36 days from today; The following day, as the Petitions clerk, check the Trial Sessions page; New clock icon and warning banner are present.

This test case has some set up:

- Log in as a Petitions Clerk
- Create a new Trial Session that has a start date of 36 days from today
- Select eligible cases
- Set the calendar

The next day...
- Log in as the Petitions Clerk again
- Click on the Trial Sessions Page
- Find the trial session that you created yesterday on the Open tab

Expected Results:
- [x] Test cases 1 passes


#### 3) Petitions Clerk sets a calendar, schedules the start date to 25 days from today; The clock icon and yellow alert banner are present.

- Log in as a Petitions Clerk
- Create a new Trial Session that has a start date of 25 days from today
- Select eligible cases
- Set the calendar

Expected Results:
- [x] Test cases 1 pass



#### 4) Petitions Clerk sees the clock icon and yellow alert banner for a session that is 25 days from today; The following day the clerk views the same session; Clock icon and yellow alert banner are no longer present.

This test case has some set up:
- Log in as a Petitions Clerk
- Create a new Trial Session that has a start date of 25 days from today
- Select eligible cases
- Set the calendar
- The clock icon and the yellow alert banner should be present

The next day...
- Log in as a Petitions Clerk
- Click on the Trial Sessions Page
- Find the Trial Session from above

Expected Results:
- [x] **NEW FUNCTIONALITY** - The clock icon is no longer present on the trial session page
- [x] **NEW FUNCTIONALITY** - The yellow alert banner is no longer present on the Session information page.


### Regression Testing ###


#### 5) Petitions Clerk opens one of the trial sessions that has a clock icon; new yellow warning banner is present underneath the Session Information header.

- This is a regression test
- Continuing from the previous test.
- Click on the City, State link for a trial session that has the clock icon.

Expected Results:
- [x] Yellow warning banner is present under the Session Information header; no change in functionality.
- [x] There is a Serve/Dismiss link available

*Repeat this test with a CSS and CotC user



#### 6) Clerk clicks the "Serve/Dismiss" link in the yellow alert banner; pop-up modal displays asking for confirmation.

- This is a regression test
- Continuing from the previous test.
- Click on the "Yes Serve" button in the modal

Expected Results:
- [x] Generating Notices modal 
- [x] Creating Paper Service PDF modal
- [x] Print paper service screen with appropriate notices
- [x] After clicking the Printing complete button, user is navigated back to the Session information page
- [x] After clicking on the Yes, Dismiss link in the yellow warning banner, a pop-up modal displays
- [x] After Clicking the Yes button, the modal closes and the yellow alert banner disappears
- [x] The clock icon is no longer present on the session information page
- [x] Service was sent appropriately 
- [x] Document is docketed on the docket record appropriately.
- [x] Service/docketing of the notice is only for open cases

*Repeat this test with a CSS and CotC user



#### 7) Clerk can cancel and close out of the Serve 30-DAy Notice pop-up modal 

- This is a regression test
- As a Petitions Clerk
- Click on the City, state link of a trial session with a clock icon
- Click on the Serve/Dismiss link in the yellow alert
- From the pop up modal, click the cancel link.

Expected Results:
- [x] Pop-up modal closes; user is back on the session information page.

*Repeat this test but instead of clicking cancel, click close.
*Repeat this test with a CSS and CotC user



#### 8) Clerk selects "Dismiss Reminder" in the pop-up modal; Yellow alert banner disappears, clock icon is no longer displayed on the Trial Sessions page.

- This is a regression test
- Continuing from the previous test.
- Click on the Serve/Dismiss link in the yellow alert banner.
- Click on the Dismiss Reminder button in the pop-up modal.

Expected Results:
- [x] The yellow alert banner disappears
- [x] The clock icon is no longer present for the trial session on the session information page

*Repeat this test with a CSS and CotC user



#### 9) Other Court Staff are able to see the 30 day notice yellow alert banner and clock icon, but are unable to clear the yellow alert banner from view.

- This is a regression test
- Log in as any Court user besides Petitions Clerk, CSS, or CotC.
- Click on the Trial Sessions tab.
- Click on the City, State of a session that has the clock icon.

Expected Results:
- [x] Yellow alert banner is present under the Session Information header
- [x] Clerk is unable to dismiss the alert banner.

*Be sure to repeat this with all of the other court roles (besides Petitions clerk, CSS, or CotC) to ensure that the alert banner is not dismissible.
