### ISSUE TITLE
Add Date of Trial Session to Remote NOTTs

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8575]
As a pro se petitioner with a case calendared for a remote session, so that I can be sure of my trial date, I need the date of my trial session added to the language in the NOTT reminder sent by the Court.

In response to several questions from pro se petitioners to the Court, we would like to add the date of their trial session to the NOTTs generated for both Remote and Standalone Remote trial sessions. Adding this information to the NOTT should make it clear when their session is scheduled for.

## Acceptance Criteria
* Text on the NOTT generated for Remote trial session cases is updated to include the Date of the trial session for which the case is calendared in the following manner.

From:
The parties are reminded that this case is calendared for trial or hearing at the Trial Session beginning at 10:00 AM local time at the location shown above, as a remote proceeding using Zoomgov

To:
The parties are reminded that this case is calendared for trial or hearing at the Trial Session beginning at 10:00 AM local time on [DATE] at the location shown above, as a remote proceeding using Zoomgov

* Text on the NOTT generated for Standalone Remote trial session cases is updated to include the Date of the trial session for which the case is calendared in the following manner.
 
From:
The parties are reminded that this case is calendared for trial or hearing at the Trial Session beginning at 1:00 PM Eastern time (ET), as a remote proceeding using Zoomgov.

To:
The parties are reminded that this case is calendared for trial or hearing at the Trial Session beginning at 1:00 PM Eastern time (ET), on [DATE] as a remote proceeding using Zoomgov.

* The Date of the trial session is formatted as [Month Day, Year] in both cases.
* The Month portion of the date is spelled out; Day and four-digit Year are numbers.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk serves a 30-Day Notice of Trial on a Remote session; text changes outlined in the A/C are reflected appropriately in the Notice.

- Log in as a Petitions clerk
- Click on trial sessions
- Find a remote trial session that has a clock icon next to the Start data (if there isn't one, you will need to adjust the start date on an upcoming trial session so that it is 35 days from the trial)
- Click on the City, State link of the trial session
- Click on the Serve/Dismiss link in the yellow alert banner
- Click Yes, Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Printed version of the NOTT now has the text: "The parties are reminded that this case is calendared for trial or hearing at the Trial Session beginning at 10:00 AM local time on [DATE] at the location shown above, as a remote proceeding using Zoomgov."
- [x] **NEW FUNCTIONALITY** - The [DATE] information matches the date of the trial. 
- [x] **NEW FUNCTIONALITY** - The formatting for the date field is Month (spelled out), Day, and four-digit year.

*If there are no paper service parties, check the docket record of a case that is on the session and check the docketed Notice.



#### 2) Petitions Clerk serves a 30-Day Notice of Trial on a Standalone remote session; text changes in the A/C are reflected appropriately in the Notice.

- Log in as a Petitions clerk
- Click on trial sessions
- Find a Standalone remote trial session that has a clock icon next to the Start data (if there isn't one, you will need to adjust the start date on an upcoming trial session so that it is 35 days from the trial)
- Click on the City, State link of the trial session
- Click on the Serve/Dismiss link in the yellow alert banner
- Click Yes, Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Printed version of the NOTT now has the text: "The parties are reminded that this case is calendared for trial or hearing at the Trial Session beginning at 1:00 PM Eastern time (ET), on [DATE] as a remote proceeding using Zoomgov."
- [x] **NEW FUNCTIONALITY** - The [DATE] information matches the date of the trial. 
- [x] **NEW FUNCTIONALITY** - The formatting for the date field is Month (spelled out), Day, and four-digit year.

*If there are no paper service parties, check the docket record of a case that is on the session and check the docketed Notice.

**Comment by jasonfu9966** [comment]
Question from working on this:
The current text reads, "... Trial Session beginning at **10:00 AM local time at the location shown above,** as a remote proceeding..." with the time and "location shown above" bolded.
After the text change, it will read "...Trial Session beginning at **10:00 AM local time on [date] at the location shown above**, as a remote proceeding..."
Is this correct emboldening or does it need to be changed?

**Comment by cholly75** [comment]
That is the correct emboldening, thanks for asking!

**Comment by ttlenard** [comment]
Testing looks good!  Thanks @jasonfu9966
