### ISSUE TITLE
Practitioner: Change "Employer" Field Name

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8621]
As a Court, so that our practitioner records more accurately reflect the nature of practitioner employment, I need the "Employer" field on the Practitioner record to be relabeled as "Practice Type".

We anticipate releasing a version of Practitioner search to the general public in Summer of 2024. Prior to doing this there are improvements/changes we want to make to a few different facets of practitioner search and records in DAWSON.

One of these changes is in nomenclature. The label "Employer" that we use for the field to designate whether the practitioner is IRS, DOJ, or Private isn't accurate in some situations, such as when an attorney is working for a non-profit, or other governmental organization. As we expose this data in the public-viewed Practitioner Search, we want to head off any objections or confusion from users. 

Additionally, this will give us future flexibility as we consider expanding our potential practitioner types, and more accurately reflect what the value in the field represents. 

## Acceptance Criteria
* Employer field on the Practitioner Record now labeled "Practice Type"
* No changes to this field's functionality or use

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Admissions clerk views an existing Practitioner Record, "Practice type" is now displayed instead of "Employer".

- Log in as an Admissions Clerk
- Click on the advanced link in the upper right corner of DAWSON
- Search for a Practitioner
- Click on the BAR number link to access the practitioner record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Employer field is now labeled "Practice type"
- [x] There is no change to the values for the practitioner (Private, IRS, DOJ)


#### 2) Admissions clerk edits an existing Practitioner record, "Practice type" is now displayed instead of "Employer".

- Continuing from the previous test 
- Check to ensure that the practitioner is not associated with any open cases (if they are, choose a different practitioner or as the practitioner, withdraw from the cases).
- Click on the edit link in the practitioner record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Employer field is now labeled "Practice type"
- [x] There is no change to the radio button values available for the practitioner (Private, IRS, DOJ)
- [x] Clerk can save the record after changing the employer for the practitioner; data saves appropriately.



#### 3) Admissions clerk creates a new practitioner record, "Practice type" is now displayed instead of "Employer".

- Log in as an admissions clerk
- Click on the Advanced link in the upper right corner of DAWSON
- Click on the Add New Practitioner button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Employer field is now labeled "Practice type"
- [x] There is no change to the values available for the practitioner (Private, IRS, DOJ)
- [x] Clerk can add the practitioner and the Practice type field is saved appropriately, displays correctly when viewing the practitioner record after save.


#### 4) Other Court users view Practitioner records, "Practice type" is now displayed instead of "Employer".

- [x] This test passes with all court users



#### 5) JSON data is updated; "Practice type" is now displayed instead of "Employer".

- Go to DAWSON login page
- Open your console
- Log in as a Practitioner

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Employer field is now labeled "Practice type" on the network/users JSON
- [x] After clicking on a case, there shouldn't be anything updated in the Case JSON for employer/Practice type - this data wasn't ever displayed there.

*Repeat this test with Private Practitioner, IRS Practitioner, and DOJ practitioner
