### ISSUE TITLE
Practitioner Search: Improve Search Results

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8623]
As a user searching for a specific practitioner, so that I can see more details at first glance when choosing the right search result, I need the results table to include more results and more nformation about each practitioner returned as a result.

We anticipate releasing a version of Practitioner search to the general public in Summer of 2024. Prior to doing this there are improvements/changes we want to make to a few different facets of practitioner search and records in DAWSON.

Currently the results list for practitioner search uses the older "Load More"/"Display 100" model instead of the pagination introduced more recently for searches/reports that may have long results lists. We would like to be able to return more than 100 results if the search warrants it, and use the pagination method of segmenting the results list.

Additionally, we would like to display more information for each individual result, including the Practitioner Type, Practice Type, and Admission Date.

## Pre-Conditions
ustaxcourt/ef-cms#8621

## Acceptance Criteria
* Practitioner Search results now include these additional columns/info for each result:
  - Practitioner Type
  - Practice Type
  - Admission Date
* Practitioner Search now loads whatever our max # of results is for displaying search results, with pagination mechanism in place instead of Load More

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by cholly75** [comment]
Estimated crazy high number for practitioner records total in the system: 15-20K

**Comment by swongCO** [comment]
**UX Notes**
Figma file: https://www.figma.com/file/sDn5MVTHF1yZWkQwLmEOyL/USTC-%7C-10281-Practitioner-Search?type=design&node-id=4%3A143&mode=design&t=ZRjLLyerQtSNFdha-1

1. Add paginator
2. Add table counter
3. Add the three columns to the right of the current set: Admission Date, Practitioner Type, Practice Type
4. Remove the 's' from Admissions Status = Admission Status
5. Spell out states
6. Alphabetize by first name from A-Z in the names column

<img width="1289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekRhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70cc01b4d3ac62d1c04cce6969d8468d32b2f126/Practitioner%20search%20results.png" alt="Practitioner search results.png" />

**Comment by TomElliottFlexion** [comment]
Note: Could be a good opportunity to examine our Dynamo access patterns- is Elastic/Opensearch necessary for this search?

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user searches for a common last name for a Practitioner by using the name search; Results list now includes pagination. 

- Log in as any Court user
- Click on the Advanced link in the upper right of the DAWSON page
- Click on the Practitioner tab
- Enter a Last name of a Practitioner that will yield many results (over 100) (example: Smith, or Jones)
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - The yellow alert that says "Displaying the first 100 matches of your search" is no longer displayed 
- [x] **NEW FUNCTIONALITY** - Paginator is now displayed at the top of the results table
- [x] **NEW FUNCTIONALITY** - Total Count is now displayed on the top right of the results table
- [x] **NEW FUNCTIONALITY** - Results now display 100 results per page
- [x] **NEW FUNCTIONALITY** - User can click next/previous to review each page of results.

*Repeat this test by searching for a less common last name, that wouldn't have more than 1 page worth of data.  Pagination does not display if not needed.

#### 2) Court user searches for a Practitioner by using the name search; Results list now includes additional columns of data about the Practitioner.

- Continuing from the previous test
- Review the Search Results

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now additional columns, including Admission Date, Practitioner Type, and Practice Type
- [x] **NEW FUNCTIONALITY** - The column for Admissions Status is now "Admission Status"
- [x] **NEW FUNCTIONALITY** - Results are alphabetized by first name A-Z
- [x] **NEW FUNCTIONALITY** - States are now spelled out, instead of abbreviated.



#### 3) Admissions clerk edits the data for a practitioner; Search results display updated information.

- Log in as an Admissions clerk
- Click on the Advanced link in the upper right of the DAWSON page
- Click on the Practitioner tab
- Enter a Last name of a Practitioner, click search
- Review the data displayed related to a specific Practitioner
- Click on the BAR number link for that Practitioner
- Click on the Edit link
- Update some of the information for this practitioner that displays in the results table
- Click save
- Navigate back to the Search page and search for that same practitioner

Expected Results:
- [x] **NEW FUNCTIONALITY** - The edits made display appropriately in the results table.



#### 4) Test the above with all Court users

- [ ] The tests above all pass with all Court Users



#### 5) Regression tests 

- [x] BAR number searching works as per usual.
- [x] Clear search works as per usual
- [x] No Matches Found displays as per usual if there are not results for either of the searches.

**Comment by swongCO** [comment]
**UX feedback**
- add paginator at the bottom of the table
- when a user clicks forward or backward to another page, the page jumps up to the anchor of the top paginator (see the custom case report)
- discussed with Kaitlyn that the ranking score is not the best for this type of search so she'll look into sorting by first name

**Comment by jasonfu9966** [comment]
Fuzzy search is NOT being implemented as part of this story. it was too fuzzy.
