### ISSUE TITLE
Fix / Investigate errors about event emitters

### ISSUE THREAD

**Issue by TomElliottFlexion** [ustaxcourt/ef-cms#8651]
As an engineer, so that I can have confidence that we don’t have memory leak issues, I need address the warnings being reported about `MaxListenersExceededWarning` that show up during test running and running the app locally.
```
  Advanced search
    case - by name
      ✓ should route to case detail when a match is found and the user clicks on the docket record link in the table (3372ms)
    case - by docket number
(node:7795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:7795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
      ✓ should display "No Matches Found" when case search yields no results (1958ms)
      ✓ should route to case detail when a case search match is found (1698ms)
    opinion
      ✓ should display results when a keyword and docketNumberWithSuffix is provided (4537ms)
(node:7795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 unpipe listeners added to [Console]. Use emitter.setMaxListeners() to increase limit
(node:7795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 error listeners added to [Console]. Use emitter.setMaxListeners() to increase limit
(node:7795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 drain listeners added to [Console]. Use emitter.setMaxListeners() to increase limit
(node:7795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 close listeners added to [Console]. Use emitter.setMaxListeners() to increase limit
(node:7795) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 finish listeners added to [Console]. Use emitter.setMaxListeners() to increase limit
```

## Pre-Conditions:
- none

## Acceptance Criteria:
- All github actions pass without any `MaxListenersExceededWarning` reports
- Running the app locally does not trigger `MaxListenersExceededWarning`
- If we need to raise `emitter.setMaxListeners` , a valid reason is documented

## Pain Avoided/Frustration Saved:
- Might be exposing a performance issue
- Confidence that we have addressed or don’t have a memory leak

## Breadth/Pervasiveness of Problem:
- Seems to occur in tests and running api locally

## Complexity of Problem (Low, Medium, High) and Why it's Complex:
- complex because we don’t have any immediate insight as to why these warnings are occurring.

## Notes
- here is an example of a [github action with the warnings](https://github.com/ustaxcourt/ef-cms/actions/runs/4534804805/jobs/7989450900?pr=3339 "‌") getting reported
- The event emitter warning is occurring in the same node process as "npm run start:api". It is the api which gives these warnings.

**Comment by Mwindo** [comment]
Quick update: I haven't done enough to "formally" assign to myself, but I am fairly confident that these issues are coming up because of our [winston logger](https://github.com/ustaxcourt/ef-cms/blob/2c8f2a41971784e9fbe6692944ef7776a7f21769/package.json#L102). I replaced my [nodemon line in run-local.sh](https://github.com/ustaxcourt/ef-cms/blob/2c8f2a41971784e9fbe6692944ef7776a7f21769/run-local.sh#L60) with `nodemon --delay 1 -e js,ts --ignore web-client/ --ignore dist/ --ignore dist-public/ --ignore cypress/ --exec "node --trace-warnings -r ts-node/register/transpile-only web-api/src/app-local.ts"` and saw the following output (for instance--this is just one of the listener events (unpipe), but all of them seem to come from `winston`):

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0pQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e7cf9bc00afbde2bea024316a857da2426f4b2e/Screenshot%202024-08-12%20at%205.56.53%E2%80%AFPM.png" alt="Screenshot 2024-08-12 at 5.56.53 PM.png" />

I am not yet sure if this has to do with our particular setup, or if it is an issue with `winston` itself. There _are_ [open winston issues that seem related](https://github.com/winstonjs/winston/issues?q=is%3Aissue+is%3Aopen+MaxListenersExceededWarning+):

<img width="1662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1ZQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--823cd143f67b52036028ced1167b0510838a9449/Screenshot%202024-08-12%20at%205.59.22%E2%80%AFPM.png" alt="Screenshot 2024-08-12 at 5.59.22 PM.png" />

**Comment by Mwindo** [comment]
It seems to be an issue with how we were using winston. We were re-creating the logger--and therefore the event listeners--on every request via middleware instead of creating it once.
