### ISSUE TITLE
AWS v2 -> v3 conversion: SQS

### ISSUE THREAD

**Issue by jimlerza** [ustaxcourt/ef-cms#8670]
## Pre-Conditions

 - none

## Acceptance Criteria

 - All usages of the AWS v2 SQS SDK have been converted to the AWS v3 SQS SDK.

## Pain Avoided/Frustration Saved

 - AWS v2 SDK has been deprecated

## Breadth/Pervasiveness of Problem

 - Used in app context, so all downstream uses will need to be checked and adjusted if necessary.

## Complexity of Problem (Low, Medium, High) and Why it's Complex

- medium

## Notes

**Comment by ttlenard** [comment]
eService Testing Results:

- [x] Petitions Clerk - Notice of Receipt of Petition sent to P - receive email
- [x] IRS - Answer sent to - P receive email
- [x] Petitioner - Create Account - Account verification - receive email
- [x] Docket - Add paper filing - print paper service + eService to other parties - receive emails
- [x] Docket - PDF upload - receive emails
- [x] Docket - Order - receive emails
- [x] Admissions - create account for Practitioner/Petitioner - receive verification email
- [x] Docket - Multi-docket on consolidated case - receive emails
- [x] Petitions Clerk - Calendar large session - receive emails
- [x] Practitioner - multi-docket on consolidated case - parties receive emails
- [x] Petitioner - eFile document - parties receive emails
- [x] Petitions clerk - NOTT, Change of trial judge, Change to remote/in Person - receive emails
- [x] Petitioner/Practitioner - Forgot password

Not testing automations - they use python, instead of JS.
