### ISSUE TITLE
Implement workflow queueing for CircleCI

### ISSUE THREAD

**Issue by En-8** [ustaxcourt/ef-cms#8719]
Currently, we have an until-recently-undocumented "gotcha" that one must check CircleCI for an already-running deployment for a given environment before deploying to that environment lest the two running workflows for the same environment clash. This adds cognitive load to our deployments and creates opportunity for broken environments that ultimately become blockers to the team. 

## Acceptance Criteria
* A developer need not concern themselves with whether or not a deploy is already ongoing in the environment to which they need to deploy before kicking off their own deploy.

## Pain Avoided/Frustration Saved
* Fewer instances of broken environments due to simultaneous deployments
* Reduced cognitive load of deployments and the overall lifecycle of a change.

## Breadth/Pervasiveness of Problem
* Technically, this could apply to any environment, but it is likely most impactful for "bottleneck" environments, especially `test`. There are other mechanisms at play for experimental environments, like environment checkout, that make this much less likely to be a problem.

## Complexity of Problem (Low, Medium, High) and Why it's Complex
 * Medium -- looks like there may be tools for this, but there are some things to consider e.g. what do we do with the queue of workflows if one fails partway through? Do we need to change where/when we perform cleanup steps for this to work?

## Notes
There seems to be at least one tool for this: https://github.com/promiseofcake/circleci-workflow-queue. Maybe GitHub merge queue could help somehow too?

Open Questions:
- Is the juice worth the squeeze?
- There may be a tool, but it's a third party plugin. Do we want to introduce an external dependency to our deployment process? Seems well maintained for now, but may not always be.

**Comment by jasonfu9966** [comment]
Github merge queues have been researched and they don't quite accomplish what we're looking for. [Here's a primer](https://flexion.slack.com/archives/CD4PNKEPK/p1716914610001069).

**Comment by zachrog** [comment]
Tried implementing circle queues using this circle ORB
 - https://circleci.com/developer/orbs/orb/eddiewebb/queue#usage-exampleshttps://circleci.com/developer/orbs/orb/eddiewebb/queue#usage-examples
 - https://eddiewebb.github.io/circleci-queue/

Was unsuccessful after 1.5 days of trying. This orb also comes with the caveat that it does not work with forked repositories, so it will not worked on the flexion side. I was unable to figure out if the problem was that I implemented it incorrectly or the problem was that it was on a forked repo.
