### ISSUE TITLE
Spike: Investigate Postgres Database

### ISSUE THREAD

**Issue by zachrog** [ustaxcourt/ef-cms#8722]
Started as Reduce Time and Cost for Database Migrations however evolved into a Spike to investigate implement Postgres in place of Dynamodb and reducing dependance on OpenSearch.

## Acceptance Criteria
- Implement Messages in Postgres
- Determine Postgres Infrastructure
- The cost of performing a migration is reduced.
- The speed of a migration is increased.
- The stability of the migration process is maintained.

## Pain Avoided/Frustration Saved
- Easier to access and query database
- High $$$ cost of doing a migration
- Complex infrastructure and process for migrations
- Migrations can take a long time depending on the data size.

## Breadth/Pervasiveness of Problem
  Every time a migration occurs we need to spend hundreds of dollars to perform it and it may take ~8 hours to do.

## Complexity of Problem (Low, Medium, High) and Why it's Complex
High complexity as migrations can involve infrastructure, code changes, and deployment strategies
High complexity as literally changes our data access patterns and introduces new technical stack.

**Comment by codyseibert** [comment]
although this is a bit unrelated to the story, I do think it's important to understand migration benchmarks on well established databases such as postgres so we have a baseline to compare to when we talk about migrations in dynamo.  I know sql can run fast based on what I've read online, but I didn't really have metrics to confirm my assumption. 

To verify how long a migration actually takes in SQL, I setup an AWS RDS instance using a single postgres instance (no multi-az, smallest machine with 1000 IOPS, 2cpu 8gb ram).  After initialization, I created a docket_entries table and added all the necessary columns to hold a single docket entry record.  Next, I created 10,000,000 docket entries by running a single sql statement which took around 2 minutes.


![image](https://github.com/ustaxcourt/ef-cms/assets/1868782/2c549fe5-f288-4a76-a7e3-da3436fbf80e)



next, I want to check how long it would take to count every single record in that table.  Running a simple select count(*) query took 2 seconds.

![image](https://github.com/ustaxcourt/ef-cms/assets/1868782/cddd2155-abab-44c6-bb05-752a1804b2b8)

Next, wanted to verify how long it would take to run a migration to update all of the records in that table to change a document_type from 'MISC' to 'O'.

![image](https://github.com/ustaxcourt/ef-cms/assets/1868782/9b84f30b-b981-4cb6-8329-5fa54e619b8b)

The point of this experiment was to verify my hunch that SQL can easily handle our dataset, and it would dramatically reduce the time to run a migration script which modifies all records in a table.  Additionally, this was a worst case scenario migration, often our migration scripts involves only updating a subset of rows which would mean doing an update with a WHERE clause would be even faster.  This test also didn't include using database indexes which could affect write performance but improve read performance.

Given the fact that a migration takes almost 2-3 hours in dynamo, switching to postgres may simplify a lot of our system.  It is worth mentioning that running this postgres instance estimated around $150 a month, so having a separate instance for each environment may result in much higher operational costs.  It is possible to host multiple schemas on the same postgres database, or have multiple tables with a $ENV_ prefix inside a postgres database if reducing costs is necessary.

**Comment by codyseibert** [comment]
I have been experimenting with another approach by creating a GSI on the entityName and also the SK of the document.  It seems like we use the SK in many entities as the unique identifier, so this allows us to query for all the records of a certain type.  In order to speed this up, one much run many concurrent dynamo queries against the index using a begins_with clause.  For example, if you want to query for all the cases, you need to make a query for the following

entityName: 'Case' sk: case|10
entityName: 'Case' sk: case|20
entityName: 'Case' sk: case|30

etc.

to achieve this I created this script which runs 100 queries concurrently and counts all of the results.  It ends up using 9.2 GB of memory on my machine.  Here is the script for future reference:

```ts
import { DynamoDBClient, QueryCommand } from '@aws-sdk/client-dynamodb';

const client = new DynamoDBClient({
  region: 'us-east-1',
});

const TABLE_NAME = 'efcms-test-alpha';
const INDEX_NAME = 'entityName-sk-index';

async function queryPair(pair: string) {
  let results: any[] = [];
  let lastEvaluatedKey: { [key: string]: any } | undefined = undefined;
  console.log('fetching', pair);

  do {
    const command = new QueryCommand({
      ExclusiveStartKey: lastEvaluatedKey,
      ExpressionAttributeNames: {
        '#pk': 'entityName',
        '#sk': 'sk',
      },
      ExpressionAttributeValues: {
        ':pk': { S: 'Case' },
        ':prefix': { S: `case|${pair}` },
      },
      IndexName: INDEX_NAME,
      KeyConditionExpression: '#pk = :pk and begins_with(#sk, :prefix)',
      TableName: TABLE_NAME,
    });
    const response = await client.send(command);

    results = results.concat(response.Items || []);
    lastEvaluatedKey = response.LastEvaluatedKey;
  } while (lastEvaluatedKey);

  return results;
}

const generateUuidPairs = (): string[] => {
  const chars = '0123456789'; //abcdef'; // append the abcdef for uuids
  const pairs: string[] = [];

  for (let i = 0; i < chars.length; i++) {
    for (let j = 0; j < chars.length; j++) {
      pairs.push(chars[i] + chars[j]);
    }
  }

  return pairs;
};

// Usage
const uuidPairs = generateUuidPairs();

Promise.all(uuidPairs.map(queryPair))
  .then(results => {
    console.log(results.length);
    const flat = results.flat();
    console.log(flat.length);
  })
  .catch(console.error);
```

this script took 319s to run which resulted in a count of 1073928 which also matched the index count on elasticsearch.   I think this approach would allow us to target certain subsets of our dataset and patch that subset much faster than our parallel scan approach which checks everything.  Also it seems like doing all of this on a single powerful machine might be much faster than splitting this out into various lambda functions.

**Comment by codyseibert** [comment]
I've been doing experiments with trying to batch write into dynamo as fast as posible; here are some findings.

Writing 500,000 case records into dynamo with a concurrency of 100 batch write calls at a time, it took 3m 2.7s.  This was ran from an EC2 instance with 4 cpus and 16gb of ram.  This means that running a migration against all cases in our system (~ 1 million cases) would take around 6 minutes.  Migrating all docket entries in our system (~10 million docket entries) would take around an hour.

Unfortunately, to get these speed benefits, we'd need to move away from the alpha / beta approach for migrations because the way our current migration process is setup, we need to migrate ALL data regardless of if we are just updating a single entity.  This refactor would probably require a lot of effort.  Additionally, we'd probably also need to consolidate our opensearch alpha / beta tables into a single table as well and just create a new index and migrate data into the new index while keeping the old index around.

The original work for setting up our migration system took months, and I'd assume the work to achieve this refactor might also take months with the end result being we are still on dynamo.  I talked with @zachrog  and @En-8 and zach mentioned that a lot of the issues we currently have in our system are directly because of dynamo.  Some of these issues include:

- the need to use elasticsearch for simple queries because dynamo doesn't have a great way to do queries based on non pk / sk columsn
- the updateCaseAndAssocations method which tries to update all associated records on a case when certain properties of that case change
- the needing for batching to prevent connection reset errors because we often need to update tons of cases at once which ends up doing tons of dynamodb queries and updates when updating simple fields.
- issues with our de-normalized data cause complexity in our code where we often forget to update duplicate data shared between messages and cases (for example when a case caption is updated).  

At the start of this project, we picked dynamo because we didn't really know the size of the dataset and it was marketing as being very cheap, but knowing what we know now on this project, we think using a relational database such as postgres might make this project more maintainable and it would simplify our migration process.

my next steps are to just leave our migration process in place, and instead start slowly migrating entities into postgres (starting with messages) to see how much work might be involved to achieve it.

**Comment by codyseibert** [comment]
We compared the section inbox messages between Opensearch and Postgres.  
The average response times for the Opensearch implementation was 125.79812 ms
The average response time for the Postgres (RDS) implementation was 97.29583 ms

<img width="709" alt="Screenshot 2024-07-29 at 3 57 34 PM" src="https://github.com/user-attachments/assets/2e522ce2-0ed5-4f3d-96a9-e6a32bed6978">

**Comment by ttlenard** [comment]
Tested the following on TEST with all court user roles:
- [x] Create new message and send
- [x] Reply to a message
- [x] Forward a message
- [x] Create Order from Message
- [x] View existing messages in a case
- [x] Expand message threads in a case
- [x] Complete a single message from a message thread
- [x] Complete a single message from the inbox
- [x] Complete multiple messages at once from the inbox
- [x] View messages in Sent
- [x] View messages in Completed
- [x] View messages in the inbox
- [x] View recent messages on Judge/Chambers Dashboard
- [x] QC process - complete and send message
- [x] Messages are removed from sent and completed boxes after 7 days
- [x] Logs display activity with messages correctly
- [x] Stamp order in a message
- [x] Status order report from a message
- [x] Attaching draft documents in a message
- [x] Deleting a draft document that was attached to a message - ensuring that the message functions ok
- [x] Send message with 5 attachments
- [x] Sign stip decision from a message
- [x] Complete a message - check timestamp to ensure it is correct
- [x] Create a new message - check timestamp to ensure it is correct
- [x] For cases that are calendared - double check that the trial location and trial date displayed is correct
- [x] Update a Case status for a case that has active messages - check to ensure that the updated case status is reflected in the message
- [x] Update a case title for a case that has active messages - check to ensure that the updated case title is reflected in the message

**Comment by pixiwyn** [comment]
Todo list from dx/ox goals meeting: 
- write a script to delete all the messages after the deployment was successful
- automate the glue job to also work with these rds changes
- document and do a walk through about how the expand contract process would work for RDS related migrations
- walk through with tenille and anyone else on the team about how to connect to the postgres database
- give one last opportunity to demo to team and get any last questions about the changes
