### ISSUE TITLE
BUG: Edit Court Issued Upload Edit Page Incorrect

### ISSUE THREAD

**Issue by pixiwyn** [ustaxcourt/ef-cms#8730]
**Describe the Bug**
When Docket Clerk edits a drafted court issued upload they are redirected to the edit order (*/edit-order/*) screen instead of edit uploaded court issued pdf (*/edit-upload-court-issued/*) screen.

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
All

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Writing accessibility tests.

**To Reproduce**
1. Login as docketclerk1@example.com
2. Goto any served case
3. Upload PDF
4. Goto drafts
5. Click Edit

**Expected Behavior**
Docket clerk upon edit, sees edit uploaded court issued pdf (*/edit-upload-court-issued/*) screen.

**Actual Behavior**
Docket clerk upon edit, sees edit order (*/edit-order/*) screen.

**Screenshots**
<img width="1102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f34acae57ccb5a19364650f4af814def5a3924d7/2024-06-06_15-13-46.png" alt="2024-06-06_15-13-46.png" />

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--592d2aec36581b9913787766c3bd1293846c2d75/2024-06-06_15-13-37.png" alt="2024-06-06_15-13-37.png" />

**Cause of Bug, If Known**
Documents previous to the story below were being defaulted to Misc document type. The edit route relies on document type Misc to route to the edit uploaded court issued pdf. 
https://github.com/flexion/ef-cms/issues/9658

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by akuny** [comment]
Update:

After putting a fix in place for the bug described in this issue, I found two new bugs. @ttlenard since the fix for the bug described in this issue increases the number of bugs, my instinct is to continue work on fixing these two new bugs as part of this issue instead of breaking them out into new issues. 

### New Bug 1

When a Docket Clerk edits a unsigned court issued upload in draft using the `/edit-upload-court-issued/` form, the document description does not update.

In a local development environment:

1. Log in as [docketclerk1@example.com](mailto:docketclerk1@example.com)
2. Go to a case
3. Upload PDF using the Create menu's "PDF Upload" option
4. Go to drafts
5. Click the "Edit" button
6. Update the description and click "Save"
7.  Return to the "Drafts" tab and note that the description of the document in the "Drafts" list has not been updated
8. Click "Edit" and note that the Description that loads in the edit form is the updated description, despite the fact that this updated description did not display in the previous screen. This still happens after logging out and logging back in after clearing the browser's cache.

**Edit 8/28/2024:** The bug described below was caused by incomplete seed data and is no longer an issue.

~### New Bug 2~

~When a Docket Clerk edits a court issued upload that has been signed using the `/edit-upload-court-issued/` form, the document description does not update.~

~In a local development environment:~

~1. Log in as [docketclerk1@example.com](mailto:docketclerk1@example.com)~
~2. Go to a case that has a signed draft court issued docket entry (e.g., 111-19 in seeded test data)~
~4. Go to the "Drafts" tab~
~5. Click the "Edit" button~
~6. Click "Yes, Continue" to remove the signature~
~7. The user is routed to a generic 400 error page because the call to `remove-signature` returns a 400 response that contains the error "No value provided for input HTTP label: Key." (see below)~

**Comment by ttlenard** [comment]
@akuny I agree. Let's get these fixed! Thank you for the thorough explanation of the issues you found.

**Comment by akuny** [comment]
I submitted a [PR to test](https://github.com/ustaxcourt/ef-cms/pull/5297) this morning that fixes the original bug along with the second newly discovered bug.

Refactoring to better align domain logic concerning draft court issued uploads with the actual behavior of the application will be submitted in a second PR.

**Comment by ttlenard** [comment]
@akuny Testing Feedback:

1. Please update the information alert that displays when you change the PDF so that it is consistent with our other alerts in DAWSON. It should be the standard blue USWDS alert (like in the petition flow - see screen grab below)

Current Alert is grey with blue
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0diQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--974d9c9914f314134f23722db4db4aff8ab04c17/image.png" alt="image.png" />

We should be using this USWDS standard alert (taken from the petition workflow):
<img width="880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ViQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59305ae71e9412794c6ef3c8266a8fc760d26585/image.png" alt="image.png" />


2. Can we update the text in the alert to this? "Saving will replace the previous document."

**Comment by swongCO** [comment]
**Test feedback**

- [ ] The btns in the edit flow should be positioned under the description component, like it is in the upload flow.

Correct btn position in upload flow:
<img width="1708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWliQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9d59dd59d60795031379ef3ca4599e6a6153253/Screenshot%202024-08-29%20at%201.40.55%E2%80%AFPM.png" alt="Screenshot 2024-08-29 at 1.40.55 PM.png" />

Btns way down on the page in edit flow:
<img width="991" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW1iQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02fb944fb775c78a66a27db97be1f57f69341f76/Screenshot%202024-08-29%20at%201.41.39%E2%80%AFPM.png" alt="Screenshot 2024-08-29 at 1.41.39 PM.png" />
