### ISSUE TITLE
Trial Sessions Page: Allow Multiple Selections for Filters

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8742]
As a Court, so that I can customize the Trial Sessions display to find the information I'm looking for, I need to be able to select multiple options for the filters on the page.

## Pre-Conditions
ustaxcourt/ef-cms#8740

## Acceptance Criteria
* New filter: Trial Start Date range, filters for trial sessions with a start date in the range specified (optional)
* Multiple values can be selected for the Location filter
* Multiple values can be selected for the Session Type filter
* Multiple values can be selected for the Judge filter
* Filter selections can be easily cleared/reset
* As multiple values are selected, Trial Sessions page updates to include only those Trial Sessions matching filter selections

## Notes
* "Status" filter should not display on the New view

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
UX Notes:

[Figma File
](https://www.figma.com/design/hXGX0kcb8Gxqwnp9tu3OlS/10411-%26-10408-Trial-session-page-updates?node-id=91-509&t=Yi3PiXCuqy6yVavo-1)
This ticket should follow [10409 ](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/10409)(since we'll be adding in a new filter in that ticket)

1. Change proceeding type to a radio button and change the other filter dropdowns to the multiple selection with the pills component. (See the custom case report for those dropdown/pill components)
2. Move the add trial session button to the top right, on the same line as the trial session planning report.
4. Resetting filters will clear them all/reset to defaults. (the default for session status will be 'open' not all.)
5. The pills will appear beneath their respective dropdowns. They will wrap under it when they run out of room.
6. The date range will search for trial start date.  Only validations should be that it must be in date format, and that the end date cannot be before start date & start date cannot be after end date. Basically follow other validation rules for the date ranges.

If there is difficulty in getting the date range to look right padding wise on that row, we can drop it to the second row and then we will just have three rows of filters.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the Trial Sessions/Calendared tab; Filter and Page display is updated.

- Log in as any Court User
- Click on the Trial Sessions tab
- Review the Trial Sessions Calendared page

Expected Results
- [x] **NEW FUNCTIONALITY** - Proceeding type is now displayed with Radio buttons (All is the default selection)
- [x] **NEW FUNCTIONALITY** - There is a new filter for Trial Start Date range
- [ ] **NEW FUNCTIONALITY** - Session type, Location and Judge Filters are displayed below the session status, Proceeding type and Trial Start Date Range
~~- [ ] **NEW FUNCTIONALITY** - There is a button now that is active and is titled "Apply Filters" (See mock)~~
- [x] **NEW FUNCTIONALITY** - There is a link to "~~Clear~~ **Reset** Filters" ~~beside the Apply Filters button~~, and it is inactive.
- [x] **NEW FUNCTIONALITY** - The Add Trial Session button is shifted up to the right of the trial session planning report link.



#### 2) Court user (that has access to the New Tab), clicks on the New tab

- Continuing from the previous test
- Click on the New tab (Judge's and CA's do not have access to the New tab)
- Review the Trial Sessions New Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is no Radio button section for Session Status
- [x] **NEW FUNCTIONALITY** - Proceeding type is now displayed with Radio buttons (All is the default selection)
- [x] **NEW FUNCTIONALITY** - There is a new filter for Trial Start Date range
- [x] **NEW FUNCTIONALITY** - Session type, Location and Judge Filters are displayed below the session status, Proceeding type and Trial Start Date Range
~~- [ ] **NEW FUNCTIONALITY** - There is a button now that is active and is titled "Apply Filters" (See mock)~~
- [x] **NEW FUNCTIONALITY** - There is a link to "~~Clear~~ **Reset** Filters" ~~beside the Apply Filters button~~, and it is inactive.



#### 3) Court user selects multiple filters; selections display in pill containers underneath the filtered field.

- Continuing from the previous test
- Click on the Calendared tab
- Select a variety of items from the filters, add in a Trial Session Start Date range

Expected Results:
- [x] **NEW FUNCTIONALITY** - Each selection displays underneath the filter field in a pill container
- [x] **NEW FUNCTIONALITY** - User can click on the X in the pill container to remove the filter
- [x] **NEW FUNCTIONALITY** - The only date validation is that the dates must be in date format, and end range cannot be before start date range/start date cannot be after end range.


#### 4) Court user applies the filters, data in the table is filtered appropriately

- Continuing from the previous test
- Review the data in the results table

Expected Results:
- [x] **NEW FUNCTIONALITY** - Data in the table is filtered to match the selections that were made in the previous test
- [x] **NEW FUNCTIONALITY** - Data in the table below is in the appropriate date range



#### 5) Court user adds additional filters, removes some; Applies the filters, data in the table is filtered appropriately

- Continuing from the previous test
- Add additional filters and remove some
- Click on the Apply Filters Button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Data in the table is filtered to match the filter selections that were made.

*Repeat test cases 3, 4, and 5 with a variety of filter selections, adding in just one date in the range, and then the other.  Be sure to test the date range picker data validation by entering in dates in non-date format and flopping the order of the start/end range.



#### 6) Court user clears the filters; Data in the table displays all default data again.

- Continuing from the previous test
- Click on the Clear Filters link

Expected Results:
- [x] **NEW FUNCTIONALITY** - All selected filter data in the pill containers is no longer displayed
- [x] **NEW FUNCTIONALITY** - If the Session status or proceeding type radio buttons were changed from the default, they are switched back to the default.
- [x] **NEW FUNCTIONALITY** - The Trial Start Date range is cleared
- [x] **NEW FUNCTIONALITY** - Data in the table is displaying all calendar data per the default again.
 


#### 7) Court user clicks on the new tab; User can apply/clear filters as per the Open tab (This test will not be completed for Judge's or CA's)

- Continuing from the previous test
- Click on the New tab
- Apply/Remove filters and Clear filters

Expected Results:
- [x] **NEW FUNCTIONALITY** - The test cases from 1-6 pass for the New tab 


#### 8) Accessibility Testing

 - There are known issues with the custom case report having accessibility issues with the pill containers.  This test ensures that this issue is not present.

Expected Results:
- [x] **NEW FUNCTIONALITY** - User can use their tab button to select the selected filter and remove it if needed using their keyboard.
- [x] **NEW FUNCTIONALITY** - Screen readers can read the data in the pill containers and read the page in a logical order.



#### 9) Trial Sessions Filters work when viewing on a mobile device

- Log in as a Court User on a mobile device
- Click on the trial sessions tab
- Select some filters
- Click on the Apply Filters button

Expected Results
- [x] User can view the data on a mobile device. It doesn't have to be pretty, but it has to work.



#### 10) Repeat these tests with all Court users

- [x] ADC
- [ ] Admissions Clerk
- [x] Clerk of the Court
- [x] Case Services Supervisor
- [x] Docket Clerk
- [x] Chambers Administrator (don't have to do test 7 - this user does not have access to the New tab)
- [x] Judge (don't have to do test 7 - this user does not have access to the New tab)
- [x] Petitions Clerk
- [x] Reporters Office (don't have to do test 7 - this user does not have access to the New tab)
- [x] Trial Clerk
- [x] Floater (don't have to do test 7 - this user does not have access to the New tab)
- [x] General User

**Comment by zachrog** [comment]
Things that need regression:

- swing session options
- NOTT reminder indicator
- Autocomplete UI when selecting a document
- Paginators (Custom Case Report, Cold Case Report List, etc..)

**Comment by swongCO** [comment]
**UX feedback**
For New and Calendared tabs:
- [x] Session Status and Proceeding Type labels should be sentence case
- [x] Reduce the spacing between the two rows of filters - try to match the spacing in Custom case report
- [x] Paginator - if there is only one page, do not show the pagination
- [x] Paginator - display the paginator at the bottom of the table; when a page is changed, navigate the user to the top paginator (like in Custom case report)
- [x] Paginator - match the spacing between the last page and Next link to the spacing between Previous and the first page
- [x] When resetting filters on the New tab, don't navigate the user to the Calendared tab
- [x] Date fields error validation has some odd behavior - screenshot examples:

<img width="1108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1FVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2191d94fd37f81ea9d57400b97d16aaf061d72ba/Screenshot%202024-10-01%20at%209.50.53%E2%80%AFAM.png" alt="Screenshot 2024-10-01 at 9.50.53 AM.png" />

<img width="1082" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1VVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3087431edf5576d1d400d88538334f98db1ffda9/Screenshot%202024-10-01%20at%209.51.09%E2%80%AFAM.png" alt="Screenshot 2024-10-01 at 9.51.09 AM.png" />

<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2dVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ebc1f2133550abb7984e42ee9894365595dcb5b/Screenshot%202024-10-01%20at%209.55.18%E2%80%AFAM.png" alt="Screenshot 2024-10-01 at 9.55.18 AM.png" />

<img width="1140" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2tVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b1048f999260cdc55e587e145679a93ba8cec9d/Screenshot%202024-10-01%20at%209.52.45%E2%80%AFAM.png" alt="Screenshot 2024-10-01 at 9.52.45 AM.png" />

- [x] If there is an error in both date fields, selected filter pills are not being removed when clicking X (not always reproducible); after both errors are cleared, the pills are gone

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d31346d85016114aac4b0abfd6ce4edbe3a7a0b6/Screenshot%202024-10-01%20at%209.57.58%E2%80%AFAM.png" alt="Screenshot 2024-10-01 at 9.57.58 AM.png" />

**Comment by zachrog** [comment]
From UX
[x] Paginator accessibility
<s>[] Combo box cannot select when in voice mode</s> This will be handled when the page goes public
[x] Make more responsive

**Comment by swongCO** [comment]
**UX feedback**

- [x] Spacing between the three btns (Add Trial Session et al) should be increased - see btns above docket record table for reference

![Image](https://github.com/user-attachments/assets/d4139bdd-4b08-40d8-9431-678765a1a518)

- [ ] iOS phone: selection pills seems to have more padding within than on desktop - holding off on this point until we release this page for external users.

![Image](https://github.com/user-attachments/assets/e947b8ce-2548-44bf-be1e-d848bbc8a0f5)

- [x] axe DevTools is flagging the 5 inputs as having issues - the date fields "A form field element should have an id or name attribute"; the three combo-boxes "Incorrect use of -label for=FORM_ELEMENT-"

![Image](https://github.com/user-attachments/assets/af37394e-065f-4b8c-8dd4-ad892aad09b9)

**Comment by ttlenard** [comment]
@nechama-krigsman @zachrog 

Testing feedback.

Found a small issue. I checked with UX and they thought it was worth adjusting if this is an easy fix.  If it is complicated, then we are ok with leaving as is.

1. Navigate to the trial sessions page
2. Be on the Calendared tab.
3. Add in some filters
4. Click on the Calendared tab
5. All of your filters are reset
6. Same thing happens if you are on the new tab and repeat the steps outlined here.

We definitely want to keep the functionality where if the user clicks off of the current tab, then reset the filters, but we don't want the filters to reset if they click on the existing tab that they are currently on.  

As a comparison, I looked at the functionality on the search page. Clicking on the existing tab that you are on (ex: Order Search) doesn't clear your filters.
