### ISSUE TITLE
Some Messaging updates

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8743]
This will cover two items in Messages for all court users.

1. The sort arrows should not drop down to an extra row when they run out of room. They should be treated like they are a part of the word before it. This most likely means the sorting arrows will need to be resized and/or moved closer to the word they are next to. We can chat about solutions as you dig into the code.

![Image](https://github.com/user-attachments/assets/8ab89575-384d-48ad-b414-871a6a8af01f)

 

<s>2. Docket No column should be a wide enough column that the docket number doesn't need to wrap. The max size would be 10 characters for the docket number.
3. (This can be moved out into a separate ticket if it makes sense to do so after exploring the problem). Columns can currently expand so much they make the other columns disappear. (Having a message title be extremely long will make that column expand) We should add a mechanism that prevents a column from taking over the entire table. (Something like a max percentage before we force a line break?)</s>

**Comment by Mwindo** [comment]
After discussing with Sui and Missy, we've decided the following:

- It is ok if the docket number wraps. Let the column do its thing.
- The easiest solution for the sort icon is to have it wrap with the text (see screen shot)
- We will let columns take up the room they need, but at least allow the table to scroll when it is too big

![Image](https://github.com/user-attachments/assets/5a8ca18e-8f68-46ab-a67b-b29beaea2bc5)

I am currently seeing how difficult refactoring the message tables is. Small changes I made to one component needed to be mirrored in five others because we have six very similar message table components (Cartesian product of individual/section and inbox/outbox/completed). Ideally, if possible, I would like to reduce this to one or two components, and maybe even create a more reusable SortableTable component in advance of ustaxcourt/ef-cms#8854 . If this is not straightforward, however, I will abort.
