### ISSUE TITLE
Add ", et al." to Docket Number in Page Headers When Generating Orders in Consolidated Cases

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8752]
As a judge/docket clerk/CA/ADC, so that when I generate a multi-page order in the lead case of a consolidated group the style is uniform, I need the page headers after the first to have ", et al." added to the docket number in the page header's upper left corner.

We have the ability to add multiple cases to the caption of an order generated in the lead case of a consolidated group. When we do this, the petitioner name in the caption is appended with "et al." to indicate that there may be multiple petitioners across the case.

Subsequent pages generated after the first page have the docket number of the lead case listed appropriately in the header, but as these orders are docketed in every case in the group, we should have ", et al." appended to that docket number on those page headers as well. See attached example for how these headers look today.

## Acceptance Criteria
* When an order is created/generated in DAWSON in the lead case in a consolidated group and the caption is edited to include multiple case numbers, every page after the first should have the lead docket number appended with ", et al."

## Notes
[index.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2JFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdbff6f5f22fd145a3483d78d3dd85554a6275a0/index.pdf)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement notes:
- Should this also be on the upcoming status report's order response work? - If more than one page can be generated, then yes. Possible they can't make more than one page.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge user creates a long order (more than one page in length) in the lead case of a consolidated group (do not add additional docket numbers to the caption); Upon preview, the header on the additional pages does NOT display et al.

- Log in as a Judge user
- Navigate to the lead case in a consolidated group
- Click on Create and then select Order or Notice
- Select Order and click continue
- Begin drafting the order, making sure that you include enough text so that the order is multiple pages in length.
- Click on the preview link

Expected Results:
- [x] The header for the pages after the initial page displays the docket number as per usual on the left side of the page.



#### 2) Judge user creates a long order (more than one page in length) in the lead case of a consolidated group and adds all docket numbers to the caption; Upon preview, the header on the additional pages display "et al." after the lead case docket number in the header

- Log in as a Judge user
- Navigate to the lead case in a consolidated group
- Click on Create and then select Order or Notice
- Select Order and click continue
- Click on the Add Docket numbers to the Caption link, and select all cases in the consolidated group, click save
- Begin drafting the order, making sure that you include enough text so that the order is multiple pages in length.
- Click on the preview link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The header for the pages after the initial page displays the docket number as per usual followed by "et al." on the left side of the page.
- [x] After signing the order and then going back to edit it, the header information remains the same.


### 3) Judge user edits the case caption; selects only some of the cases in the group; Upon preview, the header on the additional pages display "et al." after the lead case docket number in the header.

- Continuing from the previous test
- Click on the edit link
- Say ok that you will be removing the signature
- Click on the Edit docket numbers in caption link
- Select some of the cases in the group (not all)
- Click save on the modal
- Click on the preview link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The header for the pages after the initial page displays the docket number as per usual followed by "et al." on the left side of the page.
- [x] After signing the order and then going back to edit it, the header infomration remains the same.



#### 4) If there are any existing draft long orders that were in the lead case in a group, if you edit the draft, the new header information populates correctly. We aren't updating existing docketed orders.

- [x] This test passes



#### 5) Be sure to test with other users

- [x] ADC
- [x] Docket Clerks
- [x] CSS
- [x] CotC
- [x] Chambers

**Comment by ttlenard** [comment]
Note: While testing this story, the "et al." is also added to Notices.  This is great! Thank you.
