### ISSUE TITLE
Practitioner Record: View Case List

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8759]
As an Admissions clerk, so that I can quickly navigate to docket records of interest, I need a screen view of a given practitioner's case list.

Currently when viewing a Practitioner record, the case list of dockets that practitioner is associated with is available in printable format via the Print Case List link. It would be helpful to have a screen version of this so that Court personnel can navigate directly to the cases associated with the practitioner.

## Acceptance Criteria
* A practitioner's Open Cases can be navigated to from the Practitioner record screen
* A practitioner's Closed Cases can be navigated to from the Practitioner record screen
* The display of Open Cases includes the following information for each case:
  - Docket No. (hyperlinked)
  - Case Title (need petitioner names only)
  - Case Status
* The display of Closed Cases includes the following information for each case:
  - Docket No. (hyperlinked)
  - Case Title (need petitioner names only)
* Both the Open and Closed case displays will need pagination mechanisms

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- what's the upper limit of how many cases a practitioner is associated with? 4k+ (Hans F)
-

**Comment by katiecissell** [comment]
**UX Notes:**
[Figma file](https://www.figma.com/design/Nc44lsr6xFNhDRFACNvf0A/USTC-%7C--10261-View-Practitioner-Case-List?node-id=16-127&t=PCUUN3N02vTDfpLb-1)

Add two new tabs with Details (and Documentation for admissions). Display the number of cases for each tab within each tab header. Move the print case list button to the top level with the tabs. If the page has more than 100 cases, use the pagination component above and below the table. 

Empty state messages:
1. There are no open cases.
2. There are no closed cases.

Admissions user view:
![Image](https://github.com/user-attachments/assets/834e8c50-a85e-454e-87cf-e1fa04287cd5)


![Image](https://github.com/user-attachments/assets/1c3d382a-8c3f-4694-a08e-71b007e5186e)


![Image](https://github.com/user-attachments/assets/c37a9079-755d-46be-83f6-77f7d5ae44b8)


Not admissions court user view:
![Image](https://github.com/user-attachments/assets/41b4cda6-58c9-4c96-aead-ae8c3cd2c6ff)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user views a Practitioner record; New tab headers are displayed for Open and Closed Cases.

- Log in as a Court user
- Click on the Advanced link
- Search for a Practitioner
- Click on the Bar number link for the practitioner

Expected Results
- [x] **NEW FUNCTIONALITY** - There are now two additional tabs displayed on the Practitioners page (Open Cases and Closed Cases)
- [x] **NEW FUNCTIONALITY** - The Open/Closed tabs also include the total number of Open/Closed cases for the practitioner in the header (see mockup)



#### 2) Court user clicks on the Open Cases tab header; the Practitioner's Open Cases display.

- Continuing from the previous test
- Click on the Open Cases tab header

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Practitioner's Open cases display in a table under the Open Cases tab header
- [x] **NEW FUNCTIONALITY** - Columns include: Docket No., Case Title, Case Status
- [ ] **NEW FUNCTIONALITY** - If a case is sealed, the red lock icon displays. Hover over text indicates that it is a sealed case
- [x] **NEW FUNCTIONALITY** - If a case is part of a consolidated group, the appropriate consolidated case icon displays. Hover over text indicates the type of consolidated case (lead or member)



#### 3) Court user clicks on the Closed Cases tab header; the Practitioner's Closed Cases display.

- Continuing from the previous test
- Click on the Closed Cases tab header

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Practitioner's Closed cases display in a table under the Closed Cases tab header
- [x] **NEW FUNCTIONALITY** - Columns include: Docket No., Case Title
- [ ] **NEW FUNCTIONALITY** - If a case is sealed, the red lock icon displays. Hover over text indicates that it is a sealed case
- [x] **NEW FUNCTIONALITY** - If a case is part of a consolidated group, the appropriate consolidated case icon displays. Hover over text indicates the type of consolidated case (lead or member)


#### 4) Court user clicks on the docket record link for an Open case; The docket record of the case opens in a new tab.

- Continuing from the previous test
- Click on the Open Cases tab
- Click on the Docket number of a case from the table

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case's docket record opens in a new tab



#### 5) Court user clicks on the docket record link for a Closed case; The docket record of the case opens in a new tab.

- Continuing from the previous test
- Click on the Closed Cases tab
- Click on the Docket number of a case from the table

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case's docket record opens in a new tab



#### 6) Court user views a case list for a practitioner that has more than 100 cases; A paginator displays so that the user can view the next page of cases.

- Continuing from the previous test
- Go back to the Practitioner Search page
- Search for a practitioner that has more than 100 cases
- Click on the bar number link for the practitioner
- Click on the Open/Closed cases tab (whichever one has more than 100)

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a paginator present and the user can use it to view the additional cases that the practitioner is associated with.



#### 7) Court user can Print the Practitioner's Case list as per normal.

- Regression test that the print case list functions as it normal does

Expected Results:
- [x] This test passes
- [x] Cases listed on the printed report match the cases displayed in the UI.



#### 8) An Open case associated with a practitioner is closed; Case that was displayed on the Practitioner's Open Cases list now displays on the Closed Case list appropriately.

- As a docket clerk, navigate to a practitioner record that has open cases
- Click on the Docket number link for an open case that the practitioner is associated with.
- Click on the Case information tab and edit the case status to closed.
- Navigate back to the practitioner record
- Refresh the page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Open case is now displayed on the Practitioner's Closed Cases list.


#### 9) Test on a Mobile device

- Access the Practitioner pages on iOS and Android

Expected Results:
- [x] **NEW FUNCTIONALITY** - These pages will load on a mobile device - does not have to be pretty but needs to load and be able to be viewed.



#### 10) Test with keyboard and screen readers

- [x] Pages can be navigated with only a keyboard
- [x] Pages can be read with screen readers



#### 11) Repeat the tests above with all Court Users

- [x] Admissions Clerk (See mockup, open/closed cases tab will be to the right of the documentation tab)
- [x] ADC
- [x] Case Services Supervisor
- [x] Chambers
- [x] Clerk of the Court
- [x] Docket Clerk
- [x] Floater
- [x] General User
- [x] Judge
- [x] Petitions Clerk
- [x] Reporters Office
- [x] Trial Clerk

**Comment by Mwindo** [comment]
I have deployed tentative code to the test environment. I want to see what the timing is like for practitioners with large case loads before passing it on to UX.

**Comment by mwestereng1** [comment]
**UX Notes:**

- [x] Can we use the new paginator created for story 10411? If no, disregard the first VoiceOver comment

- [x] VoiceOver
     - [ ] VoiceOver does not read the paginator correctly. It reads every page as "Page 1"
    ![Image](https://github.com/user-attachments/assets/422804f2-5d8a-42aa-9b2a-3a3f083d9c1e)


     - [ ] Voiceover does not read the first column in the table, or the icons
    ![Image](https://github.com/user-attachments/assets/7c4115a1-74c3-4ba3-a6a5-1d0a7f926827)


- [x] There is extra spacing between the tabs and the cards on the "Details" page as compared to staging (see images below)
     **Test Example**
    ![Image](https://github.com/user-attachments/assets/6680eed2-4636-42cd-9a92-3ce375be0ffe)


     **Staging Example**
   ![Image](https://github.com/user-attachments/assets/2facc1f9-56a2-4683-b6b5-9ffa705df614)



- [x] There is extra spacing between the tabs and the table on the "Documentation" page as compared to staging (see images below)
     **Test Example**
     ![Image](https://github.com/user-attachments/assets/8efa66b9-e221-4be4-b635-f6c04cf9439f)


     **Staging Example**
    ![Image](https://github.com/user-attachments/assets/7d6174e6-4d1f-4396-a6d3-1865cbe99b65)

**Comment by Mwindo** [comment]
Thanks @mwestereng1! I see the issue with the Paginator in the code, but I think it is being addressed in 10411! As for the spacing, I will fix that--good catch!

**Comment by mwestereng1** [comment]
We are unable to pull up IRSPractitioner8, it gives a 502 error. We believe this user has over 4,000 cases. Could the 502 error be happening because of the large amount of cases? We are able to pull up other users with large numbers of cases. 

https://app.test.ef-cms.ustaxcourt.gov/practitioner-detail/RT1111

![Image](https://github.com/user-attachments/assets/353a17e1-d2c1-4950-a036-dcd0044a3a2f)

**Comment by Mwindo** [comment]
Thank you so much for catching this! It was indeed indirectly caused by the number of cases. I think I have a fix for this and will confirm once I re-deploy to test.

**Comment by mwestereng1** [comment]
**UX Feedback:**

- [x] Update the paginator to the same styling as the new paginator for the Trial Session filters 
     ![Image](https://github.com/user-attachments/assets/c501195c-b214-4d42-97f6-fa0106d5919b)
- [x] For practitioner RT1111, the oldest case is showing first in the Closed Cases tab
     ![Image](https://github.com/user-attachments/assets/295991cc-2403-40fb-bb2a-765ed1d10521)

**Comment by Mwindo** [comment]
Got it! The first is an easy fix. The second was an existing bug: the sort function does not distinguish between [20]95 and [19]95, so 95 is seen as coming after 23. I will address this and re-deploy.

**Comment by mwestereng1** [comment]
**In process feedback:**
- [x] Voiceover does not read the first column in the table, or the icons
     ![Image](https://github.com/user-attachments/assets/7843b225-6578-4e83-9b4a-b848f5b2eacc)
     ![Image](https://github.com/user-attachments/assets/d7cd680d-b24c-44ad-bf29-c0770c372c9f)


- [x] Details tab - The spacing between the navigation and the cards are different for an Admissions Clerk vs. non AC (this is not present in staging)

     Logged in as Admissions Clerk
     ![Image](https://github.com/user-attachments/assets/651fa00c-17dd-4d9f-bc7a-71738a22ac8d)

     Logged in as Docket Clerk
     ![Image](https://github.com/user-attachments/assets/b9691a48-314f-4c11-91ae-1375a3ed6a0e)

- [ ] Search field remains populated when logging out and logging in as a different user, or for the same user navigating away and back to the practitioner search (currently present in staging)
     ![Image](https://github.com/user-attachments/assets/ec0f70ff-cfee-48dd-ab46-b09385c7967c)

**Comment by Mwindo** [comment]
Thanks @mwestereng1 !

The spacing here is different because the `Print case list` button has been moved: The Admissions view still has an `Edit` button occupying/creating that space, whereas the non-Admissions view does not. It sounds like we want to have the space there regardless of buttons existing or not, which makes sense in retrospect. I will update that.

As for the VoiceOver in the table for icons: is that something that works with other tables? (I tried it in a few other places without luck.) If so, can you point me to an example? If not, I would recommend a separate Design Debt ticket to get VoiceOver working with the table icons. (This might also be a good opportunity for a dev to make sure these case icons are being generated consistently in our code. It looked to me like there were a few different ways we were doing so, and if that's the case, we can probably standardize.)

**Comment by mwestereng1** [comment]
Thanks @Mwindo! The VO for tables is probably a better design debt item. Here are two places where I know the consolidated case column is referenced in the table with VO:

- Blocked Cases Report
- Trial Sessions > Select trial session > Open, Closed, and Inactive Cases tabs

**Comment by Mwindo** [comment]
Just adding context from outside conversations to the ticket:

- In some places, VoiceOver + modifier can read our icons; in others, it cannot. (In my case--and I suspect other cases, since I based some of this code off of existing code--the `aria-hidden` attribute was preventing VoiceOver + modifier from interacting with the icons.) I fixed this for the Practitioner Case List, but it is still probably worth seeing which meaningful icons are not being "seen" by VoiceOver/other screen readers throughout the app.
- We elected to hold off on `Search field remains populated when logging out and logging in as a different user, or for the same user navigating away and back to the practitioner search (currently present in staging)`. This persistence of state is a problem for the entire Advanced Search Form, and for various places in the app. It therefore seemed better to address this issue separately.

**Comment by ttlenard** [comment]
Testing Feedback @Mwindo 
- [x] The Sealed Case hover over text is incorrectly stating that the case is "Sealed to the public and parties of this case".  Sealed cases are not sealed to the parties, just the public.  It might be best to just have the hover over test at the sealed case level say "Sealed" like it does on the Order Seach screen. See screen captures below:

This is what the hover over text currently displays on the Practitioner Case list when a case is sealed:
![Image](https://github.com/user-attachments/assets/8c13f2fc-4927-4617-b15c-919aed613dd8)


Probably best to have the hover over text just say Sealed like it does on the Order Search screen?
![Image](https://github.com/user-attachments/assets/36763047-0a43-4be1-a9cb-fc1f7f0c982b)
