### ISSUE TITLE
Favicon is not displayed

### ISSUE THREAD

**Issue by mwestereng1** [ustaxcourt/ef-cms#8795]
As a Dawson user, I need the favicon to be displayed in a web browser, so that I can easily identify the Dawson website.

Currently, the favicon is not being pulled into the site header for several popular web browsers. The favicon is displaying in the Microsoft Edge browser. The favicon is displaying for some Chrome browsers (but not all). It is not displaying for Safari or Firefox.
___

Current view in Google Chrome
<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDg1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7606913a186cf39eb633f1efd4b73dc080c79a1d/image.png" alt="image.png" />

___

### Pre-Conditions:
none

### Acceptance Criteria:
- [ ] Favicon displays in all web browsers
- [ ] Favicon displays in bookmarks for all browsers
- [ ] Determine if user documentation needs to be updated (Tenille): Y / N

Pain Avoided/Frustration Saved:
Allows users to identify that they are on the Dawson website and easily see which tabs in their web browser are associated with Dawson.

Breadth/Pervasiveness of Problem:
- Chrome (some users are able to see the Favicon)
- Firefox
- Safari

Complexity of Problem (Low, Medium, High) and Why it's Complex:
Low

**Comment by Mwindo** [comment]
I am not sure how browser-specific this issue actually is; I suspect it has to do with differences in caching, which would explain why some users could still see the favicon and others couldn't. In any case, I think the issue is that we are just not properly copying files over in our esbuild. I've opened a PR and will merge to test after approval.
