### ISSUE TITLE
Status Report Order Enhancements

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8812]
As a Judge/CA/ADC, so that the Status Order Report workflow better suits my needs, I need a couple of enhancements to the workflow.

The Status Order Report workflow has been a success with the Court, and we have gathered feedback on how it could be improved. We want to make the following two changes:

1) Increase the character limit for the Additional Order Text clause 
2) Change the verbiage on the generated PDF when referencing the initiating Status Report

## Acceptance Criteria
* Character limit on "Additional order text" entry field is raised from 80 characters to 256 characters
* Boilerplate language indicating docket entry number of the initiating Status Report - change "Index" to "Document"

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- Language change is for new orders - confirm: confirmed
- Can admins change language for orders instead of inside the codebase? yes, for a future story

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Status Report Order Responses Additional Order Text allows for up to 256 characters.

- Log in as a Judge User
- Navigate to your messages or a case that has a Status Report that has been filed
- Click on the status report link
- Click on Order Report link at the top of the document preview
- Add in the required fields for the Order type and add in a date
- Review the section for Additional order text.

Expected Results:
- [x] **NEW FUNCTIONALITY** - It now displays "256 characters remaining" below the text box
- [x] **NEW FUNCTIONALITY** - As you start typing, the character limit goes down
- [x] **NEW FUNCTIONALITY** - After 256 characters has been reached, user cannot type any more text in the box


#### 2) Document Preview displays the 256 characters of additional order text appropriately.

- Continuing from the previous test
- Click on the Preview PDF button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The additional order text that was added wraps appropriately
- [x] Additional order text field on the PDF begins with "ORDERED that" as per normal


#### 3) PDF Preview displays "Document no." instead of "Index no.".

- Continuing from the previous test
- While reviewing the PDF from the test case above, review the first sentence that was generated

Expected Results:
- [x] **NEW FUNCTIONALITY** - The first sentence now states, "Document no." instead of "Index no.".



#### 4) Regression test to ensure all other functionality with the Status Report Order Response works as per normal

- [x] This new functionality in test cases 1-3 also works for ADC and for Chambers users
- [x] Users can sign it, send it in a message as per user
- [x] Docket can add this document to the docket record as per normal
- [x] Judge, Chambers, ADC can edit the order report as per normal - changes in this story are reflected when editing.
