### ISSUE TITLE
Investigate new PDF upload errors and enhance error message to users

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8859]
As a DAWSON User, so that I understand what I need to do to ensure my PDF uploads without error, I need better error messaging so that I can upload my PDF into DAWSON.

Stories ustaxcourt/ef-cms#8430, ustaxcourt/ef-cms#8431, and ustaxcourt/ef-cms#8432 were completed recently. These stories enhanced the error messaging that the user received if they attempted to upload a non-compliant PDF into DAWSON.  In addition, the error message in the logs was also enhanced.  We implemented a "catch all" error message and now that we have better error messaging in the logs, we are seeing some new errors that we didn't see before.  Users get a generic "There is a problem uploading the file. Try again later.", so we aren't providing them with any direction on how to fix their file.

Additional review of the root cause of the error messages is needed.  Depending on the root cause, it may be determined that we need to add additional messaging to users so that they can fix the issue and submit the document successfully

## Acceptance Criteria
- Root cause of the error messages seen in the logs is identified. See Screen captures below
- If it is determined that a new error message is necessary, the pop-up error modal in the same format as what was implemented in stories ustaxcourt/ef-cms#8430, ustaxcourt/ef-cms#8431, and ustaxcourt/ef-cms#8432.

## Notes
Errors seen in the logs:
![Image](https://github.com/user-attachments/assets/4e261236-be87-436b-947c-33f88b308035)

![Image](https://github.com/user-attachments/assets/0b4fdd78-7dfa-4f07-b9be-ea2822d060a3)

![Image](https://github.com/user-attachments/assets/b84d1466-4708-4dc4-8b10-8c2956220602)

![Image](https://github.com/user-attachments/assets/4a84ebcf-4a7e-47e4-9cde-4045f362ec9e)

![Image](https://github.com/user-attachments/assets/10c03dd1-07c4-4c8f-8e43-c8fd1f780cec)

![Image](https://github.com/user-attachments/assets/9c2ac905-1fd4-4013-bb4f-ac0a15e34a67)

![Image](https://github.com/user-attachments/assets/ce5a9b3b-7a45-454b-beea-a47012fae5aa)

![Image](https://github.com/user-attachments/assets/7264e3eb-6740-4e77-b8a0-d39cddd32b40)

![Image](https://github.com/user-attachments/assets/27133c09-691a-4385-983d-5f3b549bf48a)

![Image](https://github.com/user-attachments/assets/04f5481e-2dd0-4b1d-981e-bf2276cf323a)

![Image](https://github.com/user-attachments/assets/921c6573-a821-4fc8-b406-1e643f6e4a46)

![Image](https://github.com/user-attachments/assets/e40ee36a-accb-40ad-ac36-cd336d6b4f4f)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
If devs determine that new error message modals will be added with this story, then I will add in test cases.  If adding new error message modals is split out into a separate story, then we can skip test cases for this story.

**Comment by Mwindo** [comment]
A few notes for devs:

- The first two FileReader errors seem to indicate something like the following: The user began the upload process, but while the validation was occurring they renamed, moved, or edited the file. I can re-create similar errors locally by throttling my browser and quickly updating a selected file. However, this doesn't seem like something that should happen at all often. I wonder if there are issues with slow browsers somehow. For instance, even though I resolved it, [this was something I noticed](https://github.com/ustaxcourt/ef-cms/pull/5312#discussion_r1754259201) when testing locally; maybe slow browsers still have a similar issue.
- The private name, k.split, and structuredClone errors (images five through nine and also eleven, unless I miscounted) are outdated browser clients. pdfjs is looking for ES2022 or later. A few options: we can add a message like, "You should update your browser"; we can transpile the pdfjs package; we can load the legacy version and modern version of pdfjs appropriately depending on the client. (I personally prefer the latter two solutions, which do not restrict users of the system who may not have the hardware to upgrade. Note that the restriction is because of pdfjs, not because of any real business need to restrict the user. Without pdfjs validation, they could upload a proper PDF just fine.)
- The other errors--the dynamic import and uninitialized variable errors--are more opaque to me. I would not be surprised if they are related to outdated browsers as well, but I am unsure.
- UPDATE: uninitialized variable errors ARE related to outdated browsers.  

Some references:

- structuredClone error: [https://github.com/mozilla/pdf.js/issues/14729](https://github.com/mozilla/pdf.js/issues/14729)
- private name error: [https://github.com/mozilla/pdf.js/issues/14327](https://github.com/mozilla/pdf.js/issues/14327)
- Outdated client info: [https://stackoverflow.com/questions/73653874/pdfjs-not-working-in-safari-blank-page-how-to-solve-issue](https://stackoverflow.com/questions/73653874/pdfjs-not-working-in-safari-blank-page-how-to-solve-issue)
- Pdj.js getting starting notes, which discuss legacy vs. modern builds: [https://github.com/mozilla/pdf.js/tree/master?tab=readme-ov-file#getting-started](https://github.com/mozilla/pdf.js/tree/master?tab=readme-ov-file#getting-started)

**Comment by ttlenard** [comment]
1. For the outdated browser related errors...would it be a good idea to inform the user right when they log in to DAWSON that they should update their browser?  Maybe we shouldn't be waiting until they attempt to upload a document?  
2. Do we know what browser versions are supported?  What is the cut-off versions?  Should we be informing users the specific versions that aren't supported?

**Comment by Mwindo** [comment]
Here are my thoughts, but I think other opinions would be valuable:

- By default, I think our build configuration supports anything ~2017 or later. (This code [here](https://github.com/ustaxcourt/ef-cms/blob/76e8725c7a9ec8d77ced5863d9b23734c7ee49a2/esbuildHelper.mjs#L117) says, "Target browsers that have support for JavaScript modules, introduced in 2015 and fully supported by virtually all browsers a couple years later.")
- We load one version of pdfjs, which expects browsers from ~mid 2022 or later as of [this release](https://github.com/mozilla/pdfjs-dist/compare/v2.12.313...v2.13.216). Some (probably most) pdfjs features may still work on earlier browsers, but there are no guarantees. Anything that relies on pdfjs thus _de facto_ restricts us from ~2017-now (our default from above) to ~2022-now.
- If there have not been other "older browser" errors in the past, this indicates the system has been working well enough for those users, and I see no compelling reason why pdfjs (and more specifically, it seems, PDF validation) should be the thing that forces them to update. There are ways to load different versions of pdfjs to support older and newer browsers. I would prefer this solution.
- On the other hand, if we want to be more intentional about browsers we support and don't support, that should probably be a ticket. For older browsers (however we decide to define that), I think it would indeed be better (as you suggest) to let users know ASAP that they "are using an unsupported browser, so certain features may not work as expected."

So my overall recommendation for this ticket would be to add legacy pdfjs support (to support browsers before ~2022), and then wait and see what errors we receive after that. This might fix most--and maybe all--of the errors in this ticket while maintaining support for older (in this context, < ~2022) browsers. (This approach might also save time tracking down bugs that basically boil down to the same cause, i.e., "If you have a pre-2022 browser, who knows what errors will happen with our current usage of pdfjs--it expects a newer browser!")

**Comment by Mwindo** [comment]
I did a quick test, and it looks like we can load `pdfjs-legacy` and `pdfjs[-modern]` conditionally based on the client. (I tested on an old version of Safari and was able to upload pdfs as well as get the same error messages.) The more devices we can test the better, but this seems like a good path forward.
