### ISSUE TITLE
Blue Green Migrations can create incomplete Elasticsearch `efms-case` document

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#929]
When new DynamoDB tables are created and populated, such as Blue/Green migrations and Glue jobs, the`processStreamRecordsInteractor` can create incomplete cases in Elasticsearch that are missing practitioners, correspondence, hearings, etc.  

This is likely caused when the function [`processCaseEntries()`](https://github.com/ustaxcourt/ef-cms/blob/8cffcd93028e8108dee5f6f2bf3b78ff103cc84e/shared/src/business/useCases/processStreamRecordsInteractor.js#L84) queries the dynamoDB table that is currently being populated in order to get all rows associated with the case. This function is sometimes called before all the `case |...` rows have been written to the dynamoDB table. The result is case documents that are missing IRS petitioners and private practitioners and other data. When these uses login, their dashboards do not display all of their cases.

One possible solution is to wait until the complete dynamoDB table has been populated before populating the related Elasticsearch indices. Ideally this process will be automated, but it's not clear how to know when the SQS queue is finished populating the database.

**Comment by mark-meyer** [comment]
An example case with missing data currently in the migration environment is `229-20`. The case document in `efcms-case` shows:
```
     'irsPractitioners': {'L': []},
     'privatePractitioners': {'L': []}
```
even though this case both a private practitioner and an IRS Respondent.

**Comment by mark-meyer** [comment]
There may be an opportunity to decouple the re-indexing that happens when a dynamo table is created and populated during a mirgration from the day-to-day updates to dynamo. Both currently use the dynamo streams, but maybe there is an alternative. The streams work well for the day-to-day updates but become problematic during a migration because of the scale and the latent relationships in the data. This will become more difficult when this same stream processor need to also include document contents for full-text search.
